// Generated by `pnpm generate`. Do not edit.

import type { ClientElement, ReadonlyState } from "@backtickjs/core-schema";

export type {
  Array,
  ArrayConstructor,
  ArrayLike,
  Boolean,
  Children,
  Client,
  ClientElement,
  Math,
  Number,
  Prop,
  ReadonlyState,
  State,
  String,
} from "@backtickjs/core-schema";

export interface ForProps<T> {
  /**
   * The array to draw one thing per member of.
   */
  readonly each: T[];
  /**
   * @param index Where the member is, as storage: a position moves without the
   * member changing, so a drawing handed the number would hold the one it was
   * drawn at.
   */
  children(member: T, index: ReadonlyState<number>): ClientElement;
}
