// Generated by `pnpm generate`. Do not edit.

import type { ClientHandle, ReadonlyState } from "@backtickjs/language-schema";

export type {
  ArrayLike,
  Client,
  ClientFunction,
  ClientHandle,
  ClientUnknown,
  ClientValue,
  ReadonlyState,
  State,
} from "@backtickjs/language-schema";

declare const ClientElementBrand: unique symbol;
export interface ClientElement extends ClientHandle {
  readonly [ClientElementBrand]: never;
}

export interface ForProps<T> {
  /**
   * The array to draw one thing per member of.
   */
  readonly each: T[];
  /**
   * @param index Where the member is, as storage: a position moves without the
   * member changing, so a drawing handed the number would hold the one it was
   * drawn at.
   */
  children(member: T, index: ReadonlyState<number>): ClientElement;
}
