// Generated by `pnpm generate`. Do not edit.

import type {
  Client,
  ClientHandle,
  ClientValue,
  ReadonlyState,
} from "@backtickjs/language-schema";
import type { Prop } from "./Prop.js";

export type {
  ArrayLike,
  Client,
  ClientFunction,
  ClientHandle,
  ClientUnknown,
  ClientValue,
  ReadonlyState,
  State,
} from "@backtickjs/language-schema";

declare const ClientElementBrand: unique symbol;
export interface ClientElement extends ClientHandle {
  readonly [ClientElementBrand]: never;
}

export interface ForProps<T extends ClientValue> {
  /**
   * The array to draw one thing per member of.
   */
  each: Prop<T[]>;
  /**
   * @param index Where the member is, as storage: a position moves without the
   * member changing, so a drawing handed the number would hold the one it was
   * drawn at.
   */
  children: Client<(member: T, index: ReadonlyState<number>) => ClientElement>;
}

/** The elements this schema declares, and what each accepts. */
export interface IntrinsicElements {
  /**
   * An array, and what to draw for one member of it.
   *
   * `children` is a script whose value is a function, so the client is what
   * walks the array: it draws only the members that are new, and moves rather
   * than rebuilds the ones that are not. A member is named by its own identity
   * — there is no key, and a value replaced is a member replaced.
   *
   * A member is `ClientValue` here where it is `T` on the props: an intrinsic
   * tag has nowhere to bind a type parameter from a prop, so the child's
   * parameter is checked against the language's whole value domain rather than
   * against what `each` holds.
   */
  for: ForProps<ClientValue>;
}
