// Generated by `pnpm generate`. Do not edit.

import { createBuiltin, type Client } from "@backtickjs/language";

/**
 * How wide the display is, in pixels. 240 on this device.
 */
export const screenWidth: Client<() => number> = createBuiltin("screenWidth");

/**
 * How tall the display is, in pixels. 135 on this device.
 */
export const screenHeight: Client<() => number> = createBuiltin("screenHeight");

/**
 * How wide text would be, as `textWidth` measures it — for an app placing
 * something beside it.
 *
 * @param text What would be drawn.
 * @param size The size it would be drawn at. 1 where left out.
 */
export const textWidth: Client<(text: string, size?: number) => number> =
  createBuiltin("textWidth");

/**
 * The key pressed since this was last asked, or an empty string.
 *
 * Asked rather than delivered: a script that wants to know reads it, and one
 * that does not is not interrupted. A printable key is itself; the rest are
 * named — `enter`, `backspace`, `up`, `down`, `left`, `right`, `tab`,
 * `escape`.
 */
export const key: Client<() => string> = createBuiltin("key");

/**
 * Where the key `key` answered with sits, as the scanner numbers the keyboard
 * — 1 upwards, or 0 where nothing was pressed.
 *
 * The number under a key rather than what it says, for an app that wants to
 * know which key rather than which letter. Unlike `key` this is not spent by
 * reading it: both stand for the one press this drawing was given.
 */
export const keyCode: Client<() => number> = createBuiltin("keyCode");

/**
 * How long the device has been awake, in milliseconds. What an app animating
 * something reads, since a frame is drawn when a value moves.
 */
export const millis: Client<() => number> = createBuiltin("millis");

/**
 * What the battery holds, 0 to 100.
 */
export const battery: Client<() => number> = createBuiltin("battery");
