// Generated by `pnpm generate`. Do not edit.

import type { BacktickNode, Prop } from "@backtickjs/boundary";
import type {
  Builtins as UiBuiltins,
  Elements as UiElements,
} from "@backtickjs/ui-schema";

export type {
  ArrayLike,
  BacktickProps,
  Bytes,
  ForProps,
  ReadonlyState,
  RequestInit,
  Response,
  State,
} from "@backtickjs/ui-schema";

/**
 * Text, as `drawString` draws it.
 *
 * `children` is what it says. A number is written as the language writes one,
 * so a count needs no formatting to be drawn.
 */
export interface StringProps {
  x: Prop<number>;
  y: Prop<number>;
  colour?: Prop<number>;
  size?: Prop<number>;
  datum?: Prop<string>;
  children?: BacktickNode;
}

/**
 * A rectangle, as `fillRect` and `drawRect` draw one.
 */
export interface RectProps {
  x: Prop<number>;
  y: Prop<number>;
  colour?: Prop<number>;
  fill?: Prop<boolean>;
  width: Prop<number>;
  height: Prop<number>;
  radius?: Prop<number>;
}

/**
 * A circle, as `fillCircle` and `drawCircle` draw one.
 */
export interface CircleProps {
  x: Prop<number>;
  y: Prop<number>;
  colour?: Prop<number>;
  fill?: Prop<boolean>;
  radius: Prop<number>;
}

/**
 * An ellipse, as `fillEllipse` and `drawEllipse` draw one.
 */
export interface EllipseProps {
  x: Prop<number>;
  y: Prop<number>;
  colour?: Prop<number>;
  fill?: Prop<boolean>;
  width: Prop<number>;
  height: Prop<number>;
}

/**
 * A line from one point to another, as `drawLine` draws it.
 */
export interface LineProps {
  x: Prop<number>;
  y: Prop<number>;
  colour?: Prop<number>;
  toX: Prop<number>;
  toY: Prop<number>;
}

/**
 * A triangle, as `fillTriangle` and `drawTriangle` draw one. `x` and `y` are
 * its first corner and the other two are named.
 */
export interface TriangleProps {
  x: Prop<number>;
  y: Prop<number>;
  colour?: Prop<number>;
  fill?: Prop<boolean>;
  x2: Prop<number>;
  y2: Prop<number>;
  x3: Prop<number>;
  y3: Prop<number>;
}

/**
 * One pixel, as `drawPixel` draws it.
 */
export interface PixelProps {
  x: Prop<number>;
  y: Prop<number>;
  colour?: Prop<number>;
}

/**
 * An arc between two angles in degrees, as `fillArc` and `drawArc` draw one.
 */
export interface ArcProps {
  x: Prop<number>;
  y: Prop<number>;
  colour?: Prop<number>;
  fill?: Prop<boolean>;
  radius: Prop<number>;
  innerRadius: Prop<number>;
  start: Prop<number>;
  end: Prop<number>;
}

/** The elements this schema declares, and what each accepts. */
export interface CardputerElements {
  string: StringProps;
  rect: RectProps;
  circle: CircleProps;
  ellipse: EllipseProps;
  line: LineProps;
  triangle: TriangleProps;
  pixel: PixelProps;
  arc: ArcProps;
}

/** Every element in scope, this schema's own and its bases'. */
export interface Elements extends UiElements, CardputerElements {}

/** What this schema declares, which is what its own client answers for. */
export interface CardputerBuiltins {
  /**
   * How wide the display is, in pixels. 240 on this device.
   */
  screenWidth(): number;
  /**
   * How tall the display is, in pixels. 135 on this device.
   */
  screenHeight(): number;
  /**
   * How wide text would be, as `textWidth` measures it — for an app placing
   * something beside it.
   *
   * @param text What would be drawn.
   * @param size The size it would be drawn at. 1 where left out.
   */
  textWidth(text: string, size?: number): number;
  /**
   * The key pressed since this was last asked, or an empty string.
   *
   * Asked rather than delivered: a script that wants to know reads it, and one
   * that does not is not interrupted. A printable key is itself; the rest are
   * named — `enter`, `backspace`, `up`, `down`, `left`, `right`, `tab`,
   * `escape`.
   */
  key(): string;
  /**
   * Where the key `key` answered with sits, as the scanner numbers the
   * keyboard — 1 upwards, or 0 where nothing was pressed.
   *
   * The number under a key rather than what it says, for an app that wants to
   * know which key rather than which letter. Unlike `key` this is not spent by
   * reading it: both stand for the one press this drawing was given.
   */
  keyCode(): number;
  /**
   * How long the device has been awake, in milliseconds. What an app animating
   * something reads, since a frame is drawn when a value moves.
   */
  millis(): number;
  /**
   * What the battery holds, 0 to 100.
   */
  battery(): number;
}

/** What a client must answer with, for every name in scope. */
export interface Builtins extends UiBuiltins, CardputerBuiltins {}
