// Writes each Test262 group as a module of cases the server imports as it is
// asked for one, so a case reaches a client the way any `cs` script does:
// compiled by the plugin when its module loads.
//
// Into `.cache/`, not `src/`: what the corpus holds is untyped JavaScript, and
// the corpus itself is what is committed.
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { judgeCase } from "./judgeCase.js";

const ROOT = join(import.meta.dir, "..");
const CORPUS = join(ROOT, "test262/test");
// ECMA-262's own tests. Not `intl402`, which is ECMA-402; not `staging`, which
// is proposals; not `harness`, which tests Test262's harness.
const SUITES = ["annexB", "built-ins", "language"];
const OUT = join(ROOT, ".cache/test262");

const groups = new Map<string, string[]>();
const entries = SUITES.flatMap((suite) =>
  readdirSync(join(CORPUS, suite), { recursive: true, withFileTypes: true }),
);
for (const entry of entries) {
  // A fixture is imported by the case beside it, not run on its own.
  if (!entry.isFile() || !entry.name.endsWith(".js")) continue;
  if (entry.name.endsWith("_FIXTURE.js")) continue;
  const group = relative(CORPUS, entry.parentPath);
  groups.set(group, [...(groups.get(group) ?? []), entry.name]);
}

// JSON, with anything past ASCII escaped: the plugin garbles it in host code.
const literal = (value: unknown) =>
  JSON.stringify(value).replace(
    /[\u007f-￿]/g,
    (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`,
  );

rmSync(OUT, { recursive: true, force: true });
for (const [group, files] of groups) {
  const out = join(OUT, `${group}.ts`);
  const src = (file: string) =>
    literal(relative(dirname(out), join(ROOT, "src", file)));
  const cases = files.sort().map((file) => {
    const name = file.replace(/\.js$/, "");
    const judged = judgeCase(
      name,
      readFileSync(join(CORPUS, group, file), "utf8"),
    );
    const script =
      "verdict" in judged
        ? `decided(${literal({ name, ...judged.verdict })})`
        : `verdict({ name: ${literal(name)}, negative: ${judged.negative}, run: cs\`${judged.script}\` })`;
    return `  { name: ${literal(name)}, script: ${script} },\n`;
  });
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(
    out,
    `// Generated by \`pnpm build\` from test262/test/${group}. Do not edit.\n` +
      'import { cs } from "@backtickjs/core";\n' +
      `import { decided, verdict } from ${src("Case.js")};\n` +
      `import { assert, compareArray, Test262Error } from ${src("test262/harness.js")};\n\n` +
      `export const cases = [\n${cases.join("")}];\n`,
  );
}
writeFileSync(
  join(OUT, "groups.json"),
  `${JSON.stringify([...groups.keys()].sort(), null, 2)}\n`,
);
console.log(`${groups.size} groups written to ${relative(ROOT, OUT)}`);
