// Writes each Test262 group as a module of cases the server imports as it is
// asked for one, so a case reaches a client the way any `cs` script does:
// compiled by the plugin when its module loads.
//
// Into `.cache/`, not `src/`: what the corpus holds is untyped JavaScript, and
// the corpus itself is what is committed.
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import { judgeCase } from "./judgeCase.js";
import type { Judgement } from "./judgeCase.js";

const ROOT = join(import.meta.dir, "..");
const CORPUS = join(ROOT, "test262/test");
// ECMA-262's own tests. Not `intl402`, which is ECMA-402; not `staging`, which
// is proposals; not `harness`, which tests Test262's harness.
const SUITES = ["annexB", "built-ins", "language"];
const OUT = join(ROOT, ".cache/test262");

const groups = new Map<string, string[]>();
const entries = SUITES.flatMap((suite) =>
  readdirSync(join(CORPUS, suite), { recursive: true, withFileTypes: true }),
);
for (const entry of entries) {
  // A fixture is imported by the case beside it, not run on its own.
  if (!entry.isFile() || !entry.name.endsWith(".js")) continue;
  if (entry.name.endsWith("_FIXTURE.js")) continue;
  const group = relative(CORPUS, entry.parentPath);
  groups.set(group, [...(groups.get(group) ?? []), entry.name]);
}

// JSON, with anything past ASCII escaped: the plugin garbles it in host code.
const literal = (value: unknown) =>
  JSON.stringify(value).replace(
    /[\u007f-￿]/g,
    (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, "0")}`,
  );

const judged = new Map<string, { name: string; judgement: Judgement }[]>();
for (const [group, files] of groups) {
  judged.set(
    group,
    files.sort().map((file) => {
      const name = file.replace(/\.js$/, "");
      const source = readFileSync(join(CORPUS, group, file), "utf8");
      return { name, judgement: judgeCase(name, source) };
    }),
  );
}

// Written twice: first with every script a case compiled to, for the type
// checker to read, then with what it refused decided rather than run.
rmSync(OUT, { recursive: true, force: true });
const refused = typecheck(write(null));
write(refused);

/** A group's module, as the lines it wrote and the line each case starts at. */
type Written = { lines: string[]; starts: { name: string; line: number }[] };

function write(refused: Map<string, string> | null): Map<string, Written> {
  const written = new Map<string, Written>();
  for (const [group, cases] of judged) {
    const out = join(OUT, `${group}.ts`);
    const src = (file: string) =>
      literal(relative(dirname(out), join(ROOT, "src", file)));
    let text =
      `// Generated by \`pnpm build\` from test262/test/${group}. Do not edit.\n` +
      'import { cs } from "@backtickjs/core";\n' +
      `import { decided, verdict } from ${src("Case.js")};\n` +
      `import { assert, compareArray, DONOTEVALUATE, Test262Error } from ${src("test262/harness.js")};\n\n` +
      "export const cases = [\n";
    const starts: Written["starts"] = [];
    for (const { name, judgement } of cases) {
      starts.push({ name, line: text.split("\n").length });
      const script = scriptOf(name, judgement, refused, `${group}/${name}`);
      text += `  { name: ${literal(name)}, script: ${script} },\n`;
    }
    text += "];\n";
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, text);
    written.set(group, { lines: text.split("\n"), starts });
  }
  return written;
}

// A case's script: its verdict where the host reached one, and otherwise what
// the client runs. Before the type checker has read it, every script is one.
function scriptOf(
  name: string,
  judgement: Judgement,
  refused: Map<string, string> | null,
  key: string,
): string {
  const decide = (outcome: string, detail: string) =>
    `decided(${literal({ name, outcome, detail })})`;
  if ("verdict" in judgement) {
    return `decided(${literal({ name, ...judgement.verdict })})`;
  }
  const refusal = refused?.get(key);
  if (refused !== null && judgement.early !== null) {
    // Refused by the checker is refused by the language: what an early error
    // asks for.
    return refusal === undefined
      ? decide(
          "fail",
          `compiled, where ECMAScript rejects it with a ${judgement.early}`,
        )
      : decide("pass", "");
  }
  if (refusal !== undefined) {
    return decide("fail", `refused by the type checker: ${refusal}`);
  }
  return `verdict({ name: ${literal(name)}, negative: ${judgement.negative}, run: cs\`${judgement.script}\` })`;
}

/**
 * What \`backtick-tsc\` refuses in the modules \`write\` wrote, by case: each
 * message once, at the first line it is about. Strict, since a lax checker
 * widens \`null\` to \`any\` and passes what a client refuses.
 */
function typecheck(written: Map<string, Written>): Map<string, string> {
  const config = join(OUT, "tsconfig.json");
  writeFileSync(
    config,
    JSON.stringify({
      extends: relative(OUT, join(ROOT, "tsconfig.json")),
      compilerOptions: { strict: true, skipLibCheck: true },
      include: ["**/*.ts"],
    }),
  );
  const { exitCode, stdout, stderr } = Bun.spawnSync(
    [
      join(ROOT, "node_modules/.bin/backtick-tsc"),
      "--noEmit",
      "--pretty",
      "false",
      "-p",
      config,
    ],
    { cwd: ROOT },
  );
  // 2 is tsc's "errors were reported"; anything else is the tool failing.
  if (exitCode !== 0 && exitCode !== 2) {
    throw new Error(`backtick-tsc failed: ${stderr.toString()}`);
  }

  // One diagnostic a line, and a chained message's details indented after it.
  const diagnostics: { file: string; line: number; message: string }[] = [];
  for (const line of stdout.toString().split("\n")) {
    const head = /^(.+)\((\d+),\d+\): error TS\d+: (.*)$/.exec(line);
    if (head) {
      diagnostics.push({ file: head[1]!, line: +head[2]!, message: head[3]! });
    } else if (/^\s+\S/.test(line) && diagnostics.length > 0) {
      diagnostics.at(-1)!.message += ` ${line.trim()}`;
    } else if (line.trim() !== "") {
      throw new Error(`backtick-tsc said what this can't read: ${line}`);
    }
  }

  const found = new Map<string, Map<string, string>>();
  for (const { file, line, message } of diagnostics) {
    const group = relative(OUT, join(ROOT, file)).replace(/\.ts$/, "");
    const at = written.get(group)?.starts.findLast((one) => one.line <= line);
    // Outside every case: the harness or the module around the cases.
    if (at === undefined) {
      throw new Error(`${file}(${line}): ${message}`);
    }
    const key = `${group}/${at.name}`;
    const messages = found.get(key) ?? new Map<string, string>();
    const text = written.get(group)!.lines[line - 1]!.trim();
    if (!messages.has(message)) messages.set(message, `${message}: ${text}`);
    found.set(key, messages);
  }
  return new Map(
    [...found].map(([key, messages]) => [
      key,
      [...messages.values()].join("; "),
    ]),
  );
}

writeFileSync(
  join(OUT, "groups.json"),
  `${JSON.stringify([...groups.keys()].sort(), null, 2)}\n`,
);
console.log(`${groups.size} groups written to ${relative(ROOT, OUT)}`);
