// Generated by `pnpm generate`. Do not edit.

import type {
  BacktickElement,
  BacktickNode,
  Client,
  ClientValue,
  Prop,
} from "@backtickjs/boundary";
import type {
  Builtins as LanguageBuiltins,
  Elements as LanguageElements,
  ReadonlyState,
} from "@backtickjs/language-schema";

export type {
  ArrayLike,
  Bytes,
  ReadonlyState,
  RequestInit,
  Response,
  State,
} from "@backtickjs/language-schema";

export interface ForProps<T extends ClientValue> {
  /**
   * The array to draw one thing per member of.
   */
  each: Prop<T[]>;
  /**
   * @param index Where the member is, as storage rather than a number: a
   * position moves without the member changing, so a number read once would go
   * stale.
   */
  children: Client<
    (member: T, index: ReadonlyState<number>) => BacktickElement
  >;
}

export interface FragmentProps {
  children?: BacktickNode;
}

export interface BacktickProps {
  /**
   * What the bundle is handed, under the name `props`.
   *
   * A bundle written elsewhere reads it the way any script reads a name it did
   * not write. A live value stays live: reading a splice is calling it, so a
   * drawing handed a cell redraws when the cell changes rather than being
   * built again.
   *
   * Unchecked here where `<Backtick />` checks it against what the bundle
   * takes, for the reason `<For />` exists: a tag has nowhere to bind a type
   * parameter.
   */
  props?: Prop<{ [key: string]: ClientValue | undefined }>;
  /**
   * The bundle to draw, as the text it is on the wire — what `response.text`
   * answers with, and what a document carries.
   *
   * Null draws nothing, which is what a page with no bundle yet has to say. It
   * is admitted here because a cell that is sometimes empty cannot be narrowed
   * on its way in: a script reads a cell where it stands, and a read moved out
   * to a `const` to be narrowed is a read that happens once and never again.
   * So a page that wants something in the meantime writes the condition it
   * already has — `held.read() === null ? … : <backtick bundle={held.read()}
   * />` — and a page that wants nothing writes the tag and lets the null
   * through.
   */
  bundle: Prop<string | null>;
}

/** The elements this schema declares, and what each accepts. */
export interface UiElements {
  /**
   * An array, and what to draw for one member of it.
   *
   * `children` is a script whose value is a function, so the client walks the
   * array itself: it draws only the members that are new and moves the rest
   * rather than rebuilding them. A member is named by its own identity — there
   * is no key.
   *
   * A member is `ClientValue` here where it is `T` on the props, because a tag
   * has nowhere to bind a type parameter. Write `<For />` to have the child
   * checked against what `each` holds.
   */
  for: ForProps<ClientValue>;
  /**
   * Children with no element of their own: what it holds goes where it stands.
   *
   * What it is for is the position. A drawing that is not an element has
   * nowhere to be watched — a conditional standing at a block's root is read
   * inside whatever computation asked for it, and the write that answers the
   * conditional runs the block again. Under a fragment the conditional is a
   * child, and a child position is watched on its own.
   *
   * Written `<>`, which TypeScript resolves to this name. Capitalized where
   * the other two are not, because a lowercase first letter is what makes a
   * tag a target's own — so no target can declare an element named this.
   */
  Fragment: FragmentProps;
  /**
   * A bundle, drawn here.
   *
   * One a script was handed rather than one the page was built with — fetched,
   * stored, passed in. Every client evaluates bundles already, which is why
   * this is the language's and not a target's: what draws it is the same
   * client that drew the one it stands in.
   */
  backtick: BacktickProps;
}

/** Every element in scope, this schema's own and its bases'. */
export interface Elements extends LanguageElements, UiElements {}

/** What this schema declares, which is what its own client answers for. */
export interface UiBuiltins {}

/** What a client must answer with, for every name in scope. */
export interface Builtins extends LanguageBuiltins, UiBuiltins {}
