// Generated by `pnpm generate`. Do not edit.

import type {
  BacktickElement,
  Client,
  ClientValue,
  Prop,
} from "@backtickjs/boundary";
import type {
  Builtins as LanguageBuiltins,
  Elements as LanguageElements,
  ReadonlyState,
} from "@backtickjs/language-schema";

export type {
  ArrayLike,
  Bytes,
  ReadonlyState,
  RequestInit,
  Response,
  State,
} from "@backtickjs/language-schema";

export interface ForProps<T extends ClientValue> {
  /**
   * The array to draw one thing per member of.
   */
  each: Prop<T[]>;
  /**
   * @param index Where the member is, as storage rather than a number: a
   * position moves without the member changing, so a number read once would go
   * stale.
   */
  children: Client<
    (member: T, index: ReadonlyState<number>) => BacktickElement
  >;
}

export interface BacktickProps {
  /**
   * The bundle to draw, as the text it is on the wire — what `response.text`
   * answers with, and what a document carries.
   *
   * Null draws nothing, which is what a page with no bundle yet has to say. It
   * is admitted here because a cell that is sometimes empty cannot be narrowed
   * on its way in: a script reads a cell where it stands, and a read moved out
   * to a `const` to be narrowed is a read that happens once and never again.
   * So a page that wants something in the meantime writes the condition it
   * already has — `held.read() === null ? … : <backtick bundle={held.read()}
   * />` — and a page that wants nothing writes the tag and lets the null
   * through.
   */
  bundle: Prop<string | null>;
}

/** The elements this schema declares, and what each accepts. */
export interface UiElements {
  /**
   * An array, and what to draw for one member of it.
   *
   * `children` is a script whose value is a function, so the client walks the
   * array itself: it draws only the members that are new and moves the rest
   * rather than rebuilding them. A member is named by its own identity — there
   * is no key.
   *
   * A member is `ClientValue` here where it is `T` on the props, because a tag
   * has nowhere to bind a type parameter. Write `<For />` to have the child
   * checked against what `each` holds.
   */
  for: ForProps<ClientValue>;
  /**
   * A bundle, drawn here.
   *
   * One a script was handed rather than one the page was built with — fetched,
   * stored, passed in. Every client evaluates bundles already, which is why
   * this is the language's and not a target's: what draws it is the same
   * client that drew the one it stands in.
   */
  backtick: BacktickProps;
}

/** Every element in scope, this schema's own and its bases'. */
export interface Elements extends LanguageElements, UiElements {}

/** What this schema declares, which is what its own client answers for. */
export interface UiBuiltins {}

/** What a client must answer with, for every name in scope. */
export interface Builtins extends LanguageBuiltins, UiBuiltins {}
