import { Type } from "typebox";
import type { JsxElement } from "@backtickjs/cs-runtime";

// What a browser's elements accept, as a schema. `elements.ts` is generated
// from this and is not written by hand — run `pnpm generate`.

export const aliases = {
  Booleanish: Type.Union([
    Type.Boolean(),
    Type.Literal("true"),
    Type.Literal("false"),
  ]),
  Numeric: Type.Union([Type.Number(), Type.String()]),
  AriaRole: Type.Union([
    Type.Literal("alert"),
    Type.Literal("alertdialog"),
    Type.Literal("application"),
    Type.Literal("article"),
    Type.Literal("banner"),
    Type.Literal("button"),
    Type.Literal("cell"),
    Type.Literal("checkbox"),
    Type.Literal("columnheader"),
    Type.Literal("combobox"),
    Type.Literal("complementary"),
    Type.Literal("contentinfo"),
    Type.Literal("definition"),
    Type.Literal("dialog"),
    Type.Literal("directory"),
    Type.Literal("document"),
    Type.Literal("feed"),
    Type.Literal("figure"),
    Type.Literal("form"),
    Type.Literal("grid"),
    Type.Literal("gridcell"),
    Type.Literal("group"),
    Type.Literal("heading"),
    Type.Literal("img"),
    Type.Literal("link"),
    Type.Literal("list"),
    Type.Literal("listbox"),
    Type.Literal("listitem"),
    Type.Literal("log"),
    Type.Literal("main"),
    Type.Literal("marquee"),
    Type.Literal("math"),
    Type.Literal("menu"),
    Type.Literal("menubar"),
    Type.Literal("menuitem"),
    Type.Literal("menuitemcheckbox"),
    Type.Literal("menuitemradio"),
    Type.Literal("navigation"),
    Type.Literal("none"),
    Type.Literal("note"),
    Type.Literal("option"),
    Type.Literal("presentation"),
    Type.Literal("progressbar"),
    Type.Literal("radio"),
    Type.Literal("radiogroup"),
    Type.Literal("region"),
    Type.Literal("row"),
    Type.Literal("rowgroup"),
    Type.Literal("rowheader"),
    Type.Literal("scrollbar"),
    Type.Literal("search"),
    Type.Literal("searchbox"),
    Type.Literal("separator"),
    Type.Literal("slider"),
    Type.Literal("spinbutton"),
    Type.Literal("status"),
    Type.Literal("switch"),
    Type.Literal("tab"),
    Type.Literal("table"),
    Type.Literal("tablist"),
    Type.Literal("tabpanel"),
    Type.Literal("term"),
    Type.Literal("textbox"),
    Type.Literal("timer"),
    Type.Literal("toolbar"),
    Type.Literal("tooltip"),
    Type.Literal("tree"),
    Type.Literal("treegrid"),
    Type.Literal("treeitem"),
    Type.Intersect([Type.String(), Type.Object({})]),
  ]),
  ReferrerPolicy: Type.Union([
    Type.Literal(""),
    Type.Literal("no-referrer"),
    Type.Literal("no-referrer-when-downgrade"),
    Type.Literal("origin"),
    Type.Literal("origin-when-cross-origin"),
    Type.Literal("same-origin"),
    Type.Literal("strict-origin"),
    Type.Literal("strict-origin-when-cross-origin"),
    Type.Literal("unsafe-url"),
  ]),
  CrossOrigin: Type.Union([
    Type.Literal("anonymous"),
    Type.Literal("use-credentials"),
    Type.Literal(""),
  ]),
  Target: Type.Union([
    Type.Literal("_self"),
    Type.Literal("_blank"),
    Type.Literal("_parent"),
    Type.Literal("_top"),
    Type.Intersect([Type.String(), Type.Object({})]),
  ]),
};

export const interfaces = {
  AriaAttributes: Type.Intersect([
    Type.Object({
      "aria-activedescendant": Type.Optional(Type.String()),
      "aria-atomic": Type.Optional(Type.Ref("Booleanish")),
      "aria-autocomplete": Type.Optional(
        Type.Union([
          Type.Literal("none"),
          Type.Literal("inline"),
          Type.Literal("list"),
          Type.Literal("both"),
        ]),
      ),
      "aria-braillelabel": Type.Optional(Type.String()),
      "aria-brailleroledescription": Type.Optional(Type.String()),
      "aria-busy": Type.Optional(Type.Ref("Booleanish")),
      "aria-checked": Type.Optional(
        Type.Union([
          Type.Boolean(),
          Type.Literal("false"),
          Type.Literal("mixed"),
          Type.Literal("true"),
        ]),
      ),
      "aria-colcount": Type.Optional(Type.Number()),
      "aria-colindex": Type.Optional(Type.Number()),
      "aria-colindextext": Type.Optional(Type.String()),
      "aria-colspan": Type.Optional(Type.Number()),
      "aria-controls": Type.Optional(Type.String()),
      "aria-current": Type.Optional(
        Type.Union([
          Type.Boolean(),
          Type.Literal("false"),
          Type.Literal("true"),
          Type.Literal("page"),
          Type.Literal("step"),
          Type.Literal("location"),
          Type.Literal("date"),
          Type.Literal("time"),
        ]),
      ),
      "aria-describedby": Type.Optional(Type.String()),
      "aria-description": Type.Optional(Type.String()),
      "aria-details": Type.Optional(Type.String()),
      "aria-disabled": Type.Optional(Type.Ref("Booleanish")),
      "aria-errormessage": Type.Optional(Type.String()),
      "aria-expanded": Type.Optional(Type.Ref("Booleanish")),
      "aria-flowto": Type.Optional(Type.String()),
      "aria-haspopup": Type.Optional(
        Type.Union([
          Type.Boolean(),
          Type.Literal("false"),
          Type.Literal("true"),
          Type.Literal("menu"),
          Type.Literal("listbox"),
          Type.Literal("tree"),
          Type.Literal("grid"),
          Type.Literal("dialog"),
        ]),
      ),
      "aria-hidden": Type.Optional(Type.Ref("Booleanish")),
      "aria-invalid": Type.Optional(
        Type.Union([
          Type.Boolean(),
          Type.Literal("false"),
          Type.Literal("true"),
          Type.Literal("grammar"),
          Type.Literal("spelling"),
        ]),
      ),
      "aria-keyshortcuts": Type.Optional(Type.String()),
      "aria-label": Type.Optional(Type.String()),
      "aria-labelledby": Type.Optional(Type.String()),
      "aria-level": Type.Optional(Type.Number()),
      "aria-live": Type.Optional(
        Type.Union([
          Type.Literal("off"),
          Type.Literal("assertive"),
          Type.Literal("polite"),
        ]),
      ),
      "aria-modal": Type.Optional(Type.Ref("Booleanish")),
      "aria-multiline": Type.Optional(Type.Ref("Booleanish")),
      "aria-multiselectable": Type.Optional(Type.Ref("Booleanish")),
      "aria-orientation": Type.Optional(
        Type.Union([Type.Literal("horizontal"), Type.Literal("vertical")]),
      ),
      "aria-owns": Type.Optional(Type.String()),
      "aria-placeholder": Type.Optional(Type.String()),
      "aria-posinset": Type.Optional(Type.Number()),
      "aria-pressed": Type.Optional(
        Type.Union([
          Type.Boolean(),
          Type.Literal("false"),
          Type.Literal("mixed"),
          Type.Literal("true"),
        ]),
      ),
      "aria-readonly": Type.Optional(Type.Ref("Booleanish")),
      "aria-relevant": Type.Optional(
        Type.Union([
          Type.Literal("additions"),
          Type.Literal("additions removals"),
          Type.Literal("additions text"),
          Type.Literal("all"),
          Type.Literal("removals"),
          Type.Literal("removals additions"),
          Type.Literal("removals text"),
          Type.Literal("text"),
          Type.Literal("text additions"),
          Type.Literal("text removals"),
        ]),
      ),
      "aria-required": Type.Optional(Type.Ref("Booleanish")),
      "aria-roledescription": Type.Optional(Type.String()),
      "aria-rowcount": Type.Optional(Type.Number()),
      "aria-rowindex": Type.Optional(Type.Number()),
      "aria-rowindextext": Type.Optional(Type.String()),
      "aria-rowspan": Type.Optional(Type.Number()),
      "aria-selected": Type.Optional(Type.Ref("Booleanish")),
      "aria-setsize": Type.Optional(Type.Number()),
      "aria-sort": Type.Optional(
        Type.Union([
          Type.Literal("none"),
          Type.Literal("ascending"),
          Type.Literal("descending"),
          Type.Literal("other"),
        ]),
      ),
      "aria-valuemax": Type.Optional(Type.Number()),
      "aria-valuemin": Type.Optional(Type.Number()),
      "aria-valuenow": Type.Optional(Type.Number()),
      "aria-valuetext": Type.Optional(Type.String()),
    }),
  ]),
  Events: Type.Intersect([
    Type.Object({
      oncopy: Type.Optional(Type.Function([], Type.Void())),
      oncut: Type.Optional(Type.Function([], Type.Void())),
      onpaste: Type.Optional(Type.Function([], Type.Void())),
      oncompositionend: Type.Optional(Type.Function([], Type.Void())),
      oncompositionstart: Type.Optional(Type.Function([], Type.Void())),
      oncompositionupdate: Type.Optional(Type.Function([], Type.Void())),
      onblur: Type.Optional(Type.Function([], Type.Void())),
      onfocus: Type.Optional(Type.Function([], Type.Void())),
      onfocusin: Type.Optional(Type.Function([], Type.Void())),
      onfocusout: Type.Optional(Type.Function([], Type.Void())),
      onbeforeinput: Type.Optional(Type.Function([], Type.Void())),
      onchange: Type.Optional(Type.Function([], Type.Void())),
      oninput: Type.Optional(Type.Function([], Type.Void())),
      oninvalid: Type.Optional(Type.Function([], Type.Void())),
      onreset: Type.Optional(Type.Function([], Type.Void())),
      onselect: Type.Optional(Type.Function([], Type.Void())),
      onsubmit: Type.Optional(Type.Function([], Type.Void())),
      onerror: Type.Optional(Type.Function([], Type.Void())),
      onload: Type.Optional(Type.Function([], Type.Void())),
      onkeydown: Type.Optional(Type.Function([], Type.Void())),
      onkeypress: Type.Optional(Type.Function([], Type.Void())),
      onkeyup: Type.Optional(Type.Function([], Type.Void())),
      onabort: Type.Optional(Type.Function([], Type.Void())),
      oncanplay: Type.Optional(Type.Function([], Type.Void())),
      oncanplaythrough: Type.Optional(Type.Function([], Type.Void())),
      ondurationchange: Type.Optional(Type.Function([], Type.Void())),
      onemptied: Type.Optional(Type.Function([], Type.Void())),
      onended: Type.Optional(Type.Function([], Type.Void())),
      onloadeddata: Type.Optional(Type.Function([], Type.Void())),
      onloadedmetadata: Type.Optional(Type.Function([], Type.Void())),
      onloadstart: Type.Optional(Type.Function([], Type.Void())),
      onpause: Type.Optional(Type.Function([], Type.Void())),
      onplay: Type.Optional(Type.Function([], Type.Void())),
      onplaying: Type.Optional(Type.Function([], Type.Void())),
      onprogress: Type.Optional(Type.Function([], Type.Void())),
      onratechange: Type.Optional(Type.Function([], Type.Void())),
      onseeked: Type.Optional(Type.Function([], Type.Void())),
      onseeking: Type.Optional(Type.Function([], Type.Void())),
      onstalled: Type.Optional(Type.Function([], Type.Void())),
      onsuspend: Type.Optional(Type.Function([], Type.Void())),
      ontimeupdate: Type.Optional(Type.Function([], Type.Void())),
      onvolumechange: Type.Optional(Type.Function([], Type.Void())),
      onwaiting: Type.Optional(Type.Function([], Type.Void())),
      onauxclick: Type.Optional(Type.Function([], Type.Void())),
      onclick: Type.Optional(Type.Function([], Type.Void())),
      oncontextmenu: Type.Optional(Type.Function([], Type.Void())),
      ondblclick: Type.Optional(Type.Function([], Type.Void())),
      onmousedown: Type.Optional(Type.Function([], Type.Void())),
      onmouseenter: Type.Optional(Type.Function([], Type.Void())),
      onmouseleave: Type.Optional(Type.Function([], Type.Void())),
      onmousemove: Type.Optional(Type.Function([], Type.Void())),
      onmouseout: Type.Optional(Type.Function([], Type.Void())),
      onmouseover: Type.Optional(Type.Function([], Type.Void())),
      onmouseup: Type.Optional(Type.Function([], Type.Void())),
      ondrag: Type.Optional(Type.Function([], Type.Void())),
      ondragend: Type.Optional(Type.Function([], Type.Void())),
      ondragenter: Type.Optional(Type.Function([], Type.Void())),
      ondragleave: Type.Optional(Type.Function([], Type.Void())),
      ondragover: Type.Optional(Type.Function([], Type.Void())),
      ondragstart: Type.Optional(Type.Function([], Type.Void())),
      ondrop: Type.Optional(Type.Function([], Type.Void())),
      ontouchcancel: Type.Optional(Type.Function([], Type.Void())),
      ontouchend: Type.Optional(Type.Function([], Type.Void())),
      ontouchmove: Type.Optional(Type.Function([], Type.Void())),
      ontouchstart: Type.Optional(Type.Function([], Type.Void())),
      ongotpointercapture: Type.Optional(Type.Function([], Type.Void())),
      onlostpointercapture: Type.Optional(Type.Function([], Type.Void())),
      onpointercancel: Type.Optional(Type.Function([], Type.Void())),
      onpointerdown: Type.Optional(Type.Function([], Type.Void())),
      onpointerenter: Type.Optional(Type.Function([], Type.Void())),
      onpointerleave: Type.Optional(Type.Function([], Type.Void())),
      onpointermove: Type.Optional(Type.Function([], Type.Void())),
      onpointerout: Type.Optional(Type.Function([], Type.Void())),
      onpointerover: Type.Optional(Type.Function([], Type.Void())),
      onpointerup: Type.Optional(Type.Function([], Type.Void())),
      onscroll: Type.Optional(Type.Function([], Type.Void())),
      onscrollend: Type.Optional(Type.Function([], Type.Void())),
      onwheel: Type.Optional(Type.Function([], Type.Void())),
      onanimationend: Type.Optional(Type.Function([], Type.Void())),
      onanimationiteration: Type.Optional(Type.Function([], Type.Void())),
      onanimationstart: Type.Optional(Type.Function([], Type.Void())),
      ontransitioncancel: Type.Optional(Type.Function([], Type.Void())),
      ontransitionend: Type.Optional(Type.Function([], Type.Void())),
      ontransitionrun: Type.Optional(Type.Function([], Type.Void())),
      ontransitionstart: Type.Optional(Type.Function([], Type.Void())),
      onbeforetoggle: Type.Optional(Type.Function([], Type.Void())),
      ontoggle: Type.Optional(Type.Function([], Type.Void())),
    }),
  ]),
  GlobalAttributes: Type.Intersect([
    Type.Ref("AriaAttributes"),
    Type.Ref("Events"),
    Type.Object({
      accesskey: Type.Optional(Type.String()),
      autocapitalize: Type.Optional(
        Type.Union([
          Type.Literal("off"),
          Type.Literal("none"),
          Type.Literal("on"),
          Type.Literal("sentences"),
          Type.Literal("words"),
          Type.Literal("characters"),
        ]),
      ),
      autocorrect: Type.Optional(
        Type.Union([Type.Literal("on"), Type.Literal("off")]),
      ),
      autofocus: Type.Optional(Type.Boolean()),
      class: Type.Optional(Type.String()),
      contenteditable: Type.Optional(
        Type.Union([
          Type.Ref("Booleanish"),
          Type.Literal("inherit"),
          Type.Literal("plaintext-only"),
        ]),
      ),
      dir: Type.Optional(
        Type.Union([
          Type.Literal("ltr"),
          Type.Literal("rtl"),
          Type.Literal("auto"),
        ]),
      ),
      draggable: Type.Optional(Type.Ref("Booleanish")),
      enterkeyhint: Type.Optional(
        Type.Union([
          Type.Literal("enter"),
          Type.Literal("done"),
          Type.Literal("go"),
          Type.Literal("next"),
          Type.Literal("previous"),
          Type.Literal("search"),
          Type.Literal("send"),
        ]),
      ),
      exportparts: Type.Optional(Type.String()),
      hidden: Type.Optional(
        Type.Union([Type.Boolean(), Type.Literal("until-found")]),
      ),
      id: Type.Optional(Type.String()),
      inert: Type.Optional(Type.Boolean()),
      inputmode: Type.Optional(
        Type.Union([
          Type.Literal("none"),
          Type.Literal("text"),
          Type.Literal("tel"),
          Type.Literal("url"),
          Type.Literal("email"),
          Type.Literal("numeric"),
          Type.Literal("decimal"),
          Type.Literal("search"),
        ]),
      ),
      is: Type.Optional(Type.String()),
      itemid: Type.Optional(Type.String()),
      itemprop: Type.Optional(Type.String()),
      itemref: Type.Optional(Type.String()),
      itemscope: Type.Optional(Type.Boolean()),
      itemtype: Type.Optional(Type.String()),
      lang: Type.Optional(Type.String()),
      nonce: Type.Optional(Type.String()),
      part: Type.Optional(Type.String()),
      popover: Type.Optional(
        Type.Union([
          Type.Literal(""),
          Type.Literal("auto"),
          Type.Literal("manual"),
          Type.Literal("hint"),
        ]),
      ),
      role: Type.Optional(Type.Ref("AriaRole")),
      slot: Type.Optional(Type.String()),
      spellcheck: Type.Optional(Type.Ref("Booleanish")),
      style: Type.Optional(Type.String()),
      tabindex: Type.Optional(Type.Number()),
      title: Type.Optional(Type.String()),
      translate: Type.Optional(
        Type.Union([Type.Literal("yes"), Type.Literal("no")]),
      ),
    }),
  ]),
  VoidProps: Type.Intersect([Type.Ref("GlobalAttributes"), Type.Object({})]),
  HtmlProps: Type.Intersect([
    Type.Ref("GlobalAttributes"),
    Type.Object({
      children: Type.Optional(
        Type.Union([
          Type.Unsafe<JsxElement>({ $ref: "JsxElement" }),
          Type.String(),
          Type.Number(),
        ]),
      ),
    }),
  ]),
  AnchorProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      download: Type.Optional(Type.Union([Type.String(), Type.Boolean()])),
      href: Type.Optional(Type.String()),
      hreflang: Type.Optional(Type.String()),
      media: Type.Optional(Type.String()),
      ping: Type.Optional(Type.String()),
      referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
      rel: Type.Optional(Type.String()),
      target: Type.Optional(Type.Ref("Target")),
      type: Type.Optional(Type.String()),
    }),
  ]),
  AreaProps: Type.Intersect([
    Type.Ref("VoidProps"),
    Type.Object({
      alt: Type.Optional(Type.String()),
      coords: Type.Optional(Type.String()),
      download: Type.Optional(Type.Union([Type.String(), Type.Boolean()])),
      href: Type.Optional(Type.String()),
      referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
      rel: Type.Optional(Type.String()),
      shape: Type.Optional(
        Type.Union([
          Type.Literal("rect"),
          Type.Literal("circle"),
          Type.Literal("poly"),
          Type.Literal("default"),
        ]),
      ),
      target: Type.Optional(Type.Ref("Target")),
    }),
  ]),
  BaseProps: Type.Intersect([
    Type.Ref("VoidProps"),
    Type.Object({
      href: Type.Optional(Type.String()),
      target: Type.Optional(Type.Ref("Target")),
    }),
  ]),
  BlockquoteProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      cite: Type.Optional(Type.String()),
    }),
  ]),
  ButtonProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      disabled: Type.Optional(Type.Boolean()),
      form: Type.Optional(Type.String()),
      formaction: Type.Optional(Type.String()),
      formenctype: Type.Optional(Type.String()),
      formmethod: Type.Optional(
        Type.Union([
          Type.Literal("get"),
          Type.Literal("post"),
          Type.Literal("dialog"),
        ]),
      ),
      formnovalidate: Type.Optional(Type.Boolean()),
      formtarget: Type.Optional(Type.Ref("Target")),
      name: Type.Optional(Type.String()),
      popovertarget: Type.Optional(Type.String()),
      popovertargetaction: Type.Optional(
        Type.Union([
          Type.Literal("toggle"),
          Type.Literal("show"),
          Type.Literal("hide"),
        ]),
      ),
      type: Type.Optional(
        Type.Union([
          Type.Literal("submit"),
          Type.Literal("reset"),
          Type.Literal("button"),
        ]),
      ),
      value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
    }),
  ]),
  CanvasProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      height: Type.Optional(Type.Ref("Numeric")),
      width: Type.Optional(Type.Ref("Numeric")),
    }),
  ]),
  ColProps: Type.Intersect([
    Type.Ref("VoidProps"),
    Type.Object({
      span: Type.Optional(Type.Number()),
      width: Type.Optional(Type.Ref("Numeric")),
    }),
  ]),
  ColgroupProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      span: Type.Optional(Type.Number()),
    }),
  ]),
  DataProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
    }),
  ]),
  DelProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      cite: Type.Optional(Type.String()),
      datetime: Type.Optional(Type.String()),
    }),
  ]),
  DetailsProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      name: Type.Optional(Type.String()),
      open: Type.Optional(Type.Boolean()),
    }),
  ]),
  DialogProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      closedby: Type.Optional(
        Type.Union([
          Type.Literal("any"),
          Type.Literal("closerequest"),
          Type.Literal("none"),
        ]),
      ),
      open: Type.Optional(Type.Boolean()),
    }),
  ]),
  EmbedProps: Type.Intersect([
    Type.Ref("VoidProps"),
    Type.Object({
      height: Type.Optional(Type.Ref("Numeric")),
      src: Type.Optional(Type.String()),
      type: Type.Optional(Type.String()),
      width: Type.Optional(Type.Ref("Numeric")),
    }),
  ]),
  FieldsetProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      disabled: Type.Optional(Type.Boolean()),
      form: Type.Optional(Type.String()),
      name: Type.Optional(Type.String()),
    }),
  ]),
  FormProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      "accept-charset": Type.Optional(Type.String()),
      action: Type.Optional(Type.String()),
      autocomplete: Type.Optional(
        Type.Union([Type.Literal("on"), Type.Literal("off")]),
      ),
      enctype: Type.Optional(Type.String()),
      method: Type.Optional(
        Type.Union([
          Type.Literal("get"),
          Type.Literal("post"),
          Type.Literal("dialog"),
        ]),
      ),
      name: Type.Optional(Type.String()),
      novalidate: Type.Optional(Type.Boolean()),
      rel: Type.Optional(Type.String()),
      target: Type.Optional(Type.Ref("Target")),
    }),
  ]),
  HtmlElementProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      manifest: Type.Optional(Type.String()),
    }),
  ]),
  IframeProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      allow: Type.Optional(Type.String()),
      allowfullscreen: Type.Optional(Type.Boolean()),
      height: Type.Optional(Type.Ref("Numeric")),
      loading: Type.Optional(
        Type.Union([Type.Literal("eager"), Type.Literal("lazy")]),
      ),
      name: Type.Optional(Type.String()),
      referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
      sandbox: Type.Optional(Type.String()),
      src: Type.Optional(Type.String()),
      srcdoc: Type.Optional(Type.String()),
      width: Type.Optional(Type.Ref("Numeric")),
    }),
  ]),
  ImgProps: Type.Intersect([
    Type.Ref("VoidProps"),
    Type.Object({
      alt: Type.Optional(Type.String()),
      crossorigin: Type.Optional(Type.Ref("CrossOrigin")),
      decoding: Type.Optional(
        Type.Union([
          Type.Literal("async"),
          Type.Literal("auto"),
          Type.Literal("sync"),
        ]),
      ),
      fetchpriority: Type.Optional(
        Type.Union([
          Type.Literal("high"),
          Type.Literal("low"),
          Type.Literal("auto"),
        ]),
      ),
      height: Type.Optional(Type.Ref("Numeric")),
      loading: Type.Optional(
        Type.Union([Type.Literal("eager"), Type.Literal("lazy")]),
      ),
      referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
      sizes: Type.Optional(Type.String()),
      src: Type.Optional(Type.String()),
      srcset: Type.Optional(Type.String()),
      usemap: Type.Optional(Type.String()),
      width: Type.Optional(Type.Ref("Numeric")),
    }),
  ]),
  InputProps: Type.Intersect([
    Type.Ref("VoidProps"),
    Type.Object({
      accept: Type.Optional(Type.String()),
      alt: Type.Optional(Type.String()),
      autocomplete: Type.Optional(Type.String()),
      capture: Type.Optional(
        Type.Union([
          Type.Boolean(),
          Type.Literal("user"),
          Type.Literal("environment"),
        ]),
      ),
      checked: Type.Optional(Type.Boolean()),
      dirname: Type.Optional(Type.String()),
      disabled: Type.Optional(Type.Boolean()),
      form: Type.Optional(Type.String()),
      formaction: Type.Optional(Type.String()),
      formenctype: Type.Optional(Type.String()),
      formmethod: Type.Optional(
        Type.Union([
          Type.Literal("get"),
          Type.Literal("post"),
          Type.Literal("dialog"),
        ]),
      ),
      formnovalidate: Type.Optional(Type.Boolean()),
      formtarget: Type.Optional(Type.Ref("Target")),
      height: Type.Optional(Type.Ref("Numeric")),
      list: Type.Optional(Type.String()),
      max: Type.Optional(Type.Ref("Numeric")),
      maxlength: Type.Optional(Type.Number()),
      min: Type.Optional(Type.Ref("Numeric")),
      minlength: Type.Optional(Type.Number()),
      multiple: Type.Optional(Type.Boolean()),
      name: Type.Optional(Type.String()),
      pattern: Type.Optional(Type.String()),
      placeholder: Type.Optional(Type.String()),
      readonly: Type.Optional(Type.Boolean()),
      required: Type.Optional(Type.Boolean()),
      size: Type.Optional(Type.Number()),
      src: Type.Optional(Type.String()),
      step: Type.Optional(Type.Ref("Numeric")),
      type: Type.Optional(
        Type.Union([
          Type.Literal("button"),
          Type.Literal("checkbox"),
          Type.Literal("color"),
          Type.Literal("date"),
          Type.Literal("datetime-local"),
          Type.Literal("email"),
          Type.Literal("file"),
          Type.Literal("hidden"),
          Type.Literal("image"),
          Type.Literal("month"),
          Type.Literal("number"),
          Type.Literal("password"),
          Type.Literal("radio"),
          Type.Literal("range"),
          Type.Literal("reset"),
          Type.Literal("search"),
          Type.Literal("submit"),
          Type.Literal("tel"),
          Type.Literal("text"),
          Type.Literal("time"),
          Type.Literal("url"),
          Type.Literal("week"),
        ]),
      ),
      value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
      width: Type.Optional(Type.Ref("Numeric")),
    }),
  ]),
  InsProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      cite: Type.Optional(Type.String()),
      datetime: Type.Optional(Type.String()),
    }),
  ]),
  LabelProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      for: Type.Optional(Type.String()),
      form: Type.Optional(Type.String()),
    }),
  ]),
  LiProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      value: Type.Optional(Type.Number()),
    }),
  ]),
  LinkProps: Type.Intersect([
    Type.Ref("VoidProps"),
    Type.Object({
      as: Type.Optional(Type.String()),
      crossorigin: Type.Optional(Type.Ref("CrossOrigin")),
      fetchpriority: Type.Optional(
        Type.Union([
          Type.Literal("high"),
          Type.Literal("low"),
          Type.Literal("auto"),
        ]),
      ),
      href: Type.Optional(Type.String()),
      hreflang: Type.Optional(Type.String()),
      imagesizes: Type.Optional(Type.String()),
      imagesrcset: Type.Optional(Type.String()),
      integrity: Type.Optional(Type.String()),
      media: Type.Optional(Type.String()),
      referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
      rel: Type.Optional(Type.String()),
      sizes: Type.Optional(Type.String()),
      type: Type.Optional(Type.String()),
    }),
  ]),
  MapProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      name: Type.Optional(Type.String()),
    }),
  ]),
  MediaProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      autoplay: Type.Optional(Type.Boolean()),
      controls: Type.Optional(Type.Boolean()),
      controlslist: Type.Optional(Type.String()),
      crossorigin: Type.Optional(Type.Ref("CrossOrigin")),
      loop: Type.Optional(Type.Boolean()),
      muted: Type.Optional(Type.Boolean()),
      preload: Type.Optional(
        Type.Union([
          Type.Literal("none"),
          Type.Literal("metadata"),
          Type.Literal("auto"),
          Type.Literal(""),
        ]),
      ),
      src: Type.Optional(Type.String()),
    }),
  ]),
  MetaProps: Type.Intersect([
    Type.Ref("VoidProps"),
    Type.Object({
      charset: Type.Optional(Type.String()),
      content: Type.Optional(Type.String()),
      "http-equiv": Type.Optional(Type.String()),
      media: Type.Optional(Type.String()),
      name: Type.Optional(Type.String()),
    }),
  ]),
  MeterProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      form: Type.Optional(Type.String()),
      high: Type.Optional(Type.Number()),
      low: Type.Optional(Type.Number()),
      max: Type.Optional(Type.Ref("Numeric")),
      min: Type.Optional(Type.Ref("Numeric")),
      optimum: Type.Optional(Type.Number()),
      value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
    }),
  ]),
  ObjectProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      data: Type.Optional(Type.String()),
      form: Type.Optional(Type.String()),
      height: Type.Optional(Type.Ref("Numeric")),
      name: Type.Optional(Type.String()),
      type: Type.Optional(Type.String()),
      usemap: Type.Optional(Type.String()),
      width: Type.Optional(Type.Ref("Numeric")),
    }),
  ]),
  OlProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      reversed: Type.Optional(Type.Boolean()),
      start: Type.Optional(Type.Number()),
      type: Type.Optional(
        Type.Union([
          Type.Literal("1"),
          Type.Literal("a"),
          Type.Literal("A"),
          Type.Literal("i"),
          Type.Literal("I"),
        ]),
      ),
    }),
  ]),
  OptgroupProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      disabled: Type.Optional(Type.Boolean()),
      label: Type.Optional(Type.String()),
    }),
  ]),
  OptionProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      disabled: Type.Optional(Type.Boolean()),
      label: Type.Optional(Type.String()),
      selected: Type.Optional(Type.Boolean()),
      value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
    }),
  ]),
  OutputProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      for: Type.Optional(Type.String()),
      form: Type.Optional(Type.String()),
      name: Type.Optional(Type.String()),
    }),
  ]),
  ProgressProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      max: Type.Optional(Type.Ref("Numeric")),
      value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
    }),
  ]),
  QuoteProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      cite: Type.Optional(Type.String()),
    }),
  ]),
  ScriptProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      async: Type.Optional(Type.Boolean()),
      crossorigin: Type.Optional(Type.Ref("CrossOrigin")),
      defer: Type.Optional(Type.Boolean()),
      fetchpriority: Type.Optional(
        Type.Union([
          Type.Literal("high"),
          Type.Literal("low"),
          Type.Literal("auto"),
        ]),
      ),
      integrity: Type.Optional(Type.String()),
      nomodule: Type.Optional(Type.Boolean()),
      referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
      src: Type.Optional(Type.String()),
      type: Type.Optional(Type.String()),
    }),
  ]),
  SelectProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      autocomplete: Type.Optional(Type.String()),
      disabled: Type.Optional(Type.Boolean()),
      form: Type.Optional(Type.String()),
      multiple: Type.Optional(Type.Boolean()),
      name: Type.Optional(Type.String()),
      required: Type.Optional(Type.Boolean()),
      size: Type.Optional(Type.Number()),
      value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
    }),
  ]),
  SlotProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      name: Type.Optional(Type.String()),
    }),
  ]),
  SourceProps: Type.Intersect([
    Type.Ref("VoidProps"),
    Type.Object({
      height: Type.Optional(Type.Ref("Numeric")),
      media: Type.Optional(Type.String()),
      sizes: Type.Optional(Type.String()),
      src: Type.Optional(Type.String()),
      srcset: Type.Optional(Type.String()),
      type: Type.Optional(Type.String()),
      width: Type.Optional(Type.Ref("Numeric")),
    }),
  ]),
  StyleProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      media: Type.Optional(Type.String()),
      type: Type.Optional(Type.String()),
    }),
  ]),
  TableProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      summary: Type.Optional(Type.String()),
      width: Type.Optional(Type.Ref("Numeric")),
    }),
  ]),
  TdProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      colspan: Type.Optional(Type.Number()),
      headers: Type.Optional(Type.String()),
      rowspan: Type.Optional(Type.Number()),
    }),
  ]),
  ThProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      abbr: Type.Optional(Type.String()),
      colspan: Type.Optional(Type.Number()),
      headers: Type.Optional(Type.String()),
      rowspan: Type.Optional(Type.Number()),
      scope: Type.Optional(
        Type.Union([
          Type.Literal("row"),
          Type.Literal("col"),
          Type.Literal("rowgroup"),
          Type.Literal("colgroup"),
        ]),
      ),
    }),
  ]),
  TextareaProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      autocomplete: Type.Optional(Type.String()),
      cols: Type.Optional(Type.Number()),
      dirname: Type.Optional(Type.String()),
      disabled: Type.Optional(Type.Boolean()),
      form: Type.Optional(Type.String()),
      maxlength: Type.Optional(Type.Number()),
      minlength: Type.Optional(Type.Number()),
      name: Type.Optional(Type.String()),
      placeholder: Type.Optional(Type.String()),
      readonly: Type.Optional(Type.Boolean()),
      required: Type.Optional(Type.Boolean()),
      rows: Type.Optional(Type.Number()),
      value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
      wrap: Type.Optional(
        Type.Union([
          Type.Literal("hard"),
          Type.Literal("soft"),
          Type.Literal("off"),
        ]),
      ),
    }),
  ]),
  TimeProps: Type.Intersect([
    Type.Ref("HtmlProps"),
    Type.Object({
      datetime: Type.Optional(Type.String()),
    }),
  ]),
  TrackProps: Type.Intersect([
    Type.Ref("VoidProps"),
    Type.Object({
      default: Type.Optional(Type.Boolean()),
      kind: Type.Optional(
        Type.Union([
          Type.Literal("subtitles"),
          Type.Literal("captions"),
          Type.Literal("descriptions"),
          Type.Literal("chapters"),
          Type.Literal("metadata"),
        ]),
      ),
      label: Type.Optional(Type.String()),
      src: Type.Optional(Type.String()),
      srclang: Type.Optional(Type.String()),
    }),
  ]),
  VideoProps: Type.Intersect([
    Type.Ref("MediaProps"),
    Type.Object({
      disablepictureinpicture: Type.Optional(Type.Boolean()),
      disableremoteplayback: Type.Optional(Type.Boolean()),
      height: Type.Optional(Type.Ref("Numeric")),
      playsinline: Type.Optional(Type.Boolean()),
      poster: Type.Optional(Type.String()),
      width: Type.Optional(Type.Ref("Numeric")),
    }),
  ]),
};

// Keyed by tag, which is also the id the wire carries and the string
// `createElement` receives. Most of them share one shape, which is why this
// is a map onto interfaces rather than 112 declarations.
export const elements = {
  a: "AnchorProps",
  abbr: "HtmlProps",
  address: "HtmlProps",
  area: "AreaProps",
  article: "HtmlProps",
  aside: "HtmlProps",
  audio: "MediaProps",
  b: "HtmlProps",
  base: "BaseProps",
  bdi: "HtmlProps",
  bdo: "HtmlProps",
  blockquote: "BlockquoteProps",
  body: "HtmlProps",
  br: "VoidProps",
  button: "ButtonProps",
  canvas: "CanvasProps",
  caption: "HtmlProps",
  cite: "HtmlProps",
  code: "HtmlProps",
  col: "ColProps",
  colgroup: "ColgroupProps",
  data: "DataProps",
  datalist: "HtmlProps",
  dd: "HtmlProps",
  del: "DelProps",
  details: "DetailsProps",
  dfn: "HtmlProps",
  dialog: "DialogProps",
  div: "HtmlProps",
  dl: "HtmlProps",
  dt: "HtmlProps",
  em: "HtmlProps",
  embed: "EmbedProps",
  fieldset: "FieldsetProps",
  figcaption: "HtmlProps",
  figure: "HtmlProps",
  footer: "HtmlProps",
  form: "FormProps",
  h1: "HtmlProps",
  h2: "HtmlProps",
  h3: "HtmlProps",
  h4: "HtmlProps",
  h5: "HtmlProps",
  h6: "HtmlProps",
  head: "HtmlProps",
  header: "HtmlProps",
  hgroup: "HtmlProps",
  hr: "VoidProps",
  html: "HtmlElementProps",
  i: "HtmlProps",
  iframe: "IframeProps",
  img: "ImgProps",
  input: "InputProps",
  ins: "InsProps",
  kbd: "HtmlProps",
  label: "LabelProps",
  legend: "HtmlProps",
  li: "LiProps",
  link: "LinkProps",
  main: "HtmlProps",
  map: "MapProps",
  mark: "HtmlProps",
  menu: "HtmlProps",
  meta: "MetaProps",
  meter: "MeterProps",
  nav: "HtmlProps",
  noscript: "HtmlProps",
  object: "ObjectProps",
  ol: "OlProps",
  optgroup: "OptgroupProps",
  option: "OptionProps",
  output: "OutputProps",
  p: "HtmlProps",
  picture: "HtmlProps",
  pre: "HtmlProps",
  progress: "ProgressProps",
  q: "QuoteProps",
  rp: "HtmlProps",
  rt: "HtmlProps",
  ruby: "HtmlProps",
  s: "HtmlProps",
  samp: "HtmlProps",
  script: "ScriptProps",
  search: "HtmlProps",
  section: "HtmlProps",
  select: "SelectProps",
  slot: "SlotProps",
  small: "HtmlProps",
  source: "SourceProps",
  span: "HtmlProps",
  strong: "HtmlProps",
  style: "StyleProps",
  sub: "HtmlProps",
  summary: "HtmlProps",
  sup: "HtmlProps",
  table: "TableProps",
  tbody: "HtmlProps",
  td: "TdProps",
  template: "HtmlProps",
  textarea: "TextareaProps",
  tfoot: "HtmlProps",
  th: "ThProps",
  thead: "HtmlProps",
  time: "TimeProps",
  title: "HtmlProps",
  tr: "HtmlProps",
  track: "TrackProps",
  u: "HtmlProps",
  ul: "HtmlProps",
  var: "HtmlProps",
  video: "VideoProps",
  wbr: "VoidProps",
};
