import { Type } from "@backtickjs/schema";

// What a browser's elements accept, as a schema. `elements.ts` is generated
// from this and is not written by hand — run `pnpm generate`.

/**
 * What a child may be, which is this target's decision and not the framework's.
 *
 * That the web's tags hold text and numbers as well as elements is vocabulary,
 * and says so here. A target whose elements hold only text would write
 * `Type.String()` alone. `JsxElement` — anything this framework draws — is the
 * one name no type language outside TypeScript can say, so `Unsafe` supplies
 * it: a real `Ref`, so every guard reads it as one, wrapped to carry the type
 * that name stands for.
 *
 * One child, not several: the plural is `Children<T>`, which the emitter wraps
 * around this. Local rather than a named alias, because it is not a type this
 * target publishes — it is what two of its things happen to hold.
 */
const child = Type.Union([
  Type.Ref("JsxElement"),
  Type.String(),
  Type.Number(),
]);

export const aliases = {
  Booleanish: Type.Union([
    Type.Boolean(),
    Type.Literal("true"),
    Type.Literal("false"),
  ]),
  Numeric: Type.Union([Type.Number(), Type.String()]),
  AriaRole: Type.Union([
    Type.Literal("alert"),
    Type.Literal("alertdialog"),
    Type.Literal("application"),
    Type.Literal("article"),
    Type.Literal("banner"),
    Type.Literal("button"),
    Type.Literal("cell"),
    Type.Literal("checkbox"),
    Type.Literal("columnheader"),
    Type.Literal("combobox"),
    Type.Literal("complementary"),
    Type.Literal("contentinfo"),
    Type.Literal("definition"),
    Type.Literal("dialog"),
    Type.Literal("directory"),
    Type.Literal("document"),
    Type.Literal("feed"),
    Type.Literal("figure"),
    Type.Literal("form"),
    Type.Literal("grid"),
    Type.Literal("gridcell"),
    Type.Literal("group"),
    Type.Literal("heading"),
    Type.Literal("img"),
    Type.Literal("link"),
    Type.Literal("list"),
    Type.Literal("listbox"),
    Type.Literal("listitem"),
    Type.Literal("log"),
    Type.Literal("main"),
    Type.Literal("marquee"),
    Type.Literal("math"),
    Type.Literal("menu"),
    Type.Literal("menubar"),
    Type.Literal("menuitem"),
    Type.Literal("menuitemcheckbox"),
    Type.Literal("menuitemradio"),
    Type.Literal("navigation"),
    Type.Literal("none"),
    Type.Literal("note"),
    Type.Literal("option"),
    Type.Literal("presentation"),
    Type.Literal("progressbar"),
    Type.Literal("radio"),
    Type.Literal("radiogroup"),
    Type.Literal("region"),
    Type.Literal("row"),
    Type.Literal("rowgroup"),
    Type.Literal("rowheader"),
    Type.Literal("scrollbar"),
    Type.Literal("search"),
    Type.Literal("searchbox"),
    Type.Literal("separator"),
    Type.Literal("slider"),
    Type.Literal("spinbutton"),
    Type.Literal("status"),
    Type.Literal("switch"),
    Type.Literal("tab"),
    Type.Literal("table"),
    Type.Literal("tablist"),
    Type.Literal("tabpanel"),
    Type.Literal("term"),
    Type.Literal("textbox"),
    Type.Literal("timer"),
    Type.Literal("toolbar"),
    Type.Literal("tooltip"),
    Type.Literal("tree"),
    Type.Literal("treegrid"),
    Type.Literal("treeitem"),
  ]),
  ReferrerPolicy: Type.Union([
    Type.Literal(""),
    Type.Literal("no-referrer"),
    Type.Literal("no-referrer-when-downgrade"),
    Type.Literal("origin"),
    Type.Literal("origin-when-cross-origin"),
    Type.Literal("same-origin"),
    Type.Literal("strict-origin"),
    Type.Literal("strict-origin-when-cross-origin"),
    Type.Literal("unsafe-url"),
  ]),
  CrossOrigin: Type.Union([
    Type.Literal("anonymous"),
    Type.Literal("use-credentials"),
    Type.Literal(""),
  ]),
  Target: Type.Union([
    Type.Literal("_self"),
    Type.Literal("_blank"),
    Type.Literal("_parent"),
    Type.Literal("_top"),
  ]),
};

export const interfaces = {
  AriaAttributes: Type.Interface([], {
    "aria-activedescendant": Type.Optional(Type.String()),
    "aria-atomic": Type.Optional(Type.Ref("Booleanish")),
    "aria-autocomplete": Type.Optional(
      Type.Union([
        Type.Literal("none"),
        Type.Literal("inline"),
        Type.Literal("list"),
        Type.Literal("both"),
      ]),
    ),
    "aria-braillelabel": Type.Optional(Type.String()),
    "aria-brailleroledescription": Type.Optional(Type.String()),
    "aria-busy": Type.Optional(Type.Ref("Booleanish")),
    "aria-checked": Type.Optional(
      Type.Union([
        Type.Boolean(),
        Type.Literal("false"),
        Type.Literal("mixed"),
        Type.Literal("true"),
      ]),
    ),
    "aria-colcount": Type.Optional(Type.Number()),
    "aria-colindex": Type.Optional(Type.Number()),
    "aria-colindextext": Type.Optional(Type.String()),
    "aria-colspan": Type.Optional(Type.Number()),
    "aria-controls": Type.Optional(Type.String()),
    "aria-current": Type.Optional(
      Type.Union([
        Type.Boolean(),
        Type.Literal("false"),
        Type.Literal("true"),
        Type.Literal("page"),
        Type.Literal("step"),
        Type.Literal("location"),
        Type.Literal("date"),
        Type.Literal("time"),
      ]),
    ),
    "aria-describedby": Type.Optional(Type.String()),
    "aria-description": Type.Optional(Type.String()),
    "aria-details": Type.Optional(Type.String()),
    "aria-disabled": Type.Optional(Type.Ref("Booleanish")),
    "aria-errormessage": Type.Optional(Type.String()),
    "aria-expanded": Type.Optional(Type.Ref("Booleanish")),
    "aria-flowto": Type.Optional(Type.String()),
    "aria-haspopup": Type.Optional(
      Type.Union([
        Type.Boolean(),
        Type.Literal("false"),
        Type.Literal("true"),
        Type.Literal("menu"),
        Type.Literal("listbox"),
        Type.Literal("tree"),
        Type.Literal("grid"),
        Type.Literal("dialog"),
      ]),
    ),
    "aria-hidden": Type.Optional(Type.Ref("Booleanish")),
    "aria-invalid": Type.Optional(
      Type.Union([
        Type.Boolean(),
        Type.Literal("false"),
        Type.Literal("true"),
        Type.Literal("grammar"),
        Type.Literal("spelling"),
      ]),
    ),
    "aria-keyshortcuts": Type.Optional(Type.String()),
    "aria-label": Type.Optional(Type.String()),
    "aria-labelledby": Type.Optional(Type.String()),
    "aria-level": Type.Optional(Type.Number()),
    "aria-live": Type.Optional(
      Type.Union([
        Type.Literal("off"),
        Type.Literal("assertive"),
        Type.Literal("polite"),
      ]),
    ),
    "aria-modal": Type.Optional(Type.Ref("Booleanish")),
    "aria-multiline": Type.Optional(Type.Ref("Booleanish")),
    "aria-multiselectable": Type.Optional(Type.Ref("Booleanish")),
    "aria-orientation": Type.Optional(
      Type.Union([Type.Literal("horizontal"), Type.Literal("vertical")]),
    ),
    "aria-owns": Type.Optional(Type.String()),
    "aria-placeholder": Type.Optional(Type.String()),
    "aria-posinset": Type.Optional(Type.Number()),
    "aria-pressed": Type.Optional(
      Type.Union([
        Type.Boolean(),
        Type.Literal("false"),
        Type.Literal("mixed"),
        Type.Literal("true"),
      ]),
    ),
    "aria-readonly": Type.Optional(Type.Ref("Booleanish")),
    "aria-relevant": Type.Optional(
      Type.Union([
        Type.Literal("additions"),
        Type.Literal("additions removals"),
        Type.Literal("additions text"),
        Type.Literal("all"),
        Type.Literal("removals"),
        Type.Literal("removals additions"),
        Type.Literal("removals text"),
        Type.Literal("text"),
        Type.Literal("text additions"),
        Type.Literal("text removals"),
      ]),
    ),
    "aria-required": Type.Optional(Type.Ref("Booleanish")),
    "aria-roledescription": Type.Optional(Type.String()),
    "aria-rowcount": Type.Optional(Type.Number()),
    "aria-rowindex": Type.Optional(Type.Number()),
    "aria-rowindextext": Type.Optional(Type.String()),
    "aria-rowspan": Type.Optional(Type.Number()),
    "aria-selected": Type.Optional(Type.Ref("Booleanish")),
    "aria-setsize": Type.Optional(Type.Number()),
    "aria-sort": Type.Optional(
      Type.Union([
        Type.Literal("none"),
        Type.Literal("ascending"),
        Type.Literal("descending"),
        Type.Literal("other"),
      ]),
    ),
    "aria-valuemax": Type.Optional(Type.Number()),
    "aria-valuemin": Type.Optional(Type.Number()),
    "aria-valuenow": Type.Optional(Type.Number()),
    "aria-valuetext": Type.Optional(Type.String()),
  }),
  Events: Type.Interface([], {
    oncopy: Type.Optional(Type.Function([], Type.Void())),
    oncut: Type.Optional(Type.Function([], Type.Void())),
    onpaste: Type.Optional(Type.Function([], Type.Void())),
    oncompositionend: Type.Optional(Type.Function([], Type.Void())),
    oncompositionstart: Type.Optional(Type.Function([], Type.Void())),
    oncompositionupdate: Type.Optional(Type.Function([], Type.Void())),
    onblur: Type.Optional(Type.Function([], Type.Void())),
    onfocus: Type.Optional(Type.Function([], Type.Void())),
    onfocusin: Type.Optional(Type.Function([], Type.Void())),
    onfocusout: Type.Optional(Type.Function([], Type.Void())),
    onbeforeinput: Type.Optional(Type.Function([], Type.Void())),
    onchange: Type.Optional(Type.Function([], Type.Void())),
    oninput: Type.Optional(Type.Function([], Type.Void())),
    oninvalid: Type.Optional(Type.Function([], Type.Void())),
    onreset: Type.Optional(Type.Function([], Type.Void())),
    onselect: Type.Optional(Type.Function([], Type.Void())),
    onsubmit: Type.Optional(Type.Function([], Type.Void())),
    onerror: Type.Optional(Type.Function([], Type.Void())),
    onload: Type.Optional(Type.Function([], Type.Void())),
    onkeydown: Type.Optional(Type.Function([], Type.Void())),
    onkeypress: Type.Optional(Type.Function([], Type.Void())),
    onkeyup: Type.Optional(Type.Function([], Type.Void())),
    onabort: Type.Optional(Type.Function([], Type.Void())),
    oncanplay: Type.Optional(Type.Function([], Type.Void())),
    oncanplaythrough: Type.Optional(Type.Function([], Type.Void())),
    ondurationchange: Type.Optional(Type.Function([], Type.Void())),
    onemptied: Type.Optional(Type.Function([], Type.Void())),
    onended: Type.Optional(Type.Function([], Type.Void())),
    onloadeddata: Type.Optional(Type.Function([], Type.Void())),
    onloadedmetadata: Type.Optional(Type.Function([], Type.Void())),
    onloadstart: Type.Optional(Type.Function([], Type.Void())),
    onpause: Type.Optional(Type.Function([], Type.Void())),
    onplay: Type.Optional(Type.Function([], Type.Void())),
    onplaying: Type.Optional(Type.Function([], Type.Void())),
    onprogress: Type.Optional(Type.Function([], Type.Void())),
    onratechange: Type.Optional(Type.Function([], Type.Void())),
    onseeked: Type.Optional(Type.Function([], Type.Void())),
    onseeking: Type.Optional(Type.Function([], Type.Void())),
    onstalled: Type.Optional(Type.Function([], Type.Void())),
    onsuspend: Type.Optional(Type.Function([], Type.Void())),
    ontimeupdate: Type.Optional(Type.Function([], Type.Void())),
    onvolumechange: Type.Optional(Type.Function([], Type.Void())),
    onwaiting: Type.Optional(Type.Function([], Type.Void())),
    onauxclick: Type.Optional(Type.Function([], Type.Void())),
    onclick: Type.Optional(Type.Function([], Type.Void())),
    oncontextmenu: Type.Optional(Type.Function([], Type.Void())),
    ondblclick: Type.Optional(Type.Function([], Type.Void())),
    onmousedown: Type.Optional(Type.Function([], Type.Void())),
    onmouseenter: Type.Optional(Type.Function([], Type.Void())),
    onmouseleave: Type.Optional(Type.Function([], Type.Void())),
    onmousemove: Type.Optional(Type.Function([], Type.Void())),
    onmouseout: Type.Optional(Type.Function([], Type.Void())),
    onmouseover: Type.Optional(Type.Function([], Type.Void())),
    onmouseup: Type.Optional(Type.Function([], Type.Void())),
    ondrag: Type.Optional(Type.Function([], Type.Void())),
    ondragend: Type.Optional(Type.Function([], Type.Void())),
    ondragenter: Type.Optional(Type.Function([], Type.Void())),
    ondragleave: Type.Optional(Type.Function([], Type.Void())),
    ondragover: Type.Optional(Type.Function([], Type.Void())),
    ondragstart: Type.Optional(Type.Function([], Type.Void())),
    ondrop: Type.Optional(Type.Function([], Type.Void())),
    ontouchcancel: Type.Optional(Type.Function([], Type.Void())),
    ontouchend: Type.Optional(Type.Function([], Type.Void())),
    ontouchmove: Type.Optional(Type.Function([], Type.Void())),
    ontouchstart: Type.Optional(Type.Function([], Type.Void())),
    ongotpointercapture: Type.Optional(Type.Function([], Type.Void())),
    onlostpointercapture: Type.Optional(Type.Function([], Type.Void())),
    onpointercancel: Type.Optional(Type.Function([], Type.Void())),
    onpointerdown: Type.Optional(Type.Function([], Type.Void())),
    onpointerenter: Type.Optional(Type.Function([], Type.Void())),
    onpointerleave: Type.Optional(Type.Function([], Type.Void())),
    onpointermove: Type.Optional(Type.Function([], Type.Void())),
    onpointerout: Type.Optional(Type.Function([], Type.Void())),
    onpointerover: Type.Optional(Type.Function([], Type.Void())),
    onpointerup: Type.Optional(Type.Function([], Type.Void())),
    onscroll: Type.Optional(Type.Function([], Type.Void())),
    onscrollend: Type.Optional(Type.Function([], Type.Void())),
    onwheel: Type.Optional(Type.Function([], Type.Void())),
    onanimationend: Type.Optional(Type.Function([], Type.Void())),
    onanimationiteration: Type.Optional(Type.Function([], Type.Void())),
    onanimationstart: Type.Optional(Type.Function([], Type.Void())),
    ontransitioncancel: Type.Optional(Type.Function([], Type.Void())),
    ontransitionend: Type.Optional(Type.Function([], Type.Void())),
    ontransitionrun: Type.Optional(Type.Function([], Type.Void())),
    ontransitionstart: Type.Optional(Type.Function([], Type.Void())),
    onbeforetoggle: Type.Optional(Type.Function([], Type.Void())),
    ontoggle: Type.Optional(Type.Function([], Type.Void())),
  }),
  GlobalAttributes: Type.Interface(
    [Type.Ref("AriaAttributes"), Type.Ref("Events")],
    {
      accesskey: Type.Optional(Type.String()),
      autocapitalize: Type.Optional(
        Type.Union([
          Type.Literal("off"),
          Type.Literal("none"),
          Type.Literal("on"),
          Type.Literal("sentences"),
          Type.Literal("words"),
          Type.Literal("characters"),
        ]),
      ),
      autocorrect: Type.Optional(
        Type.Union([Type.Literal("on"), Type.Literal("off")]),
      ),
      autofocus: Type.Optional(Type.Boolean()),
      class: Type.Optional(Type.String()),
      contenteditable: Type.Optional(
        Type.Union([
          Type.Ref("Booleanish"),
          Type.Literal("inherit"),
          Type.Literal("plaintext-only"),
        ]),
      ),
      dir: Type.Optional(
        Type.Union([
          Type.Literal("ltr"),
          Type.Literal("rtl"),
          Type.Literal("auto"),
        ]),
      ),
      draggable: Type.Optional(Type.Ref("Booleanish")),
      enterkeyhint: Type.Optional(
        Type.Union([
          Type.Literal("enter"),
          Type.Literal("done"),
          Type.Literal("go"),
          Type.Literal("next"),
          Type.Literal("previous"),
          Type.Literal("search"),
          Type.Literal("send"),
        ]),
      ),
      exportparts: Type.Optional(Type.String()),
      hidden: Type.Optional(
        Type.Union([Type.Boolean(), Type.Literal("until-found")]),
      ),
      id: Type.Optional(Type.String()),
      inert: Type.Optional(Type.Boolean()),
      inputmode: Type.Optional(
        Type.Union([
          Type.Literal("none"),
          Type.Literal("text"),
          Type.Literal("tel"),
          Type.Literal("url"),
          Type.Literal("email"),
          Type.Literal("numeric"),
          Type.Literal("decimal"),
          Type.Literal("search"),
        ]),
      ),
      is: Type.Optional(Type.String()),
      itemid: Type.Optional(Type.String()),
      itemprop: Type.Optional(Type.String()),
      itemref: Type.Optional(Type.String()),
      itemscope: Type.Optional(Type.Boolean()),
      itemtype: Type.Optional(Type.String()),
      lang: Type.Optional(Type.String()),
      nonce: Type.Optional(Type.String()),
      part: Type.Optional(Type.String()),
      popover: Type.Optional(
        Type.Union([
          Type.Literal(""),
          Type.Literal("auto"),
          Type.Literal("manual"),
          Type.Literal("hint"),
        ]),
      ),
      role: Type.Optional(Type.Ref("AriaRole")),
      slot: Type.Optional(Type.String()),
      spellcheck: Type.Optional(Type.Ref("Booleanish")),
      style: Type.Optional(Type.String()),
      tabindex: Type.Optional(Type.Number()),
      title: Type.Optional(Type.String()),
      translate: Type.Optional(
        Type.Union([Type.Literal("yes"), Type.Literal("no")]),
      ),
    },
  ),
  VoidProps: Type.Interface([Type.Ref("GlobalAttributes")], {}),
  HtmlProps: Type.Interface([Type.Ref("GlobalAttributes")], {
    children: Type.Optional(child),
  }),
  /**
   * Children with no element of their own.
   *
   * What this target's fragment may hold is what its elements hold, which is
   * why it is declared here rather than shared: another target's fragment holds
   * that target's, and the brand they agree on is `cs-runtime`'s.
   */
  FragmentProps: Type.Interface([], { children: Type.Optional(child) }),
  AnchorProps: Type.Interface([Type.Ref("HtmlProps")], {
    download: Type.Optional(Type.Union([Type.String(), Type.Boolean()])),
    href: Type.Optional(Type.String()),
    hreflang: Type.Optional(Type.String()),
    media: Type.Optional(Type.String()),
    ping: Type.Optional(Type.String()),
    referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
    rel: Type.Optional(Type.String()),
    target: Type.Optional(Type.Ref("Target")),
    type: Type.Optional(Type.String()),
  }),
  AreaProps: Type.Interface([Type.Ref("VoidProps")], {
    alt: Type.Optional(Type.String()),
    coords: Type.Optional(Type.String()),
    download: Type.Optional(Type.Union([Type.String(), Type.Boolean()])),
    href: Type.Optional(Type.String()),
    referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
    rel: Type.Optional(Type.String()),
    shape: Type.Optional(
      Type.Union([
        Type.Literal("rect"),
        Type.Literal("circle"),
        Type.Literal("poly"),
        Type.Literal("default"),
      ]),
    ),
    target: Type.Optional(Type.Ref("Target")),
  }),
  BaseProps: Type.Interface([Type.Ref("VoidProps")], {
    href: Type.Optional(Type.String()),
    target: Type.Optional(Type.Ref("Target")),
  }),
  BlockquoteProps: Type.Interface([Type.Ref("HtmlProps")], {
    cite: Type.Optional(Type.String()),
  }),
  ButtonProps: Type.Interface([Type.Ref("HtmlProps")], {
    disabled: Type.Optional(Type.Boolean()),
    form: Type.Optional(Type.String()),
    formaction: Type.Optional(Type.String()),
    formenctype: Type.Optional(Type.String()),
    formmethod: Type.Optional(
      Type.Union([
        Type.Literal("get"),
        Type.Literal("post"),
        Type.Literal("dialog"),
      ]),
    ),
    formnovalidate: Type.Optional(Type.Boolean()),
    formtarget: Type.Optional(Type.Ref("Target")),
    name: Type.Optional(Type.String()),
    popovertarget: Type.Optional(Type.String()),
    popovertargetaction: Type.Optional(
      Type.Union([
        Type.Literal("toggle"),
        Type.Literal("show"),
        Type.Literal("hide"),
      ]),
    ),
    type: Type.Optional(
      Type.Union([
        Type.Literal("submit"),
        Type.Literal("reset"),
        Type.Literal("button"),
      ]),
    ),
    value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
  }),
  CanvasProps: Type.Interface([Type.Ref("HtmlProps")], {
    height: Type.Optional(Type.Ref("Numeric")),
    width: Type.Optional(Type.Ref("Numeric")),
  }),
  ColProps: Type.Interface([Type.Ref("VoidProps")], {
    span: Type.Optional(Type.Number()),
    width: Type.Optional(Type.Ref("Numeric")),
  }),
  ColgroupProps: Type.Interface([Type.Ref("HtmlProps")], {
    span: Type.Optional(Type.Number()),
  }),
  DataProps: Type.Interface([Type.Ref("HtmlProps")], {
    value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
  }),
  DelProps: Type.Interface([Type.Ref("HtmlProps")], {
    cite: Type.Optional(Type.String()),
    datetime: Type.Optional(Type.String()),
  }),
  DetailsProps: Type.Interface([Type.Ref("HtmlProps")], {
    name: Type.Optional(Type.String()),
    open: Type.Optional(Type.Boolean()),
  }),
  DialogProps: Type.Interface([Type.Ref("HtmlProps")], {
    closedby: Type.Optional(
      Type.Union([
        Type.Literal("any"),
        Type.Literal("closerequest"),
        Type.Literal("none"),
      ]),
    ),
    open: Type.Optional(Type.Boolean()),
  }),
  EmbedProps: Type.Interface([Type.Ref("VoidProps")], {
    height: Type.Optional(Type.Ref("Numeric")),
    src: Type.Optional(Type.String()),
    type: Type.Optional(Type.String()),
    width: Type.Optional(Type.Ref("Numeric")),
  }),
  FieldsetProps: Type.Interface([Type.Ref("HtmlProps")], {
    disabled: Type.Optional(Type.Boolean()),
    form: Type.Optional(Type.String()),
    name: Type.Optional(Type.String()),
  }),
  FormProps: Type.Interface([Type.Ref("HtmlProps")], {
    "accept-charset": Type.Optional(Type.String()),
    action: Type.Optional(Type.String()),
    autocomplete: Type.Optional(
      Type.Union([Type.Literal("on"), Type.Literal("off")]),
    ),
    enctype: Type.Optional(Type.String()),
    method: Type.Optional(
      Type.Union([
        Type.Literal("get"),
        Type.Literal("post"),
        Type.Literal("dialog"),
      ]),
    ),
    name: Type.Optional(Type.String()),
    novalidate: Type.Optional(Type.Boolean()),
    rel: Type.Optional(Type.String()),
    target: Type.Optional(Type.Ref("Target")),
  }),
  HtmlElementProps: Type.Interface([Type.Ref("HtmlProps")], {
    manifest: Type.Optional(Type.String()),
  }),
  IframeProps: Type.Interface([Type.Ref("HtmlProps")], {
    allow: Type.Optional(Type.String()),
    allowfullscreen: Type.Optional(Type.Boolean()),
    height: Type.Optional(Type.Ref("Numeric")),
    loading: Type.Optional(
      Type.Union([Type.Literal("eager"), Type.Literal("lazy")]),
    ),
    name: Type.Optional(Type.String()),
    referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
    sandbox: Type.Optional(Type.String()),
    src: Type.Optional(Type.String()),
    srcdoc: Type.Optional(Type.String()),
    width: Type.Optional(Type.Ref("Numeric")),
  }),
  ImgProps: Type.Interface([Type.Ref("VoidProps")], {
    alt: Type.Optional(Type.String()),
    crossorigin: Type.Optional(Type.Ref("CrossOrigin")),
    decoding: Type.Optional(
      Type.Union([
        Type.Literal("async"),
        Type.Literal("auto"),
        Type.Literal("sync"),
      ]),
    ),
    fetchpriority: Type.Optional(
      Type.Union([
        Type.Literal("high"),
        Type.Literal("low"),
        Type.Literal("auto"),
      ]),
    ),
    height: Type.Optional(Type.Ref("Numeric")),
    loading: Type.Optional(
      Type.Union([Type.Literal("eager"), Type.Literal("lazy")]),
    ),
    referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
    sizes: Type.Optional(Type.String()),
    src: Type.Optional(Type.String()),
    srcset: Type.Optional(Type.String()),
    usemap: Type.Optional(Type.String()),
    width: Type.Optional(Type.Ref("Numeric")),
  }),
  InputProps: Type.Interface([Type.Ref("VoidProps")], {
    accept: Type.Optional(Type.String()),
    alt: Type.Optional(Type.String()),
    autocomplete: Type.Optional(Type.String()),
    capture: Type.Optional(
      Type.Union([
        Type.Boolean(),
        Type.Literal("user"),
        Type.Literal("environment"),
      ]),
    ),
    checked: Type.Optional(Type.Boolean()),
    dirname: Type.Optional(Type.String()),
    disabled: Type.Optional(Type.Boolean()),
    form: Type.Optional(Type.String()),
    formaction: Type.Optional(Type.String()),
    formenctype: Type.Optional(Type.String()),
    formmethod: Type.Optional(
      Type.Union([
        Type.Literal("get"),
        Type.Literal("post"),
        Type.Literal("dialog"),
      ]),
    ),
    formnovalidate: Type.Optional(Type.Boolean()),
    formtarget: Type.Optional(Type.Ref("Target")),
    height: Type.Optional(Type.Ref("Numeric")),
    list: Type.Optional(Type.String()),
    max: Type.Optional(Type.Ref("Numeric")),
    maxlength: Type.Optional(Type.Number()),
    min: Type.Optional(Type.Ref("Numeric")),
    minlength: Type.Optional(Type.Number()),
    multiple: Type.Optional(Type.Boolean()),
    name: Type.Optional(Type.String()),
    pattern: Type.Optional(Type.String()),
    placeholder: Type.Optional(Type.String()),
    readonly: Type.Optional(Type.Boolean()),
    required: Type.Optional(Type.Boolean()),
    size: Type.Optional(Type.Number()),
    src: Type.Optional(Type.String()),
    step: Type.Optional(Type.Ref("Numeric")),
    type: Type.Optional(
      Type.Union([
        Type.Literal("button"),
        Type.Literal("checkbox"),
        Type.Literal("color"),
        Type.Literal("date"),
        Type.Literal("datetime-local"),
        Type.Literal("email"),
        Type.Literal("file"),
        Type.Literal("hidden"),
        Type.Literal("image"),
        Type.Literal("month"),
        Type.Literal("number"),
        Type.Literal("password"),
        Type.Literal("radio"),
        Type.Literal("range"),
        Type.Literal("reset"),
        Type.Literal("search"),
        Type.Literal("submit"),
        Type.Literal("tel"),
        Type.Literal("text"),
        Type.Literal("time"),
        Type.Literal("url"),
        Type.Literal("week"),
      ]),
    ),
    value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
    width: Type.Optional(Type.Ref("Numeric")),
  }),
  InsProps: Type.Interface([Type.Ref("HtmlProps")], {
    cite: Type.Optional(Type.String()),
    datetime: Type.Optional(Type.String()),
  }),
  LabelProps: Type.Interface([Type.Ref("HtmlProps")], {
    for: Type.Optional(Type.String()),
    form: Type.Optional(Type.String()),
  }),
  LiProps: Type.Interface([Type.Ref("HtmlProps")], {
    value: Type.Optional(Type.Number()),
  }),
  LinkProps: Type.Interface([Type.Ref("VoidProps")], {
    as: Type.Optional(Type.String()),
    crossorigin: Type.Optional(Type.Ref("CrossOrigin")),
    fetchpriority: Type.Optional(
      Type.Union([
        Type.Literal("high"),
        Type.Literal("low"),
        Type.Literal("auto"),
      ]),
    ),
    href: Type.Optional(Type.String()),
    hreflang: Type.Optional(Type.String()),
    imagesizes: Type.Optional(Type.String()),
    imagesrcset: Type.Optional(Type.String()),
    integrity: Type.Optional(Type.String()),
    media: Type.Optional(Type.String()),
    referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
    rel: Type.Optional(Type.String()),
    sizes: Type.Optional(Type.String()),
    type: Type.Optional(Type.String()),
  }),
  MapProps: Type.Interface([Type.Ref("HtmlProps")], {
    name: Type.Optional(Type.String()),
  }),
  MediaProps: Type.Interface([Type.Ref("HtmlProps")], {
    autoplay: Type.Optional(Type.Boolean()),
    controls: Type.Optional(Type.Boolean()),
    controlslist: Type.Optional(Type.String()),
    crossorigin: Type.Optional(Type.Ref("CrossOrigin")),
    loop: Type.Optional(Type.Boolean()),
    muted: Type.Optional(Type.Boolean()),
    preload: Type.Optional(
      Type.Union([
        Type.Literal("none"),
        Type.Literal("metadata"),
        Type.Literal("auto"),
        Type.Literal(""),
      ]),
    ),
    src: Type.Optional(Type.String()),
  }),
  MetaProps: Type.Interface([Type.Ref("VoidProps")], {
    charset: Type.Optional(Type.String()),
    content: Type.Optional(Type.String()),
    "http-equiv": Type.Optional(Type.String()),
    media: Type.Optional(Type.String()),
    name: Type.Optional(Type.String()),
  }),
  MeterProps: Type.Interface([Type.Ref("HtmlProps")], {
    form: Type.Optional(Type.String()),
    high: Type.Optional(Type.Number()),
    low: Type.Optional(Type.Number()),
    max: Type.Optional(Type.Ref("Numeric")),
    min: Type.Optional(Type.Ref("Numeric")),
    optimum: Type.Optional(Type.Number()),
    value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
  }),
  ObjectProps: Type.Interface([Type.Ref("HtmlProps")], {
    data: Type.Optional(Type.String()),
    form: Type.Optional(Type.String()),
    height: Type.Optional(Type.Ref("Numeric")),
    name: Type.Optional(Type.String()),
    type: Type.Optional(Type.String()),
    usemap: Type.Optional(Type.String()),
    width: Type.Optional(Type.Ref("Numeric")),
  }),
  OlProps: Type.Interface([Type.Ref("HtmlProps")], {
    reversed: Type.Optional(Type.Boolean()),
    start: Type.Optional(Type.Number()),
    type: Type.Optional(
      Type.Union([
        Type.Literal("1"),
        Type.Literal("a"),
        Type.Literal("A"),
        Type.Literal("i"),
        Type.Literal("I"),
      ]),
    ),
  }),
  OptgroupProps: Type.Interface([Type.Ref("HtmlProps")], {
    disabled: Type.Optional(Type.Boolean()),
    label: Type.Optional(Type.String()),
  }),
  OptionProps: Type.Interface([Type.Ref("HtmlProps")], {
    disabled: Type.Optional(Type.Boolean()),
    label: Type.Optional(Type.String()),
    selected: Type.Optional(Type.Boolean()),
    value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
  }),
  OutputProps: Type.Interface([Type.Ref("HtmlProps")], {
    for: Type.Optional(Type.String()),
    form: Type.Optional(Type.String()),
    name: Type.Optional(Type.String()),
  }),
  ProgressProps: Type.Interface([Type.Ref("HtmlProps")], {
    max: Type.Optional(Type.Ref("Numeric")),
    value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
  }),
  QuoteProps: Type.Interface([Type.Ref("HtmlProps")], {
    cite: Type.Optional(Type.String()),
  }),
  ScriptProps: Type.Interface([Type.Ref("HtmlProps")], {
    async: Type.Optional(Type.Boolean()),
    crossorigin: Type.Optional(Type.Ref("CrossOrigin")),
    defer: Type.Optional(Type.Boolean()),
    fetchpriority: Type.Optional(
      Type.Union([
        Type.Literal("high"),
        Type.Literal("low"),
        Type.Literal("auto"),
      ]),
    ),
    integrity: Type.Optional(Type.String()),
    nomodule: Type.Optional(Type.Boolean()),
    referrerpolicy: Type.Optional(Type.Ref("ReferrerPolicy")),
    src: Type.Optional(Type.String()),
    type: Type.Optional(Type.String()),
  }),
  SelectProps: Type.Interface([Type.Ref("HtmlProps")], {
    autocomplete: Type.Optional(Type.String()),
    disabled: Type.Optional(Type.Boolean()),
    form: Type.Optional(Type.String()),
    multiple: Type.Optional(Type.Boolean()),
    name: Type.Optional(Type.String()),
    required: Type.Optional(Type.Boolean()),
    size: Type.Optional(Type.Number()),
    value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
  }),
  SlotProps: Type.Interface([Type.Ref("HtmlProps")], {
    name: Type.Optional(Type.String()),
  }),
  SourceProps: Type.Interface([Type.Ref("VoidProps")], {
    height: Type.Optional(Type.Ref("Numeric")),
    media: Type.Optional(Type.String()),
    sizes: Type.Optional(Type.String()),
    src: Type.Optional(Type.String()),
    srcset: Type.Optional(Type.String()),
    type: Type.Optional(Type.String()),
    width: Type.Optional(Type.Ref("Numeric")),
  }),
  StyleProps: Type.Interface([Type.Ref("HtmlProps")], {
    media: Type.Optional(Type.String()),
    type: Type.Optional(Type.String()),
  }),
  TableProps: Type.Interface([Type.Ref("HtmlProps")], {
    summary: Type.Optional(Type.String()),
    width: Type.Optional(Type.Ref("Numeric")),
  }),
  TdProps: Type.Interface([Type.Ref("HtmlProps")], {
    colspan: Type.Optional(Type.Number()),
    headers: Type.Optional(Type.String()),
    rowspan: Type.Optional(Type.Number()),
  }),
  ThProps: Type.Interface([Type.Ref("HtmlProps")], {
    abbr: Type.Optional(Type.String()),
    colspan: Type.Optional(Type.Number()),
    headers: Type.Optional(Type.String()),
    rowspan: Type.Optional(Type.Number()),
    scope: Type.Optional(
      Type.Union([
        Type.Literal("row"),
        Type.Literal("col"),
        Type.Literal("rowgroup"),
        Type.Literal("colgroup"),
      ]),
    ),
  }),
  TextareaProps: Type.Interface([Type.Ref("HtmlProps")], {
    autocomplete: Type.Optional(Type.String()),
    cols: Type.Optional(Type.Number()),
    dirname: Type.Optional(Type.String()),
    disabled: Type.Optional(Type.Boolean()),
    form: Type.Optional(Type.String()),
    maxlength: Type.Optional(Type.Number()),
    minlength: Type.Optional(Type.Number()),
    name: Type.Optional(Type.String()),
    placeholder: Type.Optional(Type.String()),
    readonly: Type.Optional(Type.Boolean()),
    required: Type.Optional(Type.Boolean()),
    rows: Type.Optional(Type.Number()),
    value: Type.Optional(Type.Union([Type.String(), Type.Number()])),
    wrap: Type.Optional(
      Type.Union([
        Type.Literal("hard"),
        Type.Literal("soft"),
        Type.Literal("off"),
      ]),
    ),
  }),
  TimeProps: Type.Interface([Type.Ref("HtmlProps")], {
    datetime: Type.Optional(Type.String()),
  }),
  TrackProps: Type.Interface([Type.Ref("VoidProps")], {
    default: Type.Optional(Type.Boolean()),
    kind: Type.Optional(
      Type.Union([
        Type.Literal("subtitles"),
        Type.Literal("captions"),
        Type.Literal("descriptions"),
        Type.Literal("chapters"),
        Type.Literal("metadata"),
      ]),
    ),
    label: Type.Optional(Type.String()),
    src: Type.Optional(Type.String()),
    srclang: Type.Optional(Type.String()),
  }),
  VideoProps: Type.Interface([Type.Ref("MediaProps")], {
    disablepictureinpicture: Type.Optional(Type.Boolean()),
    disableremoteplayback: Type.Optional(Type.Boolean()),
    height: Type.Optional(Type.Ref("Numeric")),
    playsinline: Type.Optional(Type.Boolean()),
    poster: Type.Optional(Type.String()),
    width: Type.Optional(Type.Ref("Numeric")),
  }),
};

// Keyed by tag, which is also the id the wire carries and the string
// `createElement` receives. Most of them share one shape, which is why this
// is a map onto interfaces rather than 112 declarations.
export const elements = {
  a: Type.Element(Type.Ref("AnchorProps")),
  abbr: Type.Element(Type.Ref("HtmlProps")),
  address: Type.Element(Type.Ref("HtmlProps")),
  area: Type.Element(Type.Ref("AreaProps")),
  article: Type.Element(Type.Ref("HtmlProps")),
  aside: Type.Element(Type.Ref("HtmlProps")),
  audio: Type.Element(Type.Ref("MediaProps")),
  b: Type.Element(Type.Ref("HtmlProps")),
  base: Type.Element(Type.Ref("BaseProps")),
  bdi: Type.Element(Type.Ref("HtmlProps")),
  bdo: Type.Element(Type.Ref("HtmlProps")),
  blockquote: Type.Element(Type.Ref("BlockquoteProps")),
  body: Type.Element(Type.Ref("HtmlProps")),
  br: Type.Element(Type.Ref("VoidProps")),
  button: Type.Element(Type.Ref("ButtonProps")),
  canvas: Type.Element(Type.Ref("CanvasProps")),
  caption: Type.Element(Type.Ref("HtmlProps")),
  cite: Type.Element(Type.Ref("HtmlProps")),
  code: Type.Element(Type.Ref("HtmlProps")),
  col: Type.Element(Type.Ref("ColProps")),
  colgroup: Type.Element(Type.Ref("ColgroupProps")),
  data: Type.Element(Type.Ref("DataProps")),
  datalist: Type.Element(Type.Ref("HtmlProps")),
  dd: Type.Element(Type.Ref("HtmlProps")),
  del: Type.Element(Type.Ref("DelProps")),
  details: Type.Element(Type.Ref("DetailsProps")),
  dfn: Type.Element(Type.Ref("HtmlProps")),
  dialog: Type.Element(Type.Ref("DialogProps")),
  div: Type.Element(Type.Ref("HtmlProps")),
  dl: Type.Element(Type.Ref("HtmlProps")),
  dt: Type.Element(Type.Ref("HtmlProps")),
  em: Type.Element(Type.Ref("HtmlProps")),
  embed: Type.Element(Type.Ref("EmbedProps")),
  fieldset: Type.Element(Type.Ref("FieldsetProps")),
  figcaption: Type.Element(Type.Ref("HtmlProps")),
  figure: Type.Element(Type.Ref("HtmlProps")),
  footer: Type.Element(Type.Ref("HtmlProps")),
  form: Type.Element(Type.Ref("FormProps")),
  h1: Type.Element(Type.Ref("HtmlProps")),
  h2: Type.Element(Type.Ref("HtmlProps")),
  h3: Type.Element(Type.Ref("HtmlProps")),
  h4: Type.Element(Type.Ref("HtmlProps")),
  h5: Type.Element(Type.Ref("HtmlProps")),
  h6: Type.Element(Type.Ref("HtmlProps")),
  head: Type.Element(Type.Ref("HtmlProps")),
  header: Type.Element(Type.Ref("HtmlProps")),
  hgroup: Type.Element(Type.Ref("HtmlProps")),
  hr: Type.Element(Type.Ref("VoidProps")),
  html: Type.Element(Type.Ref("HtmlElementProps")),
  i: Type.Element(Type.Ref("HtmlProps")),
  iframe: Type.Element(Type.Ref("IframeProps")),
  img: Type.Element(Type.Ref("ImgProps")),
  input: Type.Element(Type.Ref("InputProps")),
  ins: Type.Element(Type.Ref("InsProps")),
  kbd: Type.Element(Type.Ref("HtmlProps")),
  label: Type.Element(Type.Ref("LabelProps")),
  legend: Type.Element(Type.Ref("HtmlProps")),
  li: Type.Element(Type.Ref("LiProps")),
  link: Type.Element(Type.Ref("LinkProps")),
  main: Type.Element(Type.Ref("HtmlProps")),
  map: Type.Element(Type.Ref("MapProps")),
  mark: Type.Element(Type.Ref("HtmlProps")),
  menu: Type.Element(Type.Ref("HtmlProps")),
  meta: Type.Element(Type.Ref("MetaProps")),
  meter: Type.Element(Type.Ref("MeterProps")),
  nav: Type.Element(Type.Ref("HtmlProps")),
  noscript: Type.Element(Type.Ref("HtmlProps")),
  object: Type.Element(Type.Ref("ObjectProps")),
  ol: Type.Element(Type.Ref("OlProps")),
  optgroup: Type.Element(Type.Ref("OptgroupProps")),
  option: Type.Element(Type.Ref("OptionProps")),
  output: Type.Element(Type.Ref("OutputProps")),
  p: Type.Element(Type.Ref("HtmlProps")),
  picture: Type.Element(Type.Ref("HtmlProps")),
  pre: Type.Element(Type.Ref("HtmlProps")),
  progress: Type.Element(Type.Ref("ProgressProps")),
  q: Type.Element(Type.Ref("QuoteProps")),
  rp: Type.Element(Type.Ref("HtmlProps")),
  rt: Type.Element(Type.Ref("HtmlProps")),
  ruby: Type.Element(Type.Ref("HtmlProps")),
  s: Type.Element(Type.Ref("HtmlProps")),
  samp: Type.Element(Type.Ref("HtmlProps")),
  script: Type.Element(Type.Ref("ScriptProps")),
  search: Type.Element(Type.Ref("HtmlProps")),
  section: Type.Element(Type.Ref("HtmlProps")),
  select: Type.Element(Type.Ref("SelectProps")),
  slot: Type.Element(Type.Ref("SlotProps")),
  small: Type.Element(Type.Ref("HtmlProps")),
  source: Type.Element(Type.Ref("SourceProps")),
  span: Type.Element(Type.Ref("HtmlProps")),
  strong: Type.Element(Type.Ref("HtmlProps")),
  style: Type.Element(Type.Ref("StyleProps")),
  sub: Type.Element(Type.Ref("HtmlProps")),
  summary: Type.Element(Type.Ref("HtmlProps")),
  sup: Type.Element(Type.Ref("HtmlProps")),
  table: Type.Element(Type.Ref("TableProps")),
  tbody: Type.Element(Type.Ref("HtmlProps")),
  td: Type.Element(Type.Ref("TdProps")),
  template: Type.Element(Type.Ref("HtmlProps")),
  textarea: Type.Element(Type.Ref("TextareaProps")),
  tfoot: Type.Element(Type.Ref("HtmlProps")),
  th: Type.Element(Type.Ref("ThProps")),
  thead: Type.Element(Type.Ref("HtmlProps")),
  time: Type.Element(Type.Ref("TimeProps")),
  title: Type.Element(Type.Ref("HtmlProps")),
  tr: Type.Element(Type.Ref("HtmlProps")),
  track: Type.Element(Type.Ref("TrackProps")),
  u: Type.Element(Type.Ref("HtmlProps")),
  ul: Type.Element(Type.Ref("HtmlProps")),
  var: Type.Element(Type.Ref("HtmlProps")),
  video: Type.Element(Type.Ref("VideoProps")),
  wbr: Type.Element(Type.Ref("VoidProps")),
};
