// Generated by `pnpm generate`. Do not edit.

import type {
  Builtins as WebBuiltins,
  Elements as WebElements,
} from "@backtickjs/web-sdk";

export type {
  AnchorProps,
  AnimationEvent,
  AreaProps,
  AriaAttributes,
  AriaRole,
  ArrayLike,
  BacktickElement,
  BacktickNode,
  BaseProps,
  BlockquoteProps,
  Booleanish,
  BundleAddition,
  BundleAdditionAssignment,
  BundleArrayElement,
  BundleArrayLiteral,
  BundleArrowFunction,
  BundleAssignment,
  BundleBlock,
  BundleBody,
  BundleBreak,
  BundleBuiltin,
  BundleCall,
  BundleCatchClause,
  BundleComponentCall,
  BundleConditional,
  BundleConstDeclaration,
  BundleContinue,
  BundleDivision,
  BundleDivisionAssignment,
  BundleElement,
  BundleElementAccess,
  BundleExpression,
  BundleFor,
  BundleFunctionLabel,
  BundleFunctionReference,
  BundleGreaterThan,
  BundleGreaterThanOrEqual,
  BundleIdentifier,
  BundleIf,
  BundleLessThan,
  BundleLessThanOrEqual,
  BundleLetDeclaration,
  BundleLogicalAnd,
  BundleLogicalNot,
  BundleLogicalOr,
  BundleMultiplication,
  BundleMultiplicationAssignment,
  BundleNegation,
  BundleNullishCoalescing,
  BundleOptionalCall,
  BundleOptionalPropertyAccess,
  BundleParameter,
  BundlePostfixDecrement,
  BundlePostfixIncrement,
  BundlePrefixDecrement,
  BundlePrefixIncrement,
  BundlePropertyAccess,
  BundleRemainder,
  BundleRemainderAssignment,
  BundleReturn,
  BundleSpreadElement,
  BundleStatement,
  BundleStrictEquality,
  BundleStrictInequality,
  BundleSubtraction,
  BundleSubtractionAssignment,
  BundleThrow,
  BundleTree,
  BundleTry,
  BundleTypeOf,
  BundleUndefined,
  BundleWhile,
  ButtonProps,
  CanvasProps,
  ClientFunction,
  ClientHandle,
  ClientUnknown,
  ClientValue,
  ClipboardEvent,
  ColProps,
  ColgroupProps,
  CompositionEvent,
  Console,
  CrossOrigin,
  DataProps,
  DelProps,
  DetailsProps,
  DialogProps,
  DragEvent,
  Element,
  EmbedProps,
  ErrorEvent,
  Event,
  EventTarget,
  Events,
  FieldsetProps,
  FocusEvent,
  ForProps,
  FormProps,
  FragmentProps,
  GlobalAttributes,
  HTMLAnchorElement,
  HTMLAreaElement,
  HTMLAudioElement,
  HTMLBRElement,
  HTMLBaseElement,
  HTMLBodyElement,
  HTMLButtonElement,
  HTMLCanvasElement,
  HTMLDListElement,
  HTMLDataElement,
  HTMLDataListElement,
  HTMLDetailsElement,
  HTMLDialogElement,
  HTMLDivElement,
  HTMLElement,
  HTMLEmbedElement,
  HTMLFieldSetElement,
  HTMLFormElement,
  HTMLHRElement,
  HTMLHeadElement,
  HTMLHeadingElement,
  HTMLHtmlElement,
  HTMLHyperlinkElementUtils,
  HTMLIFrameElement,
  HTMLImageElement,
  HTMLInputElement,
  HTMLLIElement,
  HTMLLabelElement,
  HTMLLegendElement,
  HTMLLinkElement,
  HTMLMapElement,
  HTMLMediaElement,
  HTMLMenuElement,
  HTMLMetaElement,
  HTMLMeterElement,
  HTMLModElement,
  HTMLOListElement,
  HTMLObjectElement,
  HTMLOptGroupElement,
  HTMLOptionElement,
  HTMLOrSVGElement,
  HTMLOutputElement,
  HTMLParagraphElement,
  HTMLPictureElement,
  HTMLPreElement,
  HTMLProgressElement,
  HTMLQuoteElement,
  HTMLScriptElement,
  HTMLSelectElement,
  HTMLSlotElement,
  HTMLSourceElement,
  HTMLSpanElement,
  HTMLStyleElement,
  HTMLTableCaptionElement,
  HTMLTableCellElement,
  HTMLTableColElement,
  HTMLTableElement,
  HTMLTableRowElement,
  HTMLTableSectionElement,
  HTMLTemplateElement,
  HTMLTextAreaElement,
  HTMLTimeElement,
  HTMLTitleElement,
  HTMLTrackElement,
  HTMLUListElement,
  HTMLVideoElement,
  HtmlElementProps,
  HtmlProps,
  IframeProps,
  ImgProps,
  InputEvent,
  InputProps,
  InsProps,
  KeyboardEvent,
  LabelProps,
  LiProps,
  LinkProps,
  Location,
  MapProps,
  MediaProps,
  MessageEvent,
  MetaProps,
  MeterProps,
  MouseEvent,
  Node,
  Numeric,
  ObjectProps,
  OlProps,
  OptgroupProps,
  OptionProps,
  OutputProps,
  Performance,
  PointerEvent,
  ProgressEvent,
  ProgressProps,
  QuoteProps,
  RefProps,
  ReferrerPolicy,
  RequestInit,
  Response,
  SVGElement,
  SelectProps,
  Signal,
  SignalOptions,
  SlotProps,
  SourceProps,
  State,
  StyleProps,
  SubmitEvent,
  SvgProps,
  TableProps,
  Target,
  TdProps,
  TextareaProps,
  ThProps,
  TimeProps,
  ToggleEvent,
  TouchEvent,
  TrackProps,
  TransitionEvent,
  UIEvent,
  VideoProps,
  VoidProps,
  WheelEvent,
  Window,
} from "@backtickjs/web-sdk";

/**
 * Something the compiler had to say, and where in the source.
 */
export interface Diagnostic {
  readonly message: string;
  readonly start: number | null;
  readonly length: number | null;
}

/** The elements this schema declares, and what each accepts. */
export interface SiteElements {}

/** Every element in scope, this schema's own and its bases'. */
export interface Elements extends WebElements, SiteElements {}

/** What this schema declares, which is what its own client answers for. */
export interface SiteBuiltins {
  /**
   * Backtick source, compiled to javascript. One callback is called, once —
   * callbacks because waiting is not a thing this language does.
   *
   * @param fileName What to call it. It reaches a reader in a complaint, and
   * it is what decides whether the text is read as `.ts` or `.tsx`.
   * @param sourceText What somebody wrote.
   * @param onJavascript Called with the javascript, in `require`/`exports`
   * form. Nothing has run it yet.
   * @param onDiagnostics Called instead. Not an error: a half-written line
   * answers this way, and the call did what it was asked.
   */
  compile(
    fileName: string,
    sourceText: string,
    onJavascript: (javascript: string) => void,
    onDiagnostics: (diagnostics: Diagnostic[]) => void,
  ): void;
  /**
   * Javascript, run for the drawing it makes, and that drawing folded into a
   * bundle.
   *
   * Running it is `eval`, which a page saying `default-src 'self'` cannot do —
   * so where this happens is somewhere the page is not, and that is a client's
   * to arrange.
   *
   * Apart from `compile` because the two fail differently: a half-written line
   * is the compiler speaking, and code that throws while it runs is not.
   *
   * @param javascript What `compile` answered with.
   * @param onBundle Called with the bundle. Measuring it is the caller's.
   * @param onDiagnostics Called instead, when what was written threw while it
   * ran or drew nothing. Spans are null here — it failed afterwards.
   */
  bundle(
    javascript: string,
    onBundle: (bundle: string) => void,
    onDiagnostics: (diagnostics: Diagnostic[]) => void,
  ): void;
}

/** What a client must answer with, for every name in scope. */
export interface Builtins extends WebBuiltins, SiteBuiltins {}
