// Generated by `pnpm generate`. Do not edit.

import { createBuiltin, type Client } from "@backtickjs/platform-sdk";

/**
 * Runs something once, after the drawing the calling script belongs to is in
 * place — the moment to start a timer or listen on the window.
 *
 * Called from a script that draws, as a statement before its `return`. Called
 * from a handler, the drawing is already in place and it runs straight away.
 *
 * @param fn What to run once the drawing is in place.
 */
export const onMount: Client<(fn: () => void) => void> =
  createBuiltin("onMount");
