// Generated by `pnpm generate`. Do not edit.

/** Every name a script reaches without declaring it. */
export const BUILTIN_NAMES = ["Array", "Math", "state"] as const;

/** The ones a script may reach as a value, and read members of. */
export const BUILTIN_GLOBALS = ["Array", "Math"] as const;
