// Generated by `pnpm generate`. Do not edit.

import type {
  Builtins as UiPlatformBuiltins,
  Children,
  ClientHandle,
  ClientValue,
  Elements as UiPlatformElements,
  Prop,
} from "@backtickjs/ui-platform-sdk";

export type {
  ArrayLike,
  BacktickElement,
  BacktickNode,
  Bundle,
  BundleAddition,
  BundleArrayElement,
  BundleArrayLiteral,
  BundleArrowFunction,
  BundleAssignment,
  BundleBlock,
  BundleBody,
  BundleBreak,
  BundleBuiltin,
  BundleCall,
  BundleCatchClause,
  BundleComponentCall,
  BundleConditional,
  BundleConstDeclaration,
  BundleContinue,
  BundleDivision,
  BundleElement,
  BundleElementAccess,
  BundleExpression,
  BundleFor,
  BundleFunctionLabel,
  BundleFunctionReference,
  BundleGreaterThan,
  BundleGreaterThanOrEqual,
  BundleIdentifier,
  BundleIf,
  BundleLessThan,
  BundleLessThanOrEqual,
  BundleLetDeclaration,
  BundleLogicalAnd,
  BundleLogicalNot,
  BundleLogicalOr,
  BundleMultiplication,
  BundleNegation,
  BundleNullishCoalescing,
  BundleObjectEntry,
  BundleObjectLiteral,
  BundleOptionalCall,
  BundleOptionalPropertyAccess,
  BundleParameter,
  BundlePropertyAccess,
  BundlePropertyAssignment,
  BundleRemainder,
  BundleReturn,
  BundleSpreadElement,
  BundleStatement,
  BundleStrictEquality,
  BundleStrictInequality,
  BundleSubtraction,
  BundleThrow,
  BundleTry,
  BundleUndefined,
  BundleWhile,
  ClientFunction,
  ClientHandle,
  ClientUnknown,
  ClientValue,
  ForProps,
  FragmentProps,
  Http,
  HttpConfig,
  HttpResponse,
  Signal,
  State,
  Vm,
} from "@backtickjs/ui-platform-sdk";

declare const EventTargetBrand: unique symbol;
/**
 * What an event happened to, and what a listener is attached to.
 */
export interface EventTarget extends ClientHandle {
  readonly [EventTargetBrand]: never;
}

declare const WindowBrand: unique symbol;
/**
 * A window — this one, or the one inside a frame. What a script may reach that
 * is not an element's own is here, because that is where the DOM keeps it.
 */
export interface Window extends ClientHandle {
  readonly [WindowBrand]: never;
  /**
   * The clock, for measuring how long something took.
   */
  readonly performance: Performance;
  /**
   * Somewhere to say something while writing a script.
   */
  readonly console: Console;
  /**
   * Where the document came from, and how to go somewhere else.
   */
  readonly location: Location;
  /**
   * Runs something once, later, and answers with a number to cancel it by.
   *
   * Nothing cancels it for you. A timer outlives the drawing that made one, so
   * a script that may go away first keeps its id and clears it.
   *
   * @param handler What to run once the delay has passed.
   * @param timeout How long to wait, in milliseconds. Left out is the same as
   * zero: the soonest turn that is not this one.
   */
  setTimeout(handler: () => void, timeout?: number): number;
  /**
   * Cancels a timer that has not run yet. An id that has already run, or was
   * never one, is not an error.
   *
   * @param id What `setTimeout` answered with.
   */
  clearTimeout(id: number): void;
  /**
   * Runs something over and over, and answers with a number to cancel it by.
   *
   * This is what makes a loop, and not `setTimeout` calling itself: a variable
   * cannot be named in its own initializer, so a handler that reschedules
   * itself is not something a script can write.
   *
   * @param handler What to run on every tick.
   * @param timeout How long between ticks, in milliseconds.
   */
  setInterval(handler: () => void, timeout?: number): number;
  /**
   * Stops a repeating timer. Ids are one series whichever call made them, so
   * either `clear` cancels either kind.
   *
   * @param id What `setInterval` answered with.
   */
  clearInterval(id: number): void;
  /**
   * Listens for an event nothing drawn here is the target of — a key pressed
   * anywhere, a message arriving. What an element's own events are is a prop
   * on that element, and this is the rest.
   *
   * @param type Which event to listen for, named as the DOM names it.
   */
  addEventListener<E extends Event<EventTarget>>(
    type: string,
    listener: (event: E) => void,
  ): void;
  /**
   * Stops listening. The listener has to be the same one that was handed to
   * `addEventListener` — the DOM matches by identity, so a second closure that
   * does the same thing removes nothing.
   *
   * @param type Which event to listen for, named as the DOM names it.
   */
  removeEventListener<E extends Event<EventTarget>>(
    type: string,
    listener: (event: E) => void,
  ): void;
  /**
   * @param message What to send. It is copied, not shared.
   * @param targetOrigin Which origin may receive it, or `*` for any. A frame
   * sandboxed without `allow-same-origin` has an origin no sender can name, so
   * `*` is the only thing there is to say.
   */
  postMessage<T extends ClientValue>(message: T, targetOrigin: string): void;
}

declare const EventBrand: unique symbol;
/**
 * Anything that happens to an element, and what every other event here is one
 * of.
 */
export interface Event<T extends ClientValue> extends ClientHandle {
  readonly [EventBrand]: never;
  readonly bubbles: boolean;
  readonly cancelable: boolean;
  readonly composed: boolean;
  readonly currentTarget: T;
  readonly defaultPrevented: boolean;
  readonly eventPhase: number;
  readonly isTrusted: boolean;
  readonly srcElement: EventTarget | null;
  readonly target: EventTarget | null;
  readonly type: string;
  readonly timeStamp: number;
  preventDefault(): void;
  stopPropagation(): void;
  stopImmediatePropagation(): void;
}

declare const UIEventBrand: unique symbol;
/**
 * An event that came from the interface rather than from the page's own code.
 */
export interface UIEvent<T extends ClientValue> extends Event<T> {
  readonly [UIEventBrand]: T;
  readonly detail: number;
  readonly which: number;
}

declare const MouseEventBrand: unique symbol;
/**
 * A pointing device did something, and where it was when it did.
 */
export interface MouseEvent<T extends ClientValue> extends UIEvent<T> {
  readonly [MouseEventBrand]: T;
  readonly altKey: boolean;
  readonly button: number;
  readonly buttons: number;
  readonly clientX: number;
  readonly clientY: number;
  readonly ctrlKey: boolean;
  readonly layerX: number;
  readonly layerY: number;
  readonly metaKey: boolean;
  readonly movementX: number;
  readonly movementY: number;
  readonly offsetX: number;
  readonly offsetY: number;
  readonly pageX: number;
  readonly pageY: number;
  readonly relatedTarget: EventTarget | null;
  readonly screenX: number;
  readonly screenY: number;
  readonly shiftKey: boolean;
  readonly x: number;
  readonly y: number;
}

declare const PointerEventBrand: unique symbol;
/**
 * A mouse, a pen or a finger — what the DOM hands a click, whichever it was.
 */
export interface PointerEvent<T extends ClientValue> extends MouseEvent<T> {
  readonly [PointerEventBrand]: T;
  readonly altitudeAngle: number;
  readonly azimuthAngle: number;
  readonly height: number;
  readonly isPrimary: boolean;
  readonly persistentDeviceId: number;
  readonly pointerId: number;
  readonly pointerType: string;
  readonly pressure: number;
  readonly tangentialPressure: number;
  readonly tiltX: number;
  readonly tiltY: number;
  readonly twist: number;
  readonly width: number;
}

declare const DragEventBrand: unique symbol;
/**
 * Something is being dragged.
 */
export interface DragEvent<T extends ClientValue> extends MouseEvent<T> {
  readonly [DragEventBrand]: T;
}

declare const WheelEventBrand: unique symbol;
/**
 * A wheel turned, and by how much in which units.
 */
export interface WheelEvent<T extends ClientValue> extends MouseEvent<T> {
  readonly [WheelEventBrand]: T;
  readonly deltaMode: number;
  readonly deltaX: number;
  readonly deltaY: number;
  readonly deltaZ: number;
}

declare const KeyboardEventBrand: unique symbol;
/**
 * A key went down or came up, and which key it was.
 */
export interface KeyboardEvent<T extends ClientValue> extends UIEvent<T> {
  readonly [KeyboardEventBrand]: T;
  readonly altKey: boolean;
  readonly charCode: number;
  readonly code: string;
  readonly ctrlKey: boolean;
  readonly isComposing: boolean;
  readonly key: string;
  readonly keyCode: number;
  readonly location: number;
  readonly metaKey: boolean;
  readonly repeat: boolean;
  readonly shiftKey: boolean;
}

declare const InputEventBrand: unique symbol;
/**
 * The value of an editable element changed, and how.
 */
export interface InputEvent<T extends ClientValue> extends UIEvent<T> {
  readonly [InputEventBrand]: T;
  readonly data: string | null;
  readonly inputType: string;
  readonly isComposing: boolean;
}

declare const CompositionEventBrand: unique symbol;
/**
 * Text is being composed — an input method is part-way through a character.
 */
export interface CompositionEvent<T extends ClientValue> extends UIEvent<T> {
  readonly [CompositionEventBrand]: T;
  readonly data: string;
}

declare const FocusEventBrand: unique symbol;
/**
 * Focus arrived or left.
 */
export interface FocusEvent<T extends ClientValue> extends UIEvent<T> {
  readonly [FocusEventBrand]: T;
  readonly relatedTarget: EventTarget | null;
}

declare const TouchEventBrand: unique symbol;
/**
 * Fingers on a screen.
 */
export interface TouchEvent<T extends ClientValue> extends UIEvent<T> {
  readonly [TouchEventBrand]: T;
  readonly altKey: boolean;
  readonly ctrlKey: boolean;
  readonly metaKey: boolean;
  readonly shiftKey: boolean;
}

declare const ClipboardEventBrand: unique symbol;
/**
 * A copy, cut or paste.
 */
export interface ClipboardEvent<T extends ClientValue> extends Event<T> {
  readonly [ClipboardEventBrand]: T;
}

declare const SubmitEventBrand: unique symbol;
/**
 * A form was submitted.
 */
export interface SubmitEvent<T extends ClientValue> extends Event<T> {
  readonly [SubmitEventBrand]: T;
}

declare const ToggleEventBrand: unique symbol;
/**
 * Something that opens and closes did.
 */
export interface ToggleEvent<T extends ClientValue> extends Event<T> {
  readonly [ToggleEventBrand]: T;
  readonly newState: string;
  readonly oldState: string;
}

declare const AnimationEventBrand: unique symbol;
/**
 * A CSS animation reached one of its edges.
 */
export interface AnimationEvent<T extends ClientValue> extends Event<T> {
  readonly [AnimationEventBrand]: T;
  readonly animationName: string;
  readonly elapsedTime: number;
  readonly pseudoElement: string;
}

declare const TransitionEventBrand: unique symbol;
/**
 * A CSS transition reached one of its edges.
 */
export interface TransitionEvent<T extends ClientValue> extends Event<T> {
  readonly [TransitionEventBrand]: T;
  readonly elapsedTime: number;
  readonly propertyName: string;
  readonly pseudoElement: string;
}

declare const ProgressEventBrand: unique symbol;
/**
 * Something loading said how far it had got.
 */
export interface ProgressEvent<T extends ClientValue> extends Event<T> {
  readonly [ProgressEventBrand]: T;
  readonly lengthComputable: boolean;
  readonly loaded: number;
  readonly total: number;
}

declare const MessageEventBrand: unique symbol;
/**
 * Something another window posted. The parameter is what was posted, rather
 * than what the event happened to: a message is always the window's, so there
 * is nothing else to say about its target.
 */
export interface MessageEvent<
  T extends ClientValue,
> extends Event<EventTarget> {
  readonly [MessageEventBrand]: never;
  readonly data: T;
  readonly lastEventId: string;
  readonly origin: string;
  readonly source: Window | null;
}

declare const ErrorEventBrand: unique symbol;
/**
 * Something failed, and said where.
 */
export interface ErrorEvent<T extends ClientValue> extends Event<T> {
  readonly [ErrorEventBrand]: T;
  readonly colno: number;
  readonly filename: string;
  readonly lineno: number;
  readonly message: string;
}

declare const NodeBrand: unique symbol;
export interface Node extends EventTarget {
  readonly [NodeBrand]: never;
  readonly baseURI: string;
  readonly isConnected: boolean;
  readonly nodeName: string;
  readonly nodeType: number;
  readonly nodeValue: string | null;
  readonly textContent: string | null;
}

declare const ElementBrand: unique symbol;
export interface Element extends Node {
  readonly [ElementBrand]: never;
  readonly className: string;
  /**
   * Scrolls to a position, rather than by an amount.
   *
   * @param x How far along, counted in pixels.
   * @param y How far down.
   */
  scrollTo(x: number, y: number): void;
  readonly clientHeight: number;
  readonly clientLeft: number;
  readonly clientTop: number;
  readonly clientWidth: number;
  readonly currentCSSZoom: number;
  readonly id: string;
  readonly innerHTML: string;
  readonly localName: string;
  readonly namespaceURI: string | null;
  readonly outerHTML: string;
  readonly prefix: string | null;
  readonly scrollHeight: number;
  readonly scrollLeft: number;
  readonly scrollTop: number;
  readonly scrollWidth: number;
  readonly slot: string;
  readonly tagName: string;
}

declare const PerformanceBrand: unique symbol;
/**
 * A clock that only measures. Milliseconds since the page began, as a fraction
 * — what it is for is the difference between two of them, not the time of day.
 */
export interface Performance extends ClientHandle {
  readonly [PerformanceBrand]: never;
  now(): number;
}

declare const ConsoleBrand: unique symbol;
/**
 * Somewhere to say something while writing a script. What a host does with it
 * is the host's own business — a client with no console answers for these and
 * drops them.
 */
export interface Console extends ClientHandle {
  readonly [ConsoleBrand]: never;
  log(...values: ClientValue[]): void;
  warn(...values: ClientValue[]): void;
  error(...values: ClientValue[]): void;
}

declare const LocationBrand: unique symbol;
/**
 * Where the document came from, and how to go somewhere else.
 *
 * Every part is read-only, and going somewhere is a call. The DOM lets a write
 * to `href` — or to `pathname`, or to `hash` — navigate, which is nine names
 * for one act and an assignment that does not assign; a client with no DOM
 * would have to answer for each of them separately. `assign` says it once.
 */
export interface Location extends ClientHandle {
  readonly [LocationBrand]: never;
  readonly href: string;
  readonly origin: string;
  readonly protocol: string;
  readonly host: string;
  readonly hostname: string;
  readonly port: string;
  readonly pathname: string;
  readonly search: string;
  readonly hash: string;
  /**
   * Goes somewhere, leaving this behind in the history. Back comes here.
   *
   * @param url Where to go. Resolved against this one, so `/feed` and
   * `?page=2` are both things to say.
   */
  assign(url: string): void;
  /**
   * Goes somewhere in this one's place. Back skips it, which is what a
   * redirect wants.
   */
  replace(url: string): void;
  /**
   * Asks for this one again.
   */
  reload(): void;
}

declare const SVGElementBrand: unique symbol;
export interface SVGElement extends Element {
  readonly [SVGElementBrand]: never;
}

declare const HTMLElementBrand: unique symbol;
export interface HTMLElement extends Element, HTMLOrSVGElement {
  readonly [HTMLElementBrand]: never;
  readonly accessKey: string;
  readonly accessKeyLabel: string;
  readonly autocapitalize: string;
  readonly autocorrect: boolean;
  readonly dir: string;
  readonly draggable: boolean;
  readonly inert: boolean;
  readonly innerText: string;
  readonly lang: string;
  readonly offsetHeight: number;
  readonly offsetLeft: number;
  readonly offsetTop: number;
  readonly offsetWidth: number;
  readonly outerText: string;
  readonly popover: string | null;
  readonly spellcheck: boolean;
  readonly title: string;
  readonly translate: boolean;
  readonly writingSuggestions: string;
}

declare const HTMLAnchorElementBrand: unique symbol;
export interface HTMLAnchorElement
  extends HTMLElement, HTMLHyperlinkElementUtils {
  readonly [HTMLAnchorElementBrand]: never;
  readonly charset: string;
  readonly coords: string;
  readonly download: string;
  readonly hreflang: string;
  readonly name: string;
  readonly ping: string;
  readonly referrerPolicy: string;
  readonly rel: string;
  readonly rev: string;
  readonly shape: string;
  readonly target: string;
  readonly text: string;
  readonly type: string;
}

declare const HTMLAreaElementBrand: unique symbol;
export interface HTMLAreaElement
  extends HTMLElement, HTMLHyperlinkElementUtils {
  readonly [HTMLAreaElementBrand]: never;
  readonly alt: string;
  readonly coords: string;
  readonly download: string;
  readonly noHref: boolean;
  readonly ping: string;
  readonly referrerPolicy: string;
  readonly rel: string;
  readonly shape: string;
  readonly target: string;
}

declare const HTMLAudioElementBrand: unique symbol;
export interface HTMLAudioElement extends HTMLMediaElement {
  readonly [HTMLAudioElementBrand]: never;
}

declare const HTMLBRElementBrand: unique symbol;
export interface HTMLBRElement extends HTMLElement {
  readonly [HTMLBRElementBrand]: never;
  readonly clear: string;
}

declare const HTMLBaseElementBrand: unique symbol;
export interface HTMLBaseElement extends HTMLElement {
  readonly [HTMLBaseElementBrand]: never;
  readonly href: string;
  readonly target: string;
}

declare const HTMLBodyElementBrand: unique symbol;
export interface HTMLBodyElement extends HTMLElement {
  readonly [HTMLBodyElementBrand]: never;
  readonly aLink: string;
  readonly background: string;
  readonly bgColor: string;
  readonly link: string;
  readonly text: string;
  readonly vLink: string;
}

declare const HTMLButtonElementBrand: unique symbol;
export interface HTMLButtonElement extends HTMLElement {
  readonly [HTMLButtonElementBrand]: never;
  readonly command: string;
  readonly disabled: boolean;
  readonly formAction: string;
  readonly formEnctype: string;
  readonly formMethod: string;
  readonly formNoValidate: boolean;
  readonly formTarget: string;
  readonly name: string;
  readonly validationMessage: string;
  readonly value: string;
  readonly willValidate: boolean;
}

declare const HTMLCanvasElementBrand: unique symbol;
export interface HTMLCanvasElement extends HTMLElement {
  readonly [HTMLCanvasElementBrand]: never;
  readonly height: number;
  readonly width: number;
}

declare const HTMLDListElementBrand: unique symbol;
export interface HTMLDListElement extends HTMLElement {
  readonly [HTMLDListElementBrand]: never;
  readonly compact: boolean;
}

declare const HTMLDataElementBrand: unique symbol;
export interface HTMLDataElement extends HTMLElement {
  readonly [HTMLDataElementBrand]: never;
  readonly value: string;
}

declare const HTMLDataListElementBrand: unique symbol;
export interface HTMLDataListElement extends HTMLElement {
  readonly [HTMLDataListElementBrand]: never;
}

declare const HTMLDetailsElementBrand: unique symbol;
export interface HTMLDetailsElement extends HTMLElement {
  readonly [HTMLDetailsElementBrand]: never;
  readonly name: string;
  readonly open: boolean;
}

declare const HTMLDialogElementBrand: unique symbol;
export interface HTMLDialogElement extends HTMLElement {
  readonly [HTMLDialogElementBrand]: never;
  readonly closedBy: string;
  readonly open: boolean;
  readonly returnValue: string;
}

declare const HTMLDivElementBrand: unique symbol;
export interface HTMLDivElement extends HTMLElement {
  readonly [HTMLDivElementBrand]: never;
  readonly align: string;
}

declare const HTMLEmbedElementBrand: unique symbol;
export interface HTMLEmbedElement extends HTMLElement {
  readonly [HTMLEmbedElementBrand]: never;
  readonly align: string;
  readonly height: string;
  readonly name: string;
  readonly src: string;
  readonly type: string;
  readonly width: string;
}

declare const HTMLFieldSetElementBrand: unique symbol;
export interface HTMLFieldSetElement extends HTMLElement {
  readonly [HTMLFieldSetElementBrand]: never;
  readonly disabled: boolean;
  readonly name: string;
  readonly type: string;
  readonly validationMessage: string;
  readonly willValidate: boolean;
}

declare const HTMLFormElementBrand: unique symbol;
export interface HTMLFormElement extends HTMLElement {
  readonly [HTMLFormElementBrand]: never;
  readonly acceptCharset: string;
  readonly action: string;
  readonly encoding: string;
  readonly enctype: string;
  readonly length: number;
  readonly method: string;
  readonly name: string;
  readonly noValidate: boolean;
  readonly rel: string;
  readonly target: string;
}

declare const HTMLHRElementBrand: unique symbol;
export interface HTMLHRElement extends HTMLElement {
  readonly [HTMLHRElementBrand]: never;
  readonly align: string;
  readonly color: string;
  readonly noShade: boolean;
  readonly size: string;
  readonly width: string;
}

declare const HTMLHeadElementBrand: unique symbol;
export interface HTMLHeadElement extends HTMLElement {
  readonly [HTMLHeadElementBrand]: never;
}

declare const HTMLHeadingElementBrand: unique symbol;
export interface HTMLHeadingElement extends HTMLElement {
  readonly [HTMLHeadingElementBrand]: never;
  readonly align: string;
}

declare const HTMLHtmlElementBrand: unique symbol;
export interface HTMLHtmlElement extends HTMLElement {
  readonly [HTMLHtmlElementBrand]: never;
  readonly version: string;
}

declare const HTMLIFrameElementBrand: unique symbol;
export interface HTMLIFrameElement extends HTMLElement {
  readonly [HTMLIFrameElementBrand]: never;
  readonly align: string;
  readonly contentWindow: Window | null;
  readonly allow: string;
  readonly allowFullscreen: boolean;
  readonly frameBorder: string;
  readonly height: string;
  readonly longDesc: string;
  readonly marginHeight: string;
  readonly marginWidth: string;
  readonly name: string;
  readonly scrolling: string;
  readonly src: string;
  readonly srcdoc: string;
  readonly width: string;
}

declare const HTMLImageElementBrand: unique symbol;
export interface HTMLImageElement extends HTMLElement {
  readonly [HTMLImageElementBrand]: never;
  readonly align: string;
  readonly alt: string;
  readonly border: string;
  readonly complete: boolean;
  readonly crossOrigin: string | null;
  readonly currentSrc: string;
  readonly height: number;
  readonly hspace: number;
  readonly isMap: boolean;
  readonly longDesc: string;
  readonly lowsrc: string;
  readonly name: string;
  readonly naturalHeight: number;
  readonly naturalWidth: number;
  readonly referrerPolicy: string;
  readonly sizes: string;
  readonly src: string;
  readonly srcset: string;
  readonly useMap: string;
  readonly vspace: number;
  readonly width: number;
  readonly x: number;
  readonly y: number;
}

declare const HTMLInputElementBrand: unique symbol;
export interface HTMLInputElement extends HTMLElement {
  readonly [HTMLInputElementBrand]: never;
  /**
   * Selects part of what is typed here, and puts the caret at the end of it.
   *
   * @param start Where the selection begins, counted in characters.
   * @param end Where it ends.
   */
  setSelectionRange(start: number, end: number): void;
  /**
   * Selects all of it.
   */
  select(): void;
  readonly accept: string;
  readonly align: string;
  readonly alt: string;
  readonly capture: string;
  readonly checked: boolean;
  readonly defaultChecked: boolean;
  readonly defaultValue: string;
  readonly dirName: string;
  readonly disabled: boolean;
  readonly formAction: string;
  readonly formEnctype: string;
  readonly formMethod: string;
  readonly formNoValidate: boolean;
  readonly formTarget: string;
  readonly height: number;
  readonly indeterminate: boolean;
  readonly max: string;
  readonly maxLength: number;
  readonly min: string;
  readonly minLength: number;
  readonly multiple: boolean;
  readonly name: string;
  readonly pattern: string;
  readonly placeholder: string;
  readonly readOnly: boolean;
  readonly required: boolean;
  readonly size: number;
  readonly src: string;
  readonly step: string;
  readonly type: string;
  readonly useMap: string;
  readonly validationMessage: string;
  readonly value: string;
  readonly valueAsNumber: number;
  readonly webkitdirectory: boolean;
  readonly width: number;
  readonly willValidate: boolean;
}

declare const HTMLLIElementBrand: unique symbol;
export interface HTMLLIElement extends HTMLElement {
  readonly [HTMLLIElementBrand]: never;
  readonly type: string;
  readonly value: number;
}

declare const HTMLLabelElementBrand: unique symbol;
export interface HTMLLabelElement extends HTMLElement {
  readonly [HTMLLabelElementBrand]: never;
  readonly htmlFor: string;
}

declare const HTMLLegendElementBrand: unique symbol;
export interface HTMLLegendElement extends HTMLElement {
  readonly [HTMLLegendElementBrand]: never;
  readonly align: string;
}

declare const HTMLLinkElementBrand: unique symbol;
export interface HTMLLinkElement extends HTMLElement {
  readonly [HTMLLinkElementBrand]: never;
  readonly as: string;
  readonly charset: string;
  readonly crossOrigin: string | null;
  readonly disabled: boolean;
  readonly href: string;
  readonly hreflang: string;
  readonly imageSizes: string;
  readonly imageSrcset: string;
  readonly integrity: string;
  readonly media: string;
  readonly referrerPolicy: string;
  readonly rel: string;
  readonly rev: string;
  readonly target: string;
  readonly type: string;
}

declare const HTMLMapElementBrand: unique symbol;
export interface HTMLMapElement extends HTMLElement {
  readonly [HTMLMapElementBrand]: never;
  readonly name: string;
}

declare const HTMLMenuElementBrand: unique symbol;
export interface HTMLMenuElement extends HTMLElement {
  readonly [HTMLMenuElementBrand]: never;
  readonly compact: boolean;
}

declare const HTMLMetaElementBrand: unique symbol;
export interface HTMLMetaElement extends HTMLElement {
  readonly [HTMLMetaElementBrand]: never;
  readonly content: string;
  readonly httpEquiv: string;
  readonly media: string;
  readonly name: string;
  readonly scheme: string;
}

declare const HTMLMeterElementBrand: unique symbol;
export interface HTMLMeterElement extends HTMLElement {
  readonly [HTMLMeterElementBrand]: never;
  readonly high: number;
  readonly low: number;
  readonly max: number;
  readonly min: number;
  readonly optimum: number;
  readonly value: number;
}

declare const HTMLModElementBrand: unique symbol;
export interface HTMLModElement extends HTMLElement {
  readonly [HTMLModElementBrand]: never;
  readonly cite: string;
  readonly dateTime: string;
}

declare const HTMLOListElementBrand: unique symbol;
export interface HTMLOListElement extends HTMLElement {
  readonly [HTMLOListElementBrand]: never;
  readonly compact: boolean;
  readonly reversed: boolean;
  readonly start: number;
  readonly type: string;
}

declare const HTMLObjectElementBrand: unique symbol;
export interface HTMLObjectElement extends HTMLElement {
  readonly [HTMLObjectElementBrand]: never;
  readonly align: string;
  readonly archive: string;
  readonly border: string;
  readonly code: string;
  readonly codeBase: string;
  readonly codeType: string;
  readonly data: string;
  readonly declare: boolean;
  readonly height: string;
  readonly hspace: number;
  readonly name: string;
  readonly standby: string;
  readonly type: string;
  readonly useMap: string;
  readonly validationMessage: string;
  readonly vspace: number;
  readonly width: string;
  readonly willValidate: boolean;
}

declare const HTMLOptGroupElementBrand: unique symbol;
export interface HTMLOptGroupElement extends HTMLElement {
  readonly [HTMLOptGroupElementBrand]: never;
  readonly disabled: boolean;
  readonly label: string;
}

declare const HTMLOptionElementBrand: unique symbol;
export interface HTMLOptionElement extends HTMLElement {
  readonly [HTMLOptionElementBrand]: never;
  readonly defaultSelected: boolean;
  readonly disabled: boolean;
  readonly index: number;
  readonly label: string;
  readonly selected: boolean;
  readonly text: string;
  readonly value: string;
}

declare const HTMLOutputElementBrand: unique symbol;
export interface HTMLOutputElement extends HTMLElement {
  readonly [HTMLOutputElementBrand]: never;
  readonly defaultValue: string;
  readonly name: string;
  readonly type: string;
  readonly validationMessage: string;
  readonly value: string;
  readonly willValidate: boolean;
}

declare const HTMLParagraphElementBrand: unique symbol;
export interface HTMLParagraphElement extends HTMLElement {
  readonly [HTMLParagraphElementBrand]: never;
  readonly align: string;
}

declare const HTMLPictureElementBrand: unique symbol;
export interface HTMLPictureElement extends HTMLElement {
  readonly [HTMLPictureElementBrand]: never;
}

declare const HTMLPreElementBrand: unique symbol;
export interface HTMLPreElement extends HTMLElement {
  readonly [HTMLPreElementBrand]: never;
  readonly width: number;
}

declare const HTMLProgressElementBrand: unique symbol;
export interface HTMLProgressElement extends HTMLElement {
  readonly [HTMLProgressElementBrand]: never;
  readonly max: number;
  readonly position: number;
  readonly value: number;
}

declare const HTMLQuoteElementBrand: unique symbol;
export interface HTMLQuoteElement extends HTMLElement {
  readonly [HTMLQuoteElementBrand]: never;
  readonly cite: string;
}

declare const HTMLScriptElementBrand: unique symbol;
export interface HTMLScriptElement extends HTMLElement {
  readonly [HTMLScriptElementBrand]: never;
  readonly async: boolean;
  readonly charset: string;
  readonly crossOrigin: string | null;
  readonly defer: boolean;
  readonly event: string;
  readonly htmlFor: string;
  readonly integrity: string;
  readonly noModule: boolean;
  readonly referrerPolicy: string;
  readonly src: string;
  readonly text: string;
  readonly type: string;
}

declare const HTMLSelectElementBrand: unique symbol;
export interface HTMLSelectElement extends HTMLElement {
  readonly [HTMLSelectElementBrand]: never;
  readonly disabled: boolean;
  readonly length: number;
  readonly multiple: boolean;
  readonly name: string;
  readonly required: boolean;
  readonly selectedIndex: number;
  readonly size: number;
  readonly validationMessage: string;
  readonly value: string;
  readonly willValidate: boolean;
}

declare const HTMLSlotElementBrand: unique symbol;
export interface HTMLSlotElement extends HTMLElement {
  readonly [HTMLSlotElementBrand]: never;
  readonly name: string;
}

declare const HTMLSourceElementBrand: unique symbol;
export interface HTMLSourceElement extends HTMLElement {
  readonly [HTMLSourceElementBrand]: never;
  readonly height: number;
  readonly media: string;
  readonly sizes: string;
  readonly src: string;
  readonly srcset: string;
  readonly type: string;
  readonly width: number;
}

declare const HTMLSpanElementBrand: unique symbol;
export interface HTMLSpanElement extends HTMLElement {
  readonly [HTMLSpanElementBrand]: never;
}

declare const HTMLStyleElementBrand: unique symbol;
export interface HTMLStyleElement extends HTMLElement {
  readonly [HTMLStyleElementBrand]: never;
  readonly disabled: boolean;
  readonly media: string;
  readonly type: string;
}

declare const HTMLTableCaptionElementBrand: unique symbol;
export interface HTMLTableCaptionElement extends HTMLElement {
  readonly [HTMLTableCaptionElementBrand]: never;
  readonly align: string;
}

declare const HTMLTableCellElementBrand: unique symbol;
export interface HTMLTableCellElement extends HTMLElement {
  readonly [HTMLTableCellElementBrand]: never;
  readonly abbr: string;
  readonly align: string;
  readonly axis: string;
  readonly bgColor: string;
  readonly cellIndex: number;
  readonly ch: string;
  readonly chOff: string;
  readonly colSpan: number;
  readonly headers: string;
  readonly height: string;
  readonly noWrap: boolean;
  readonly rowSpan: number;
  readonly scope: string;
  readonly vAlign: string;
  readonly width: string;
}

declare const HTMLTableColElementBrand: unique symbol;
export interface HTMLTableColElement extends HTMLElement {
  readonly [HTMLTableColElementBrand]: never;
  readonly align: string;
  readonly ch: string;
  readonly chOff: string;
  readonly span: number;
  readonly vAlign: string;
  readonly width: string;
}

declare const HTMLTableElementBrand: unique symbol;
export interface HTMLTableElement extends HTMLElement {
  readonly [HTMLTableElementBrand]: never;
  readonly align: string;
  readonly bgColor: string;
  readonly border: string;
  readonly cellPadding: string;
  readonly cellSpacing: string;
  readonly frame: string;
  readonly rules: string;
  readonly summary: string;
  readonly width: string;
}

declare const HTMLTableRowElementBrand: unique symbol;
export interface HTMLTableRowElement extends HTMLElement {
  readonly [HTMLTableRowElementBrand]: never;
  readonly align: string;
  readonly bgColor: string;
  readonly ch: string;
  readonly chOff: string;
  readonly rowIndex: number;
  readonly sectionRowIndex: number;
  readonly vAlign: string;
}

declare const HTMLTableSectionElementBrand: unique symbol;
export interface HTMLTableSectionElement extends HTMLElement {
  readonly [HTMLTableSectionElementBrand]: never;
  readonly align: string;
  readonly ch: string;
  readonly chOff: string;
  readonly vAlign: string;
}

declare const HTMLTemplateElementBrand: unique symbol;
export interface HTMLTemplateElement extends HTMLElement {
  readonly [HTMLTemplateElementBrand]: never;
  readonly shadowRootClonable: boolean;
  readonly shadowRootCustomElementRegistry: string;
  readonly shadowRootDelegatesFocus: boolean;
  readonly shadowRootMode: string;
  readonly shadowRootSerializable: boolean;
}

declare const HTMLTextAreaElementBrand: unique symbol;
export interface HTMLTextAreaElement extends HTMLElement {
  readonly [HTMLTextAreaElementBrand]: never;
  /**
   * Selects part of what is typed here, and puts the caret at the end of it.
   *
   * @param start Where the selection begins, counted in characters.
   * @param end Where it ends.
   */
  setSelectionRange(start: number, end: number): void;
  /**
   * Selects all of it.
   */
  select(): void;
  readonly cols: number;
  readonly defaultValue: string;
  readonly dirName: string;
  readonly disabled: boolean;
  readonly maxLength: number;
  readonly minLength: number;
  readonly name: string;
  readonly placeholder: string;
  readonly readOnly: boolean;
  readonly required: boolean;
  readonly rows: number;
  readonly selectionEnd: number;
  readonly selectionStart: number;
  readonly textLength: number;
  readonly type: string;
  readonly validationMessage: string;
  readonly value: string;
  readonly willValidate: boolean;
  readonly wrap: string;
}

declare const HTMLTimeElementBrand: unique symbol;
export interface HTMLTimeElement extends HTMLElement {
  readonly [HTMLTimeElementBrand]: never;
  readonly dateTime: string;
}

declare const HTMLTitleElementBrand: unique symbol;
export interface HTMLTitleElement extends HTMLElement {
  readonly [HTMLTitleElementBrand]: never;
  readonly text: string;
}

declare const HTMLTrackElementBrand: unique symbol;
export interface HTMLTrackElement extends HTMLElement {
  readonly [HTMLTrackElementBrand]: never;
  readonly default: boolean;
  readonly kind: string;
  readonly label: string;
  readonly readyState: number;
  readonly src: string;
  readonly srclang: string;
}

declare const HTMLUListElementBrand: unique symbol;
export interface HTMLUListElement extends HTMLElement {
  readonly [HTMLUListElementBrand]: never;
  readonly compact: boolean;
  readonly type: string;
}

declare const HTMLVideoElementBrand: unique symbol;
export interface HTMLVideoElement extends HTMLMediaElement {
  readonly [HTMLVideoElementBrand]: never;
  readonly disablePictureInPicture: boolean;
  readonly height: number;
  readonly playsInline: boolean;
  readonly poster: string;
  readonly videoHeight: number;
  readonly videoWidth: number;
  readonly width: number;
}

declare const HTMLMediaElementBrand: unique symbol;
export interface HTMLMediaElement extends HTMLElement {
  readonly [HTMLMediaElementBrand]: never;
  readonly autoplay: boolean;
  readonly controls: boolean;
  readonly crossOrigin: string | null;
  readonly currentSrc: string;
  readonly currentTime: number;
  readonly defaultMuted: boolean;
  readonly defaultPlaybackRate: number;
  readonly disableRemotePlayback: boolean;
  readonly duration: number;
  readonly ended: boolean;
  readonly loop: boolean;
  readonly muted: boolean;
  readonly networkState: number;
  readonly paused: boolean;
  readonly playbackRate: number;
  readonly preservesPitch: boolean;
  readonly readyState: number;
  readonly seeking: boolean;
  readonly sinkId: string;
  readonly src: string;
  readonly volume: number;
}

declare const HTMLHyperlinkElementUtilsBrand: unique symbol;
export interface HTMLHyperlinkElementUtils extends EventTarget {
  readonly [HTMLHyperlinkElementUtilsBrand]: never;
  readonly hash: string;
  readonly host: string;
  readonly hostname: string;
  readonly href: string;
  readonly origin: string;
  readonly password: string;
  readonly pathname: string;
  readonly port: string;
  readonly protocol: string;
  readonly search: string;
  readonly username: string;
}

declare const HTMLOrSVGElementBrand: unique symbol;
export interface HTMLOrSVGElement extends EventTarget {
  readonly [HTMLOrSVGElementBrand]: never;
  readonly autofocus: boolean;
  /**
   * Gives this the keyboard, as clicking it would. What was focused before
   * loses it.
   */
  focus(): void;
  /**
   * Takes the keyboard away from this.
   */
  blur(): void;
  readonly nonce: string;
  readonly tabIndex: number;
}

export type Booleanish = boolean | "true" | "false";

export type Numeric = number | string;

export type AriaRole =
  | "alert"
  | "alertdialog"
  | "application"
  | "article"
  | "banner"
  | "button"
  | "cell"
  | "checkbox"
  | "columnheader"
  | "combobox"
  | "complementary"
  | "contentinfo"
  | "definition"
  | "dialog"
  | "directory"
  | "document"
  | "feed"
  | "figure"
  | "form"
  | "grid"
  | "gridcell"
  | "group"
  | "heading"
  | "img"
  | "link"
  | "list"
  | "listbox"
  | "listitem"
  | "log"
  | "main"
  | "marquee"
  | "math"
  | "menu"
  | "menubar"
  | "menuitem"
  | "menuitemcheckbox"
  | "menuitemradio"
  | "navigation"
  | "none"
  | "note"
  | "option"
  | "presentation"
  | "progressbar"
  | "radio"
  | "radiogroup"
  | "region"
  | "row"
  | "rowgroup"
  | "rowheader"
  | "scrollbar"
  | "search"
  | "searchbox"
  | "separator"
  | "slider"
  | "spinbutton"
  | "status"
  | "switch"
  | "tab"
  | "table"
  | "tablist"
  | "tabpanel"
  | "term"
  | "textbox"
  | "timer"
  | "toolbar"
  | "tooltip"
  | "tree"
  | "treegrid"
  | "treeitem";

export type ReferrerPolicy =
  | ""
  | "no-referrer"
  | "no-referrer-when-downgrade"
  | "origin"
  | "origin-when-cross-origin"
  | "same-origin"
  | "strict-origin"
  | "strict-origin-when-cross-origin"
  | "unsafe-url";

export type CrossOrigin = "anonymous" | "use-credentials" | "";

export type Target = "_self" | "_blank" | "_parent" | "_top";

export interface AriaAttributes {
  "aria-activedescendant"?: Prop<string>;
  "aria-atomic"?: Prop<Booleanish>;
  "aria-autocomplete"?: Prop<"none" | "inline" | "list" | "both">;
  "aria-braillelabel"?: Prop<string>;
  "aria-brailleroledescription"?: Prop<string>;
  "aria-busy"?: Prop<Booleanish>;
  "aria-checked"?: Prop<boolean | "false" | "mixed" | "true">;
  "aria-colcount"?: Prop<number>;
  "aria-colindex"?: Prop<number>;
  "aria-colindextext"?: Prop<string>;
  "aria-colspan"?: Prop<number>;
  "aria-controls"?: Prop<string>;
  "aria-current"?: Prop<
    boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time"
  >;
  "aria-describedby"?: Prop<string>;
  "aria-description"?: Prop<string>;
  "aria-details"?: Prop<string>;
  "aria-disabled"?: Prop<Booleanish>;
  "aria-errormessage"?: Prop<string>;
  "aria-expanded"?: Prop<Booleanish>;
  "aria-flowto"?: Prop<string>;
  "aria-haspopup"?: Prop<
    boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog"
  >;
  "aria-hidden"?: Prop<Booleanish>;
  "aria-invalid"?: Prop<boolean | "false" | "true" | "grammar" | "spelling">;
  "aria-keyshortcuts"?: Prop<string>;
  "aria-label"?: Prop<string>;
  "aria-labelledby"?: Prop<string>;
  "aria-level"?: Prop<number>;
  "aria-live"?: Prop<"off" | "assertive" | "polite">;
  "aria-modal"?: Prop<Booleanish>;
  "aria-multiline"?: Prop<Booleanish>;
  "aria-multiselectable"?: Prop<Booleanish>;
  "aria-orientation"?: Prop<"horizontal" | "vertical">;
  "aria-owns"?: Prop<string>;
  "aria-placeholder"?: Prop<string>;
  "aria-posinset"?: Prop<number>;
  "aria-pressed"?: Prop<boolean | "false" | "mixed" | "true">;
  "aria-readonly"?: Prop<Booleanish>;
  "aria-relevant"?: Prop<
    | "additions"
    | "additions removals"
    | "additions text"
    | "all"
    | "removals"
    | "removals additions"
    | "removals text"
    | "text"
    | "text additions"
    | "text removals"
  >;
  "aria-required"?: Prop<Booleanish>;
  "aria-roledescription"?: Prop<string>;
  "aria-rowcount"?: Prop<number>;
  "aria-rowindex"?: Prop<number>;
  "aria-rowindextext"?: Prop<string>;
  "aria-rowspan"?: Prop<number>;
  "aria-selected"?: Prop<Booleanish>;
  "aria-setsize"?: Prop<number>;
  "aria-sort"?: Prop<"none" | "ascending" | "descending" | "other">;
  "aria-valuemax"?: Prop<number>;
  "aria-valuemin"?: Prop<number>;
  "aria-valuenow"?: Prop<number>;
  "aria-valuetext"?: Prop<string>;
}

export interface Events<T extends ClientValue> {
  oncopy?: Prop<(event: ClipboardEvent<T>) => void>;
  oncut?: Prop<(event: ClipboardEvent<T>) => void>;
  onpaste?: Prop<(event: ClipboardEvent<T>) => void>;
  oncompositionend?: Prop<(event: CompositionEvent<T>) => void>;
  oncompositionstart?: Prop<(event: CompositionEvent<T>) => void>;
  oncompositionupdate?: Prop<(event: CompositionEvent<T>) => void>;
  onblur?: Prop<(event: FocusEvent<T>) => void>;
  onfocus?: Prop<(event: FocusEvent<T>) => void>;
  onfocusin?: Prop<(event: FocusEvent<T>) => void>;
  onfocusout?: Prop<(event: FocusEvent<T>) => void>;
  onbeforeinput?: Prop<(event: InputEvent<T>) => void>;
  onchange?: Prop<(event: Event<T>) => void>;
  oninput?: Prop<(event: InputEvent<T>) => void>;
  oninvalid?: Prop<(event: Event<T>) => void>;
  onreset?: Prop<(event: Event<T>) => void>;
  onselect?: Prop<(event: Event<T>) => void>;
  onsubmit?: Prop<(event: SubmitEvent<T>) => void>;
  onerror?: Prop<(event: ErrorEvent<T>) => void>;
  onload?: Prop<(event: Event<T>) => void>;
  onkeydown?: Prop<(event: KeyboardEvent<T>) => void>;
  onkeypress?: Prop<(event: KeyboardEvent<T>) => void>;
  onkeyup?: Prop<(event: KeyboardEvent<T>) => void>;
  onabort?: Prop<(event: UIEvent<T>) => void>;
  oncanplay?: Prop<(event: Event<T>) => void>;
  oncanplaythrough?: Prop<(event: Event<T>) => void>;
  ondurationchange?: Prop<(event: Event<T>) => void>;
  onemptied?: Prop<(event: Event<T>) => void>;
  onended?: Prop<(event: Event<T>) => void>;
  onloadeddata?: Prop<(event: Event<T>) => void>;
  onloadedmetadata?: Prop<(event: Event<T>) => void>;
  onloadstart?: Prop<(event: Event<T>) => void>;
  onpause?: Prop<(event: Event<T>) => void>;
  onplay?: Prop<(event: Event<T>) => void>;
  onplaying?: Prop<(event: Event<T>) => void>;
  onprogress?: Prop<(event: ProgressEvent<T>) => void>;
  onratechange?: Prop<(event: Event<T>) => void>;
  onseeked?: Prop<(event: Event<T>) => void>;
  onseeking?: Prop<(event: Event<T>) => void>;
  onstalled?: Prop<(event: Event<T>) => void>;
  onsuspend?: Prop<(event: Event<T>) => void>;
  ontimeupdate?: Prop<(event: Event<T>) => void>;
  onvolumechange?: Prop<(event: Event<T>) => void>;
  onwaiting?: Prop<(event: Event<T>) => void>;
  onauxclick?: Prop<(event: PointerEvent<T>) => void>;
  onclick?: Prop<(event: PointerEvent<T>) => void>;
  oncontextmenu?: Prop<(event: PointerEvent<T>) => void>;
  ondblclick?: Prop<(event: MouseEvent<T>) => void>;
  onmousedown?: Prop<(event: MouseEvent<T>) => void>;
  onmouseenter?: Prop<(event: MouseEvent<T>) => void>;
  onmouseleave?: Prop<(event: MouseEvent<T>) => void>;
  onmousemove?: Prop<(event: MouseEvent<T>) => void>;
  onmouseout?: Prop<(event: MouseEvent<T>) => void>;
  onmouseover?: Prop<(event: MouseEvent<T>) => void>;
  onmouseup?: Prop<(event: MouseEvent<T>) => void>;
  ondrag?: Prop<(event: DragEvent<T>) => void>;
  ondragend?: Prop<(event: DragEvent<T>) => void>;
  ondragenter?: Prop<(event: DragEvent<T>) => void>;
  ondragleave?: Prop<(event: DragEvent<T>) => void>;
  ondragover?: Prop<(event: DragEvent<T>) => void>;
  ondragstart?: Prop<(event: DragEvent<T>) => void>;
  ondrop?: Prop<(event: DragEvent<T>) => void>;
  ontouchcancel?: Prop<(event: TouchEvent<T>) => void>;
  ontouchend?: Prop<(event: TouchEvent<T>) => void>;
  ontouchmove?: Prop<(event: TouchEvent<T>) => void>;
  ontouchstart?: Prop<(event: TouchEvent<T>) => void>;
  ongotpointercapture?: Prop<(event: PointerEvent<T>) => void>;
  onlostpointercapture?: Prop<(event: PointerEvent<T>) => void>;
  onpointercancel?: Prop<(event: PointerEvent<T>) => void>;
  onpointerdown?: Prop<(event: PointerEvent<T>) => void>;
  onpointerenter?: Prop<(event: PointerEvent<T>) => void>;
  onpointerleave?: Prop<(event: PointerEvent<T>) => void>;
  onpointermove?: Prop<(event: PointerEvent<T>) => void>;
  onpointerout?: Prop<(event: PointerEvent<T>) => void>;
  onpointerover?: Prop<(event: PointerEvent<T>) => void>;
  onpointerup?: Prop<(event: PointerEvent<T>) => void>;
  onscroll?: Prop<(event: Event<T>) => void>;
  onscrollend?: Prop<(event: Event<T>) => void>;
  onwheel?: Prop<(event: WheelEvent<T>) => void>;
  onanimationend?: Prop<(event: AnimationEvent<T>) => void>;
  onanimationiteration?: Prop<(event: AnimationEvent<T>) => void>;
  onanimationstart?: Prop<(event: AnimationEvent<T>) => void>;
  ontransitioncancel?: Prop<(event: TransitionEvent<T>) => void>;
  ontransitionend?: Prop<(event: TransitionEvent<T>) => void>;
  ontransitionrun?: Prop<(event: TransitionEvent<T>) => void>;
  ontransitionstart?: Prop<(event: TransitionEvent<T>) => void>;
  onbeforetoggle?: Prop<(event: ToggleEvent<T>) => void>;
  ontoggle?: Prop<(event: ToggleEvent<T>) => void>;
}

export interface GlobalAttributes<T extends ClientValue>
  extends AriaAttributes, Events<T> {
  accesskey?: Prop<string>;
  autocapitalize?: Prop<
    "off" | "none" | "on" | "sentences" | "words" | "characters"
  >;
  autocorrect?: Prop<"on" | "off">;
  autofocus?: Prop<boolean>;
  class?: Prop<string>;
  contenteditable?: Prop<Booleanish | "inherit" | "plaintext-only">;
  dir?: Prop<"ltr" | "rtl" | "auto">;
  draggable?: Prop<Booleanish>;
  enterkeyhint?: Prop<
    "enter" | "done" | "go" | "next" | "previous" | "search" | "send"
  >;
  exportparts?: Prop<string>;
  hidden?: Prop<boolean | "until-found">;
  id?: Prop<string>;
  inert?: Prop<boolean>;
  inputmode?: Prop<
    "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search"
  >;
  is?: Prop<string>;
  itemid?: Prop<string>;
  itemprop?: Prop<string>;
  itemref?: Prop<string>;
  itemscope?: Prop<boolean>;
  itemtype?: Prop<string>;
  lang?: Prop<string>;
  nonce?: Prop<string>;
  part?: Prop<string>;
  popover?: Prop<"" | "auto" | "manual" | "hint">;
  role?: Prop<AriaRole>;
  xmlns?: Prop<string>;
  slot?: Prop<string>;
  spellcheck?: Prop<Booleanish>;
  style?: Prop<string>;
  tabindex?: Prop<number>;
  title?: Prop<string>;
  translate?: Prop<"yes" | "no">;
}

export interface VoidProps<T extends ClientValue> extends GlobalAttributes<T> {}

export interface HtmlProps<T extends ClientValue> extends GlobalAttributes<T> {
  children?: Children;
}

export interface AnchorProps extends HtmlProps<HTMLAnchorElement> {
  download?: Prop<string | boolean>;
  href?: Prop<string>;
  hreflang?: Prop<string>;
  media?: Prop<string>;
  ping?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  rel?: Prop<string>;
  target?: Prop<Target>;
  type?: Prop<string>;
}

export interface AreaProps extends VoidProps<HTMLAreaElement> {
  alt?: Prop<string>;
  coords?: Prop<string>;
  download?: Prop<string | boolean>;
  href?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  rel?: Prop<string>;
  shape?: Prop<"rect" | "circle" | "poly" | "default">;
  target?: Prop<Target>;
}

export interface BaseProps extends VoidProps<HTMLBaseElement> {
  href?: Prop<string>;
  target?: Prop<Target>;
}

export interface BlockquoteProps extends HtmlProps<HTMLQuoteElement> {
  cite?: Prop<string>;
}

export interface ButtonProps extends HtmlProps<HTMLButtonElement> {
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  formaction?: Prop<string>;
  formenctype?: Prop<string>;
  formmethod?: Prop<"get" | "post" | "dialog">;
  formnovalidate?: Prop<boolean>;
  formtarget?: Prop<Target>;
  name?: Prop<string>;
  popovertarget?: Prop<string>;
  popovertargetaction?: Prop<"toggle" | "show" | "hide">;
  type?: Prop<"submit" | "reset" | "button">;
  value?: Prop<string | number>;
}

export interface CanvasProps extends HtmlProps<HTMLCanvasElement> {
  height?: Prop<Numeric>;
  width?: Prop<Numeric>;
}

export interface ColProps extends VoidProps<HTMLTableColElement> {
  span?: Prop<number>;
  width?: Prop<Numeric>;
}

export interface ColgroupProps extends HtmlProps<HTMLTableColElement> {
  span?: Prop<number>;
}

export interface DataProps extends HtmlProps<HTMLDataElement> {
  value?: Prop<string | number>;
}

export interface DelProps extends HtmlProps<HTMLModElement> {
  cite?: Prop<string>;
  datetime?: Prop<string>;
}

export interface DetailsProps extends HtmlProps<HTMLDetailsElement> {
  name?: Prop<string>;
  open?: Prop<boolean>;
}

export interface DialogProps extends HtmlProps<HTMLDialogElement> {
  closedby?: Prop<"any" | "closerequest" | "none">;
  open?: Prop<boolean>;
}

export interface EmbedProps extends VoidProps<HTMLEmbedElement> {
  height?: Prop<Numeric>;
  src?: Prop<string>;
  type?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface FieldsetProps extends HtmlProps<HTMLFieldSetElement> {
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  name?: Prop<string>;
}

export interface FormProps extends HtmlProps<HTMLFormElement> {
  "accept-charset"?: Prop<string>;
  action?: Prop<string>;
  autocomplete?: Prop<"on" | "off">;
  enctype?: Prop<string>;
  method?: Prop<"get" | "post" | "dialog">;
  name?: Prop<string>;
  novalidate?: Prop<boolean>;
  rel?: Prop<string>;
  target?: Prop<Target>;
}

export interface HtmlElementProps extends HtmlProps<HTMLHtmlElement> {
  manifest?: Prop<string>;
}

export interface IframeProps extends HtmlProps<HTMLIFrameElement> {
  allow?: Prop<string>;
  allowfullscreen?: Prop<boolean>;
  height?: Prop<Numeric>;
  loading?: Prop<"eager" | "lazy">;
  name?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  sandbox?: Prop<string>;
  src?: Prop<string>;
  srcdoc?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface ImgProps extends VoidProps<HTMLImageElement> {
  alt?: Prop<string>;
  crossorigin?: Prop<CrossOrigin>;
  decoding?: Prop<"async" | "auto" | "sync">;
  fetchpriority?: Prop<"high" | "low" | "auto">;
  height?: Prop<Numeric>;
  loading?: Prop<"eager" | "lazy">;
  referrerpolicy?: Prop<ReferrerPolicy>;
  sizes?: Prop<string>;
  src?: Prop<string>;
  srcset?: Prop<string>;
  usemap?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface InputProps extends VoidProps<HTMLInputElement> {
  accept?: Prop<string>;
  alt?: Prop<string>;
  autocomplete?: Prop<string>;
  capture?: Prop<boolean | "user" | "environment">;
  checked?: Prop<boolean>;
  dirname?: Prop<string>;
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  formaction?: Prop<string>;
  formenctype?: Prop<string>;
  formmethod?: Prop<"get" | "post" | "dialog">;
  formnovalidate?: Prop<boolean>;
  formtarget?: Prop<Target>;
  height?: Prop<Numeric>;
  list?: Prop<string>;
  max?: Prop<Numeric>;
  maxlength?: Prop<number>;
  min?: Prop<Numeric>;
  minlength?: Prop<number>;
  multiple?: Prop<boolean>;
  name?: Prop<string>;
  pattern?: Prop<string>;
  placeholder?: Prop<string>;
  readonly?: Prop<boolean>;
  required?: Prop<boolean>;
  size?: Prop<number>;
  src?: Prop<string>;
  step?: Prop<Numeric>;
  type?: Prop<
    | "button"
    | "checkbox"
    | "color"
    | "date"
    | "datetime-local"
    | "email"
    | "file"
    | "hidden"
    | "image"
    | "month"
    | "number"
    | "password"
    | "radio"
    | "range"
    | "reset"
    | "search"
    | "submit"
    | "tel"
    | "text"
    | "time"
    | "url"
    | "week"
  >;
  value?: Prop<string | number>;
  width?: Prop<Numeric>;
}

export interface InsProps extends HtmlProps<HTMLModElement> {
  cite?: Prop<string>;
  datetime?: Prop<string>;
}

export interface LabelProps extends HtmlProps<HTMLLabelElement> {
  for?: Prop<string>;
  form?: Prop<string>;
}

export interface LiProps extends HtmlProps<HTMLLIElement> {
  value?: Prop<number>;
}

export interface LinkProps extends VoidProps<HTMLLinkElement> {
  as?: Prop<string>;
  crossorigin?: Prop<CrossOrigin>;
  fetchpriority?: Prop<"high" | "low" | "auto">;
  href?: Prop<string>;
  hreflang?: Prop<string>;
  imagesizes?: Prop<string>;
  imagesrcset?: Prop<string>;
  integrity?: Prop<string>;
  media?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  rel?: Prop<string>;
  sizes?: Prop<string>;
  type?: Prop<string>;
}

export interface MapProps extends HtmlProps<HTMLMapElement> {
  name?: Prop<string>;
}

export interface MediaProps extends HtmlProps<HTMLAudioElement> {
  autoplay?: Prop<boolean>;
  controls?: Prop<boolean>;
  controlslist?: Prop<string>;
  crossorigin?: Prop<CrossOrigin>;
  loop?: Prop<boolean>;
  muted?: Prop<boolean>;
  preload?: Prop<"none" | "metadata" | "auto" | "">;
  src?: Prop<string>;
}

export interface MetaProps extends VoidProps<HTMLMetaElement> {
  charset?: Prop<string>;
  content?: Prop<string>;
  "http-equiv"?: Prop<string>;
  media?: Prop<string>;
  name?: Prop<string>;
}

export interface MeterProps extends HtmlProps<HTMLMeterElement> {
  form?: Prop<string>;
  high?: Prop<number>;
  low?: Prop<number>;
  max?: Prop<Numeric>;
  min?: Prop<Numeric>;
  optimum?: Prop<number>;
  value?: Prop<string | number>;
}

export interface ObjectProps extends HtmlProps<HTMLObjectElement> {
  data?: Prop<string>;
  form?: Prop<string>;
  height?: Prop<Numeric>;
  name?: Prop<string>;
  type?: Prop<string>;
  usemap?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface OlProps extends HtmlProps<HTMLOListElement> {
  reversed?: Prop<boolean>;
  start?: Prop<number>;
  type?: Prop<"1" | "a" | "A" | "i" | "I">;
}

export interface OptgroupProps extends HtmlProps<HTMLOptGroupElement> {
  disabled?: Prop<boolean>;
  label?: Prop<string>;
}

export interface OptionProps extends HtmlProps<HTMLOptionElement> {
  disabled?: Prop<boolean>;
  label?: Prop<string>;
  selected?: Prop<boolean>;
  value?: Prop<string | number>;
}

export interface OutputProps extends HtmlProps<HTMLOutputElement> {
  for?: Prop<string>;
  form?: Prop<string>;
  name?: Prop<string>;
}

export interface ProgressProps extends HtmlProps<HTMLProgressElement> {
  max?: Prop<Numeric>;
  value?: Prop<string | number>;
}

export interface QuoteProps extends HtmlProps<HTMLQuoteElement> {
  cite?: Prop<string>;
}

export interface SelectProps extends HtmlProps<HTMLSelectElement> {
  autocomplete?: Prop<string>;
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  multiple?: Prop<boolean>;
  name?: Prop<string>;
  required?: Prop<boolean>;
  size?: Prop<number>;
  value?: Prop<string | number>;
}

export interface SlotProps extends HtmlProps<HTMLSlotElement> {
  name?: Prop<string>;
}

export interface SourceProps extends VoidProps<HTMLSourceElement> {
  height?: Prop<Numeric>;
  media?: Prop<string>;
  sizes?: Prop<string>;
  src?: Prop<string>;
  srcset?: Prop<string>;
  type?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface StyleProps extends HtmlProps<HTMLStyleElement> {
  media?: Prop<string>;
  type?: Prop<string>;
}

export interface TableProps extends HtmlProps<HTMLTableElement> {
  summary?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface TdProps extends HtmlProps<HTMLTableCellElement> {
  colspan?: Prop<number>;
  headers?: Prop<string>;
  rowspan?: Prop<number>;
}

export interface ThProps extends HtmlProps<HTMLTableCellElement> {
  abbr?: Prop<string>;
  colspan?: Prop<number>;
  headers?: Prop<string>;
  rowspan?: Prop<number>;
  scope?: Prop<"row" | "col" | "rowgroup" | "colgroup">;
}

export interface TextareaProps extends HtmlProps<HTMLTextAreaElement> {
  autocomplete?: Prop<string>;
  cols?: Prop<number>;
  dirname?: Prop<string>;
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  maxlength?: Prop<number>;
  minlength?: Prop<number>;
  name?: Prop<string>;
  placeholder?: Prop<string>;
  readonly?: Prop<boolean>;
  required?: Prop<boolean>;
  rows?: Prop<number>;
  value?: Prop<string | number>;
  wrap?: Prop<"hard" | "soft" | "off">;
}

export interface TimeProps extends HtmlProps<HTMLTimeElement> {
  datetime?: Prop<string>;
}

export interface TrackProps extends VoidProps<HTMLTrackElement> {
  default?: Prop<boolean>;
  kind?: Prop<
    "subtitles" | "captions" | "descriptions" | "chapters" | "metadata"
  >;
  label?: Prop<string>;
  src?: Prop<string>;
  srclang?: Prop<string>;
}

export interface VideoProps extends MediaProps {
  disablepictureinpicture?: Prop<boolean>;
  disableremoteplayback?: Prop<boolean>;
  height?: Prop<Numeric>;
  playsinline?: Prop<boolean>;
  poster?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface SvgProps extends AriaAttributes, Events<SVGElement> {
  children?: Children;
  id?: Prop<string>;
  class?: Prop<string>;
  style?: Prop<string>;
  lang?: Prop<string>;
  tabindex?: Prop<number>;
  role?: Prop<AriaRole>;
  xmlns?: Prop<string>;
  accentHeight?: Prop<Numeric>;
  accumulate?: Prop<string>;
  additive?: Prop<string>;
  "alignment-baseline"?: Prop<string>;
  allowReorder?: Prop<string>;
  alphabetic?: Prop<Numeric>;
  amplitude?: Prop<Numeric>;
  arabicForm?: Prop<string>;
  ascent?: Prop<Numeric>;
  attributeName?: Prop<string>;
  attributeType?: Prop<string>;
  autoReverse?: Prop<Booleanish>;
  azimuth?: Prop<Numeric>;
  baseFrequency?: Prop<Numeric>;
  baseProfile?: Prop<Numeric>;
  "baseline-shift"?: Prop<Numeric>;
  bbox?: Prop<Numeric>;
  begin?: Prop<Numeric>;
  bias?: Prop<Numeric>;
  by?: Prop<Numeric>;
  calcMode?: Prop<Numeric>;
  capHeight?: Prop<Numeric>;
  clip?: Prop<Numeric>;
  "clip-path"?: Prop<string>;
  clipPathUnits?: Prop<Numeric>;
  "clip-rule"?: Prop<Numeric>;
  color?: Prop<string>;
  "color-interpolation"?: Prop<Numeric>;
  "color-interpolation-filters"?: Prop<string>;
  "color-profile"?: Prop<Numeric>;
  "color-rendering"?: Prop<Numeric>;
  contentScriptType?: Prop<Numeric>;
  contentStyleType?: Prop<Numeric>;
  crossOrigin?: Prop<string>;
  cursor?: Prop<Numeric>;
  cx?: Prop<Numeric>;
  cy?: Prop<Numeric>;
  d?: Prop<string>;
  decelerate?: Prop<Numeric>;
  descent?: Prop<Numeric>;
  diffuseConstant?: Prop<Numeric>;
  direction?: Prop<Numeric>;
  display?: Prop<Numeric>;
  divisor?: Prop<Numeric>;
  "dominant-baseline"?: Prop<Numeric>;
  dur?: Prop<Numeric>;
  dx?: Prop<Numeric>;
  dy?: Prop<Numeric>;
  edgeMode?: Prop<Numeric>;
  elevation?: Prop<Numeric>;
  "enable-background"?: Prop<Numeric>;
  end?: Prop<Numeric>;
  exponent?: Prop<Numeric>;
  externalResourcesRequired?: Prop<Booleanish>;
  fill?: Prop<string>;
  "fill-opacity"?: Prop<Numeric>;
  "fill-rule"?: Prop<string>;
  filter?: Prop<string>;
  filterRes?: Prop<Numeric>;
  filterUnits?: Prop<Numeric>;
  "flood-color"?: Prop<Numeric>;
  "flood-opacity"?: Prop<Numeric>;
  focusable?: Prop<string>;
  "font-family"?: Prop<string>;
  "font-size"?: Prop<Numeric>;
  "font-size-adjust"?: Prop<Numeric>;
  "font-stretch"?: Prop<Numeric>;
  "font-style"?: Prop<Numeric>;
  "font-variant"?: Prop<Numeric>;
  "font-weight"?: Prop<Numeric>;
  format?: Prop<Numeric>;
  fr?: Prop<Numeric>;
  from?: Prop<Numeric>;
  fx?: Prop<Numeric>;
  fy?: Prop<Numeric>;
  g1?: Prop<Numeric>;
  g2?: Prop<Numeric>;
  glyphName?: Prop<Numeric>;
  "glyph-orientation-horizontal"?: Prop<Numeric>;
  "glyph-orientation-vertical"?: Prop<Numeric>;
  glyphRef?: Prop<Numeric>;
  gradientTransform?: Prop<string>;
  gradientUnits?: Prop<string>;
  hanging?: Prop<Numeric>;
  height?: Prop<Numeric>;
  horizAdvX?: Prop<Numeric>;
  horizOriginX?: Prop<Numeric>;
  href?: Prop<string>;
  ideographic?: Prop<Numeric>;
  "image-rendering"?: Prop<Numeric>;
  in?: Prop<string>;
  in2?: Prop<Numeric>;
  intercept?: Prop<Numeric>;
  k?: Prop<Numeric>;
  k1?: Prop<Numeric>;
  k2?: Prop<Numeric>;
  k3?: Prop<Numeric>;
  k4?: Prop<Numeric>;
  kernelMatrix?: Prop<Numeric>;
  kernelUnitLength?: Prop<Numeric>;
  kerning?: Prop<Numeric>;
  keyPoints?: Prop<Numeric>;
  keySplines?: Prop<Numeric>;
  keyTimes?: Prop<Numeric>;
  lengthAdjust?: Prop<Numeric>;
  "letter-spacing"?: Prop<Numeric>;
  "lighting-color"?: Prop<Numeric>;
  limitingConeAngle?: Prop<Numeric>;
  local?: Prop<Numeric>;
  "marker-end"?: Prop<string>;
  markerHeight?: Prop<Numeric>;
  "marker-mid"?: Prop<string>;
  "marker-start"?: Prop<string>;
  markerUnits?: Prop<Numeric>;
  markerWidth?: Prop<Numeric>;
  mask?: Prop<string>;
  maskContentUnits?: Prop<Numeric>;
  maskUnits?: Prop<Numeric>;
  mathematical?: Prop<Numeric>;
  max?: Prop<Numeric>;
  media?: Prop<string>;
  method?: Prop<string>;
  min?: Prop<Numeric>;
  mode?: Prop<Numeric>;
  name?: Prop<string>;
  numOctaves?: Prop<Numeric>;
  offset?: Prop<Numeric>;
  opacity?: Prop<Numeric>;
  operator?: Prop<Numeric>;
  order?: Prop<Numeric>;
  orient?: Prop<Numeric>;
  orientation?: Prop<Numeric>;
  origin?: Prop<Numeric>;
  overflow?: Prop<Numeric>;
  "overline-position"?: Prop<Numeric>;
  "overline-thickness"?: Prop<Numeric>;
  "paint-order"?: Prop<Numeric>;
  panose1?: Prop<Numeric>;
  path?: Prop<string>;
  pathLength?: Prop<Numeric>;
  patternContentUnits?: Prop<string>;
  patternTransform?: Prop<Numeric>;
  patternUnits?: Prop<string>;
  "pointer-events"?: Prop<Numeric>;
  points?: Prop<string>;
  pointsAtX?: Prop<Numeric>;
  pointsAtY?: Prop<Numeric>;
  pointsAtZ?: Prop<Numeric>;
  preserveAlpha?: Prop<Booleanish>;
  preserveAspectRatio?: Prop<string>;
  primitiveUnits?: Prop<Numeric>;
  r?: Prop<Numeric>;
  radius?: Prop<Numeric>;
  refX?: Prop<Numeric>;
  refY?: Prop<Numeric>;
  "rendering-intent"?: Prop<Numeric>;
  repeatCount?: Prop<Numeric>;
  repeatDur?: Prop<Numeric>;
  requiredExtensions?: Prop<Numeric>;
  requiredFeatures?: Prop<Numeric>;
  restart?: Prop<Numeric>;
  result?: Prop<string>;
  rotate?: Prop<Numeric>;
  rx?: Prop<Numeric>;
  ry?: Prop<Numeric>;
  scale?: Prop<Numeric>;
  seed?: Prop<Numeric>;
  "shape-rendering"?: Prop<Numeric>;
  slope?: Prop<Numeric>;
  spacing?: Prop<Numeric>;
  specularConstant?: Prop<Numeric>;
  specularExponent?: Prop<Numeric>;
  speed?: Prop<Numeric>;
  spreadMethod?: Prop<string>;
  startOffset?: Prop<Numeric>;
  stdDeviation?: Prop<Numeric>;
  stemh?: Prop<Numeric>;
  stemv?: Prop<Numeric>;
  stitchTiles?: Prop<Numeric>;
  "stop-color"?: Prop<string>;
  "stop-opacity"?: Prop<Numeric>;
  "strikethrough-position"?: Prop<Numeric>;
  "strikethrough-thickness"?: Prop<Numeric>;
  string?: Prop<Numeric>;
  stroke?: Prop<string>;
  "stroke-dasharray"?: Prop<Numeric>;
  "stroke-dashoffset"?: Prop<Numeric>;
  "stroke-linecap"?: Prop<string>;
  "stroke-linejoin"?: Prop<string>;
  "stroke-miterlimit"?: Prop<Numeric>;
  "stroke-opacity"?: Prop<Numeric>;
  "stroke-width"?: Prop<Numeric>;
  surfaceScale?: Prop<Numeric>;
  systemLanguage?: Prop<Numeric>;
  tableValues?: Prop<Numeric>;
  target?: Prop<string>;
  targetX?: Prop<Numeric>;
  targetY?: Prop<Numeric>;
  "text-anchor"?: Prop<string>;
  "text-decoration"?: Prop<Numeric>;
  textLength?: Prop<Numeric>;
  "text-rendering"?: Prop<Numeric>;
  to?: Prop<Numeric>;
  transform?: Prop<string>;
  type?: Prop<string>;
  u1?: Prop<Numeric>;
  u2?: Prop<Numeric>;
  "underline-position"?: Prop<Numeric>;
  "underline-thickness"?: Prop<Numeric>;
  unicode?: Prop<Numeric>;
  "unicode-bidi"?: Prop<Numeric>;
  "unicode-range"?: Prop<Numeric>;
  "units-per-em"?: Prop<Numeric>;
  "v-alphabetic"?: Prop<Numeric>;
  "v-hanging"?: Prop<Numeric>;
  "v-ideographic"?: Prop<Numeric>;
  "v-mathematical"?: Prop<Numeric>;
  values?: Prop<string>;
  "vector-effect"?: Prop<Numeric>;
  version?: Prop<string>;
  "vert-adv-y"?: Prop<Numeric>;
  "vert-origin-x"?: Prop<Numeric>;
  "vert-origin-y"?: Prop<Numeric>;
  viewBox?: Prop<string>;
  viewTarget?: Prop<Numeric>;
  visibility?: Prop<Numeric>;
  width?: Prop<Numeric>;
  widths?: Prop<Numeric>;
  "word-spacing"?: Prop<Numeric>;
  "writing-mode"?: Prop<Numeric>;
  x?: Prop<Numeric>;
  x1?: Prop<Numeric>;
  x2?: Prop<Numeric>;
  xChannelSelector?: Prop<string>;
  xHeight?: Prop<Numeric>;
  xlinkActuate?: Prop<string>;
  xlinkArcrole?: Prop<string>;
  xlinkHref?: Prop<string>;
  xlinkRole?: Prop<string>;
  xlinkShow?: Prop<string>;
  xlinkTitle?: Prop<string>;
  xlinkType?: Prop<string>;
  xmlBase?: Prop<string>;
  xmlLang?: Prop<string>;
  xmlSpace?: Prop<string>;
  xmlnsXlink?: Prop<string>;
  y?: Prop<Numeric>;
  y1?: Prop<Numeric>;
  y2?: Prop<Numeric>;
  yChannelSelector?: Prop<string>;
  z?: Prop<Numeric>;
  zoomAndPan?: Prop<string>;
}

/** The elements this schema declares, and what each accepts. */
export interface WebElements {
  a: AnchorProps;
  abbr: HtmlProps<HTMLElement>;
  address: HtmlProps<HTMLElement>;
  area: AreaProps;
  article: HtmlProps<HTMLElement>;
  aside: HtmlProps<HTMLElement>;
  audio: MediaProps;
  b: HtmlProps<HTMLElement>;
  base: BaseProps;
  bdi: HtmlProps<HTMLElement>;
  bdo: HtmlProps<HTMLElement>;
  blockquote: BlockquoteProps;
  body: HtmlProps<HTMLBodyElement>;
  br: VoidProps<HTMLBRElement>;
  button: ButtonProps;
  canvas: CanvasProps;
  caption: HtmlProps<HTMLTableCaptionElement>;
  cite: HtmlProps<HTMLElement>;
  code: HtmlProps<HTMLElement>;
  col: ColProps;
  colgroup: ColgroupProps;
  data: DataProps;
  datalist: HtmlProps<HTMLDataListElement>;
  dd: HtmlProps<HTMLElement>;
  del: DelProps;
  details: DetailsProps;
  dfn: HtmlProps<HTMLElement>;
  dialog: DialogProps;
  div: HtmlProps<HTMLDivElement>;
  dl: HtmlProps<HTMLDListElement>;
  dt: HtmlProps<HTMLElement>;
  em: HtmlProps<HTMLElement>;
  embed: EmbedProps;
  fieldset: FieldsetProps;
  figcaption: HtmlProps<HTMLElement>;
  figure: HtmlProps<HTMLElement>;
  footer: HtmlProps<HTMLElement>;
  form: FormProps;
  h1: HtmlProps<HTMLHeadingElement>;
  h2: HtmlProps<HTMLHeadingElement>;
  h3: HtmlProps<HTMLHeadingElement>;
  h4: HtmlProps<HTMLHeadingElement>;
  h5: HtmlProps<HTMLHeadingElement>;
  h6: HtmlProps<HTMLHeadingElement>;
  head: HtmlProps<HTMLHeadElement>;
  header: HtmlProps<HTMLElement>;
  hgroup: HtmlProps<HTMLElement>;
  hr: VoidProps<HTMLHRElement>;
  html: HtmlElementProps;
  i: HtmlProps<HTMLElement>;
  iframe: IframeProps;
  img: ImgProps;
  input: InputProps;
  ins: InsProps;
  kbd: HtmlProps<HTMLElement>;
  label: LabelProps;
  legend: HtmlProps<HTMLLegendElement>;
  li: LiProps;
  link: LinkProps;
  main: HtmlProps<HTMLElement>;
  map: MapProps;
  mark: HtmlProps<HTMLElement>;
  menu: HtmlProps<HTMLMenuElement>;
  meta: MetaProps;
  meter: MeterProps;
  nav: HtmlProps<HTMLElement>;
  noscript: HtmlProps<HTMLElement>;
  object: ObjectProps;
  ol: OlProps;
  optgroup: OptgroupProps;
  option: OptionProps;
  output: OutputProps;
  p: HtmlProps<HTMLParagraphElement>;
  picture: HtmlProps<HTMLPictureElement>;
  pre: HtmlProps<HTMLPreElement>;
  progress: ProgressProps;
  q: QuoteProps;
  rp: HtmlProps<HTMLElement>;
  rt: HtmlProps<HTMLElement>;
  ruby: HtmlProps<HTMLElement>;
  s: HtmlProps<HTMLElement>;
  samp: HtmlProps<HTMLElement>;
  search: HtmlProps<HTMLElement>;
  section: HtmlProps<HTMLElement>;
  select: SelectProps;
  slot: SlotProps;
  small: HtmlProps<HTMLElement>;
  source: SourceProps;
  span: HtmlProps<HTMLSpanElement>;
  strong: HtmlProps<HTMLElement>;
  style: StyleProps;
  sub: HtmlProps<HTMLElement>;
  summary: HtmlProps<HTMLElement>;
  sup: HtmlProps<HTMLElement>;
  table: TableProps;
  tbody: HtmlProps<HTMLTableSectionElement>;
  td: TdProps;
  template: HtmlProps<HTMLTemplateElement>;
  textarea: TextareaProps;
  tfoot: HtmlProps<HTMLTableSectionElement>;
  th: ThProps;
  thead: HtmlProps<HTMLTableSectionElement>;
  time: TimeProps;
  title: HtmlProps<HTMLTitleElement>;
  tr: HtmlProps<HTMLTableRowElement>;
  track: TrackProps;
  u: HtmlProps<HTMLElement>;
  ul: HtmlProps<HTMLUListElement>;
  var: HtmlProps<HTMLElement>;
  video: VideoProps;
  wbr: VoidProps<HTMLElement>;
  animate: SvgProps;
  animateMotion: SvgProps;
  animateTransform: SvgProps;
  circle: SvgProps;
  clipPath: SvgProps;
  defs: SvgProps;
  desc: SvgProps;
  ellipse: SvgProps;
  feBlend: SvgProps;
  feColorMatrix: SvgProps;
  feComponentTransfer: SvgProps;
  feComposite: SvgProps;
  feConvolveMatrix: SvgProps;
  feDiffuseLighting: SvgProps;
  feDisplacementMap: SvgProps;
  feDistantLight: SvgProps;
  feDropShadow: SvgProps;
  feFlood: SvgProps;
  feFuncA: SvgProps;
  feFuncB: SvgProps;
  feFuncG: SvgProps;
  feFuncR: SvgProps;
  feGaussianBlur: SvgProps;
  feImage: SvgProps;
  feMerge: SvgProps;
  feMergeNode: SvgProps;
  feMorphology: SvgProps;
  feOffset: SvgProps;
  fePointLight: SvgProps;
  feSpecularLighting: SvgProps;
  feSpotLight: SvgProps;
  feTile: SvgProps;
  feTurbulence: SvgProps;
  filter: SvgProps;
  foreignObject: SvgProps;
  g: SvgProps;
  image: SvgProps;
  line: SvgProps;
  linearGradient: SvgProps;
  marker: SvgProps;
  mask: SvgProps;
  metadata: SvgProps;
  mpath: SvgProps;
  path: SvgProps;
  pattern: SvgProps;
  polygon: SvgProps;
  polyline: SvgProps;
  radialGradient: SvgProps;
  rect: SvgProps;
  set: SvgProps;
  stop: SvgProps;
  svg: SvgProps;
  switch: SvgProps;
  symbol: SvgProps;
  text: SvgProps;
  textPath: SvgProps;
  tspan: SvgProps;
  use: SvgProps;
  view: SvgProps;
}

/** Every element in scope, this schema's own and its bases'. */
export interface Elements extends UiPlatformElements, WebElements {}

/** What this schema declares, which is what its own client answers for. */
export interface WebBuiltins {
  window: Window;
}

/** What a client must answer with, for every name in scope. */
export interface Builtins extends UiPlatformBuiltins, WebBuiltins {}
