// Generated by `pnpm generate`. Do not edit.

import type { Children, Client, Element, Prop } from "@backtickjs/core-schema";

export type Booleanish = boolean | "true" | "false";

export type Numeric = number | string;

export type AriaRole =
  | "alert"
  | "alertdialog"
  | "application"
  | "article"
  | "banner"
  | "button"
  | "cell"
  | "checkbox"
  | "columnheader"
  | "combobox"
  | "complementary"
  | "contentinfo"
  | "definition"
  | "dialog"
  | "directory"
  | "document"
  | "feed"
  | "figure"
  | "form"
  | "grid"
  | "gridcell"
  | "group"
  | "heading"
  | "img"
  | "link"
  | "list"
  | "listbox"
  | "listitem"
  | "log"
  | "main"
  | "marquee"
  | "math"
  | "menu"
  | "menubar"
  | "menuitem"
  | "menuitemcheckbox"
  | "menuitemradio"
  | "navigation"
  | "none"
  | "note"
  | "option"
  | "presentation"
  | "progressbar"
  | "radio"
  | "radiogroup"
  | "region"
  | "row"
  | "rowgroup"
  | "rowheader"
  | "scrollbar"
  | "search"
  | "searchbox"
  | "separator"
  | "slider"
  | "spinbutton"
  | "status"
  | "switch"
  | "tab"
  | "table"
  | "tablist"
  | "tabpanel"
  | "term"
  | "textbox"
  | "timer"
  | "toolbar"
  | "tooltip"
  | "tree"
  | "treegrid"
  | "treeitem";

export type ReferrerPolicy =
  | ""
  | "no-referrer"
  | "no-referrer-when-downgrade"
  | "origin"
  | "origin-when-cross-origin"
  | "same-origin"
  | "strict-origin"
  | "strict-origin-when-cross-origin"
  | "unsafe-url";

export type CrossOrigin = "anonymous" | "use-credentials" | "";

export type Target = "_self" | "_blank" | "_parent" | "_top";

export interface AriaAttributes {
  "aria-activedescendant"?: Prop<string>;
  "aria-atomic"?: Prop<Booleanish>;
  "aria-autocomplete"?: Prop<"none" | "inline" | "list" | "both">;
  "aria-braillelabel"?: Prop<string>;
  "aria-brailleroledescription"?: Prop<string>;
  "aria-busy"?: Prop<Booleanish>;
  "aria-checked"?: Prop<boolean | "false" | "mixed" | "true">;
  "aria-colcount"?: Prop<number>;
  "aria-colindex"?: Prop<number>;
  "aria-colindextext"?: Prop<string>;
  "aria-colspan"?: Prop<number>;
  "aria-controls"?: Prop<string>;
  "aria-current"?: Prop<
    boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time"
  >;
  "aria-describedby"?: Prop<string>;
  "aria-description"?: Prop<string>;
  "aria-details"?: Prop<string>;
  "aria-disabled"?: Prop<Booleanish>;
  "aria-errormessage"?: Prop<string>;
  "aria-expanded"?: Prop<Booleanish>;
  "aria-flowto"?: Prop<string>;
  "aria-haspopup"?: Prop<
    boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog"
  >;
  "aria-hidden"?: Prop<Booleanish>;
  "aria-invalid"?: Prop<boolean | "false" | "true" | "grammar" | "spelling">;
  "aria-keyshortcuts"?: Prop<string>;
  "aria-label"?: Prop<string>;
  "aria-labelledby"?: Prop<string>;
  "aria-level"?: Prop<number>;
  "aria-live"?: Prop<"off" | "assertive" | "polite">;
  "aria-modal"?: Prop<Booleanish>;
  "aria-multiline"?: Prop<Booleanish>;
  "aria-multiselectable"?: Prop<Booleanish>;
  "aria-orientation"?: Prop<"horizontal" | "vertical">;
  "aria-owns"?: Prop<string>;
  "aria-placeholder"?: Prop<string>;
  "aria-posinset"?: Prop<number>;
  "aria-pressed"?: Prop<boolean | "false" | "mixed" | "true">;
  "aria-readonly"?: Prop<Booleanish>;
  "aria-relevant"?: Prop<
    | "additions"
    | "additions removals"
    | "additions text"
    | "all"
    | "removals"
    | "removals additions"
    | "removals text"
    | "text"
    | "text additions"
    | "text removals"
  >;
  "aria-required"?: Prop<Booleanish>;
  "aria-roledescription"?: Prop<string>;
  "aria-rowcount"?: Prop<number>;
  "aria-rowindex"?: Prop<number>;
  "aria-rowindextext"?: Prop<string>;
  "aria-rowspan"?: Prop<number>;
  "aria-selected"?: Prop<Booleanish>;
  "aria-setsize"?: Prop<number>;
  "aria-sort"?: Prop<"none" | "ascending" | "descending" | "other">;
  "aria-valuemax"?: Prop<number>;
  "aria-valuemin"?: Prop<number>;
  "aria-valuenow"?: Prop<number>;
  "aria-valuetext"?: Prop<string>;
}

export interface Events {
  oncopy?: Client<() => void>;
  oncut?: Client<() => void>;
  onpaste?: Client<() => void>;
  oncompositionend?: Client<() => void>;
  oncompositionstart?: Client<() => void>;
  oncompositionupdate?: Client<() => void>;
  onblur?: Client<() => void>;
  onfocus?: Client<() => void>;
  onfocusin?: Client<() => void>;
  onfocusout?: Client<() => void>;
  onbeforeinput?: Client<() => void>;
  onchange?: Client<() => void>;
  oninput?: Client<() => void>;
  oninvalid?: Client<() => void>;
  onreset?: Client<() => void>;
  onselect?: Client<() => void>;
  onsubmit?: Client<() => void>;
  onerror?: Client<() => void>;
  onload?: Client<() => void>;
  onkeydown?: Client<() => void>;
  onkeypress?: Client<() => void>;
  onkeyup?: Client<() => void>;
  onabort?: Client<() => void>;
  oncanplay?: Client<() => void>;
  oncanplaythrough?: Client<() => void>;
  ondurationchange?: Client<() => void>;
  onemptied?: Client<() => void>;
  onended?: Client<() => void>;
  onloadeddata?: Client<() => void>;
  onloadedmetadata?: Client<() => void>;
  onloadstart?: Client<() => void>;
  onpause?: Client<() => void>;
  onplay?: Client<() => void>;
  onplaying?: Client<() => void>;
  onprogress?: Client<() => void>;
  onratechange?: Client<() => void>;
  onseeked?: Client<() => void>;
  onseeking?: Client<() => void>;
  onstalled?: Client<() => void>;
  onsuspend?: Client<() => void>;
  ontimeupdate?: Client<() => void>;
  onvolumechange?: Client<() => void>;
  onwaiting?: Client<() => void>;
  onauxclick?: Client<() => void>;
  onclick?: Client<() => void>;
  oncontextmenu?: Client<() => void>;
  ondblclick?: Client<() => void>;
  onmousedown?: Client<() => void>;
  onmouseenter?: Client<() => void>;
  onmouseleave?: Client<() => void>;
  onmousemove?: Client<() => void>;
  onmouseout?: Client<() => void>;
  onmouseover?: Client<() => void>;
  onmouseup?: Client<() => void>;
  ondrag?: Client<() => void>;
  ondragend?: Client<() => void>;
  ondragenter?: Client<() => void>;
  ondragleave?: Client<() => void>;
  ondragover?: Client<() => void>;
  ondragstart?: Client<() => void>;
  ondrop?: Client<() => void>;
  ontouchcancel?: Client<() => void>;
  ontouchend?: Client<() => void>;
  ontouchmove?: Client<() => void>;
  ontouchstart?: Client<() => void>;
  ongotpointercapture?: Client<() => void>;
  onlostpointercapture?: Client<() => void>;
  onpointercancel?: Client<() => void>;
  onpointerdown?: Client<() => void>;
  onpointerenter?: Client<() => void>;
  onpointerleave?: Client<() => void>;
  onpointermove?: Client<() => void>;
  onpointerout?: Client<() => void>;
  onpointerover?: Client<() => void>;
  onpointerup?: Client<() => void>;
  onscroll?: Client<() => void>;
  onscrollend?: Client<() => void>;
  onwheel?: Client<() => void>;
  onanimationend?: Client<() => void>;
  onanimationiteration?: Client<() => void>;
  onanimationstart?: Client<() => void>;
  ontransitioncancel?: Client<() => void>;
  ontransitionend?: Client<() => void>;
  ontransitionrun?: Client<() => void>;
  ontransitionstart?: Client<() => void>;
  onbeforetoggle?: Client<() => void>;
  ontoggle?: Client<() => void>;
}

export interface GlobalAttributes extends AriaAttributes, Events {
  accesskey?: Prop<string>;
  autocapitalize?: Prop<
    "off" | "none" | "on" | "sentences" | "words" | "characters"
  >;
  autocorrect?: Prop<"on" | "off">;
  autofocus?: Prop<boolean>;
  class?: Prop<string>;
  contenteditable?: Prop<Booleanish | "inherit" | "plaintext-only">;
  dir?: Prop<"ltr" | "rtl" | "auto">;
  draggable?: Prop<Booleanish>;
  enterkeyhint?: Prop<
    "enter" | "done" | "go" | "next" | "previous" | "search" | "send"
  >;
  exportparts?: Prop<string>;
  hidden?: Prop<boolean | "until-found">;
  id?: Prop<string>;
  inert?: Prop<boolean>;
  inputmode?: Prop<
    "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search"
  >;
  is?: Prop<string>;
  itemid?: Prop<string>;
  itemprop?: Prop<string>;
  itemref?: Prop<string>;
  itemscope?: Prop<boolean>;
  itemtype?: Prop<string>;
  lang?: Prop<string>;
  nonce?: Prop<string>;
  part?: Prop<string>;
  popover?: Prop<"" | "auto" | "manual" | "hint">;
  role?: Prop<AriaRole>;
  slot?: Prop<string>;
  spellcheck?: Prop<Booleanish>;
  style?: Prop<string>;
  tabindex?: Prop<number>;
  title?: Prop<string>;
  translate?: Prop<"yes" | "no">;
}

export interface VoidProps extends GlobalAttributes {}

export interface HtmlProps extends GlobalAttributes {
  children?: Children<Element | string | number>;
}

export interface FragmentProps {
  readonly children: Element | string | number;
}

export interface AnchorProps extends HtmlProps {
  download?: Prop<string | boolean>;
  href?: Prop<string>;
  hreflang?: Prop<string>;
  media?: Prop<string>;
  ping?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  rel?: Prop<string>;
  target?: Prop<Target>;
  type?: Prop<string>;
}

export interface AreaProps extends VoidProps {
  alt?: Prop<string>;
  coords?: Prop<string>;
  download?: Prop<string | boolean>;
  href?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  rel?: Prop<string>;
  shape?: Prop<"rect" | "circle" | "poly" | "default">;
  target?: Prop<Target>;
}

export interface BaseProps extends VoidProps {
  href?: Prop<string>;
  target?: Prop<Target>;
}

export interface BlockquoteProps extends HtmlProps {
  cite?: Prop<string>;
}

export interface ButtonProps extends HtmlProps {
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  formaction?: Prop<string>;
  formenctype?: Prop<string>;
  formmethod?: Prop<"get" | "post" | "dialog">;
  formnovalidate?: Prop<boolean>;
  formtarget?: Prop<Target>;
  name?: Prop<string>;
  popovertarget?: Prop<string>;
  popovertargetaction?: Prop<"toggle" | "show" | "hide">;
  type?: Prop<"submit" | "reset" | "button">;
  value?: Prop<string | number>;
}

export interface CanvasProps extends HtmlProps {
  height?: Prop<Numeric>;
  width?: Prop<Numeric>;
}

export interface ColProps extends VoidProps {
  span?: Prop<number>;
  width?: Prop<Numeric>;
}

export interface ColgroupProps extends HtmlProps {
  span?: Prop<number>;
}

export interface DataProps extends HtmlProps {
  value?: Prop<string | number>;
}

export interface DelProps extends HtmlProps {
  cite?: Prop<string>;
  datetime?: Prop<string>;
}

export interface DetailsProps extends HtmlProps {
  name?: Prop<string>;
  open?: Prop<boolean>;
}

export interface DialogProps extends HtmlProps {
  closedby?: Prop<"any" | "closerequest" | "none">;
  open?: Prop<boolean>;
}

export interface EmbedProps extends VoidProps {
  height?: Prop<Numeric>;
  src?: Prop<string>;
  type?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface FieldsetProps extends HtmlProps {
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  name?: Prop<string>;
}

export interface FormProps extends HtmlProps {
  "accept-charset"?: Prop<string>;
  action?: Prop<string>;
  autocomplete?: Prop<"on" | "off">;
  enctype?: Prop<string>;
  method?: Prop<"get" | "post" | "dialog">;
  name?: Prop<string>;
  novalidate?: Prop<boolean>;
  rel?: Prop<string>;
  target?: Prop<Target>;
}

export interface HtmlElementProps extends HtmlProps {
  manifest?: Prop<string>;
}

export interface IframeProps extends HtmlProps {
  allow?: Prop<string>;
  allowfullscreen?: Prop<boolean>;
  height?: Prop<Numeric>;
  loading?: Prop<"eager" | "lazy">;
  name?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  sandbox?: Prop<string>;
  src?: Prop<string>;
  srcdoc?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface ImgProps extends VoidProps {
  alt?: Prop<string>;
  crossorigin?: Prop<CrossOrigin>;
  decoding?: Prop<"async" | "auto" | "sync">;
  fetchpriority?: Prop<"high" | "low" | "auto">;
  height?: Prop<Numeric>;
  loading?: Prop<"eager" | "lazy">;
  referrerpolicy?: Prop<ReferrerPolicy>;
  sizes?: Prop<string>;
  src?: Prop<string>;
  srcset?: Prop<string>;
  usemap?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface InputProps extends VoidProps {
  accept?: Prop<string>;
  alt?: Prop<string>;
  autocomplete?: Prop<string>;
  capture?: Prop<boolean | "user" | "environment">;
  checked?: Prop<boolean>;
  dirname?: Prop<string>;
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  formaction?: Prop<string>;
  formenctype?: Prop<string>;
  formmethod?: Prop<"get" | "post" | "dialog">;
  formnovalidate?: Prop<boolean>;
  formtarget?: Prop<Target>;
  height?: Prop<Numeric>;
  list?: Prop<string>;
  max?: Prop<Numeric>;
  maxlength?: Prop<number>;
  min?: Prop<Numeric>;
  minlength?: Prop<number>;
  multiple?: Prop<boolean>;
  name?: Prop<string>;
  pattern?: Prop<string>;
  placeholder?: Prop<string>;
  readonly?: Prop<boolean>;
  required?: Prop<boolean>;
  size?: Prop<number>;
  src?: Prop<string>;
  step?: Prop<Numeric>;
  type?: Prop<
    | "button"
    | "checkbox"
    | "color"
    | "date"
    | "datetime-local"
    | "email"
    | "file"
    | "hidden"
    | "image"
    | "month"
    | "number"
    | "password"
    | "radio"
    | "range"
    | "reset"
    | "search"
    | "submit"
    | "tel"
    | "text"
    | "time"
    | "url"
    | "week"
  >;
  value?: Prop<string | number>;
  width?: Prop<Numeric>;
}

export interface InsProps extends HtmlProps {
  cite?: Prop<string>;
  datetime?: Prop<string>;
}

export interface LabelProps extends HtmlProps {
  for?: Prop<string>;
  form?: Prop<string>;
}

export interface LiProps extends HtmlProps {
  value?: Prop<number>;
}

export interface LinkProps extends VoidProps {
  as?: Prop<string>;
  crossorigin?: Prop<CrossOrigin>;
  fetchpriority?: Prop<"high" | "low" | "auto">;
  href?: Prop<string>;
  hreflang?: Prop<string>;
  imagesizes?: Prop<string>;
  imagesrcset?: Prop<string>;
  integrity?: Prop<string>;
  media?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  rel?: Prop<string>;
  sizes?: Prop<string>;
  type?: Prop<string>;
}

export interface MapProps extends HtmlProps {
  name?: Prop<string>;
}

export interface MediaProps extends HtmlProps {
  autoplay?: Prop<boolean>;
  controls?: Prop<boolean>;
  controlslist?: Prop<string>;
  crossorigin?: Prop<CrossOrigin>;
  loop?: Prop<boolean>;
  muted?: Prop<boolean>;
  preload?: Prop<"none" | "metadata" | "auto" | "">;
  src?: Prop<string>;
}

export interface MetaProps extends VoidProps {
  charset?: Prop<string>;
  content?: Prop<string>;
  "http-equiv"?: Prop<string>;
  media?: Prop<string>;
  name?: Prop<string>;
}

export interface MeterProps extends HtmlProps {
  form?: Prop<string>;
  high?: Prop<number>;
  low?: Prop<number>;
  max?: Prop<Numeric>;
  min?: Prop<Numeric>;
  optimum?: Prop<number>;
  value?: Prop<string | number>;
}

export interface ObjectProps extends HtmlProps {
  data?: Prop<string>;
  form?: Prop<string>;
  height?: Prop<Numeric>;
  name?: Prop<string>;
  type?: Prop<string>;
  usemap?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface OlProps extends HtmlProps {
  reversed?: Prop<boolean>;
  start?: Prop<number>;
  type?: Prop<"1" | "a" | "A" | "i" | "I">;
}

export interface OptgroupProps extends HtmlProps {
  disabled?: Prop<boolean>;
  label?: Prop<string>;
}

export interface OptionProps extends HtmlProps {
  disabled?: Prop<boolean>;
  label?: Prop<string>;
  selected?: Prop<boolean>;
  value?: Prop<string | number>;
}

export interface OutputProps extends HtmlProps {
  for?: Prop<string>;
  form?: Prop<string>;
  name?: Prop<string>;
}

export interface ProgressProps extends HtmlProps {
  max?: Prop<Numeric>;
  value?: Prop<string | number>;
}

export interface QuoteProps extends HtmlProps {
  cite?: Prop<string>;
}

export interface ScriptProps extends HtmlProps {
  async?: Prop<boolean>;
  crossorigin?: Prop<CrossOrigin>;
  defer?: Prop<boolean>;
  fetchpriority?: Prop<"high" | "low" | "auto">;
  integrity?: Prop<string>;
  nomodule?: Prop<boolean>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  src?: Prop<string>;
  type?: Prop<string>;
}

export interface SelectProps extends HtmlProps {
  autocomplete?: Prop<string>;
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  multiple?: Prop<boolean>;
  name?: Prop<string>;
  required?: Prop<boolean>;
  size?: Prop<number>;
  value?: Prop<string | number>;
}

export interface SlotProps extends HtmlProps {
  name?: Prop<string>;
}

export interface SourceProps extends VoidProps {
  height?: Prop<Numeric>;
  media?: Prop<string>;
  sizes?: Prop<string>;
  src?: Prop<string>;
  srcset?: Prop<string>;
  type?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface StyleProps extends HtmlProps {
  media?: Prop<string>;
  type?: Prop<string>;
}

export interface TableProps extends HtmlProps {
  summary?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface TdProps extends HtmlProps {
  colspan?: Prop<number>;
  headers?: Prop<string>;
  rowspan?: Prop<number>;
}

export interface ThProps extends HtmlProps {
  abbr?: Prop<string>;
  colspan?: Prop<number>;
  headers?: Prop<string>;
  rowspan?: Prop<number>;
  scope?: Prop<"row" | "col" | "rowgroup" | "colgroup">;
}

export interface TextareaProps extends HtmlProps {
  autocomplete?: Prop<string>;
  cols?: Prop<number>;
  dirname?: Prop<string>;
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  maxlength?: Prop<number>;
  minlength?: Prop<number>;
  name?: Prop<string>;
  placeholder?: Prop<string>;
  readonly?: Prop<boolean>;
  required?: Prop<boolean>;
  rows?: Prop<number>;
  value?: Prop<string | number>;
  wrap?: Prop<"hard" | "soft" | "off">;
}

export interface TimeProps extends HtmlProps {
  datetime?: Prop<string>;
}

export interface TrackProps extends VoidProps {
  default?: Prop<boolean>;
  kind?: Prop<
    "subtitles" | "captions" | "descriptions" | "chapters" | "metadata"
  >;
  label?: Prop<string>;
  src?: Prop<string>;
  srclang?: Prop<string>;
}

export interface VideoProps extends MediaProps {
  disablepictureinpicture?: Prop<boolean>;
  disableremoteplayback?: Prop<boolean>;
  height?: Prop<Numeric>;
  playsinline?: Prop<boolean>;
  poster?: Prop<string>;
  width?: Prop<Numeric>;
}

/** The tags this schema declares, and what each accepts. */
export interface IntrinsicElements {
  a: AnchorProps;
  abbr: HtmlProps;
  address: HtmlProps;
  area: AreaProps;
  article: HtmlProps;
  aside: HtmlProps;
  audio: MediaProps;
  b: HtmlProps;
  base: BaseProps;
  bdi: HtmlProps;
  bdo: HtmlProps;
  blockquote: BlockquoteProps;
  body: HtmlProps;
  br: VoidProps;
  button: ButtonProps;
  canvas: CanvasProps;
  caption: HtmlProps;
  cite: HtmlProps;
  code: HtmlProps;
  col: ColProps;
  colgroup: ColgroupProps;
  data: DataProps;
  datalist: HtmlProps;
  dd: HtmlProps;
  del: DelProps;
  details: DetailsProps;
  dfn: HtmlProps;
  dialog: DialogProps;
  div: HtmlProps;
  dl: HtmlProps;
  dt: HtmlProps;
  em: HtmlProps;
  embed: EmbedProps;
  fieldset: FieldsetProps;
  figcaption: HtmlProps;
  figure: HtmlProps;
  footer: HtmlProps;
  form: FormProps;
  h1: HtmlProps;
  h2: HtmlProps;
  h3: HtmlProps;
  h4: HtmlProps;
  h5: HtmlProps;
  h6: HtmlProps;
  head: HtmlProps;
  header: HtmlProps;
  hgroup: HtmlProps;
  hr: VoidProps;
  html: HtmlElementProps;
  i: HtmlProps;
  iframe: IframeProps;
  img: ImgProps;
  input: InputProps;
  ins: InsProps;
  kbd: HtmlProps;
  label: LabelProps;
  legend: HtmlProps;
  li: LiProps;
  link: LinkProps;
  main: HtmlProps;
  map: MapProps;
  mark: HtmlProps;
  menu: HtmlProps;
  meta: MetaProps;
  meter: MeterProps;
  nav: HtmlProps;
  noscript: HtmlProps;
  object: ObjectProps;
  ol: OlProps;
  optgroup: OptgroupProps;
  option: OptionProps;
  output: OutputProps;
  p: HtmlProps;
  picture: HtmlProps;
  pre: HtmlProps;
  progress: ProgressProps;
  q: QuoteProps;
  rp: HtmlProps;
  rt: HtmlProps;
  ruby: HtmlProps;
  s: HtmlProps;
  samp: HtmlProps;
  script: ScriptProps;
  search: HtmlProps;
  section: HtmlProps;
  select: SelectProps;
  slot: SlotProps;
  small: HtmlProps;
  source: SourceProps;
  span: HtmlProps;
  strong: HtmlProps;
  style: StyleProps;
  sub: HtmlProps;
  summary: HtmlProps;
  sup: HtmlProps;
  table: TableProps;
  tbody: HtmlProps;
  td: TdProps;
  template: HtmlProps;
  textarea: TextareaProps;
  tfoot: HtmlProps;
  th: ThProps;
  thead: HtmlProps;
  time: TimeProps;
  title: HtmlProps;
  tr: HtmlProps;
  track: TrackProps;
  u: HtmlProps;
  ul: HtmlProps;
  var: HtmlProps;
  video: VideoProps;
  wbr: VoidProps;
}
