// Generated by `pnpm generate`. Do not edit.

import { createBuiltin } from "@backtickjs/web-schema";
import type { Client, Diagnostic } from "./declarations.generated.js";

/**
 * Backtick source, compiled to javascript. One callback is called, once —
 * callbacks because waiting is not a thing this language does.
 *
 * @param fileName What to call it. It reaches a reader in a complaint, and it
 * is what decides whether the text is read as `.ts` or `.tsx`.
 * @param sourceText What somebody wrote.
 * @param onJavascript Called with the javascript, in `require`/`exports` form.
 * Nothing has run it yet.
 * @param onDiagnostics Called instead. Not an error: a half-written line
 * answers this way, and the call did what it was asked.
 */
export const compile: Client<
  (
    fileName: string,
    sourceText: string,
    onJavascript: (javascript: string) => void,
    onDiagnostics: (diagnostics: Diagnostic[]) => void,
  ) => void
> = createBuiltin("compile");

/**
 * Javascript, run for the drawing it makes, and that drawing folded into a
 * bundle.
 *
 * Running it is `eval`, which a page saying `default-src 'self'` cannot do —
 * so where this happens is somewhere the page is not, and that is a client's
 * to arrange.
 *
 * Apart from `compile` because the two fail differently: a half-written line
 * is the compiler speaking, and code that throws while it runs is not.
 *
 * @param javascript What `compile` answered with.
 * @param onBundle Called with the bundle. Measuring it is the caller's.
 * @param onDiagnostics Called instead, when what was written threw while it
 * ran or drew nothing. Spans are null here — it failed afterwards.
 */
export const bundle: Client<
  (
    javascript: string,
    onBundle: (bundle: string) => void,
    onDiagnostics: (diagnostics: Diagnostic[]) => void,
  ) => void
> = createBuiltin("bundle");
