// Generated by `pnpm generate`. Do not edit.

import { createBuiltin } from "@backtickjs/web-schema";
import type { Client, Diagnostic } from "./declarations.generated.js";

/**
 * Compiles Backtick source to a bundle. One of the two callbacks is called,
 * once. Callbacks rather than something to wait on, because waiting is not a
 * thing this language does.
 *
 * @param source What somebody wrote.
 * @param onBundle Called with the bundle, when there is one. Measuring it is
 * the caller's: a string knows its own length.
 * @param onDiagnostics Called instead, with what the compiler had to say. Not
 * an error: a half-written line answers this way, and the call did what it was
 * asked.
 */
export const compile: Client<
  (
    source: string,
    onBundle: (bundle: string) => void,
    onDiagnostics: (diagnostics: Diagnostic[]) => void,
  ) => void
> = createBuiltin("compile");
