// Generated by `pnpm generate`. Do not edit.

import type {
  Builtins as WebBuiltins,
  Elements as WebElements,
} from "@backtickjs/web-schema";

export type {
  AnchorProps,
  AnimationEvent,
  AreaProps,
  AriaAttributes,
  AriaRole,
  ArrayLike,
  BacktickRendererProps,
  BaseProps,
  BlockquoteProps,
  Booleanish,
  ButtonProps,
  CanvasProps,
  Children,
  Client,
  ClientElement,
  ClientFunction,
  ClientHandle,
  ClientUnknown,
  ClientValue,
  ClipboardEvent,
  ColProps,
  ColgroupProps,
  CompositionEvent,
  Console,
  CrossOrigin,
  DataProps,
  DelProps,
  DetailsProps,
  DialogProps,
  DragEvent,
  Element,
  EmbedProps,
  ErrorEvent,
  Event,
  EventTarget,
  Events,
  FieldsetProps,
  FocusEvent,
  ForProps,
  FormProps,
  GlobalAttributes,
  HTMLAnchorElement,
  HTMLAreaElement,
  HTMLAudioElement,
  HTMLBRElement,
  HTMLBaseElement,
  HTMLBodyElement,
  HTMLButtonElement,
  HTMLCanvasElement,
  HTMLDListElement,
  HTMLDataElement,
  HTMLDataListElement,
  HTMLDetailsElement,
  HTMLDialogElement,
  HTMLDivElement,
  HTMLElement,
  HTMLEmbedElement,
  HTMLFieldSetElement,
  HTMLFormElement,
  HTMLHRElement,
  HTMLHeadElement,
  HTMLHeadingElement,
  HTMLHtmlElement,
  HTMLHyperlinkElementUtils,
  HTMLIFrameElement,
  HTMLImageElement,
  HTMLInputElement,
  HTMLLIElement,
  HTMLLabelElement,
  HTMLLegendElement,
  HTMLLinkElement,
  HTMLMapElement,
  HTMLMediaElement,
  HTMLMenuElement,
  HTMLMetaElement,
  HTMLMeterElement,
  HTMLModElement,
  HTMLOListElement,
  HTMLObjectElement,
  HTMLOptGroupElement,
  HTMLOptionElement,
  HTMLOrSVGElement,
  HTMLOutputElement,
  HTMLParagraphElement,
  HTMLPictureElement,
  HTMLPreElement,
  HTMLProgressElement,
  HTMLQuoteElement,
  HTMLScriptElement,
  HTMLSelectElement,
  HTMLSlotElement,
  HTMLSourceElement,
  HTMLSpanElement,
  HTMLStyleElement,
  HTMLTableCaptionElement,
  HTMLTableCellElement,
  HTMLTableColElement,
  HTMLTableElement,
  HTMLTableRowElement,
  HTMLTableSectionElement,
  HTMLTemplateElement,
  HTMLTextAreaElement,
  HTMLTimeElement,
  HTMLTitleElement,
  HTMLTrackElement,
  HTMLUListElement,
  HTMLVideoElement,
  HtmlElementProps,
  HtmlNode,
  HtmlProps,
  IframeProps,
  ImgProps,
  InputEvent,
  InputProps,
  InsProps,
  KeyboardEvent,
  LabelProps,
  LiProps,
  LinkProps,
  MapProps,
  MediaProps,
  MessageEvent,
  MetaProps,
  MeterProps,
  MouseEvent,
  Node,
  Numeric,
  ObjectProps,
  OlProps,
  OptgroupProps,
  OptionProps,
  OutputProps,
  Performance,
  PointerEvent,
  ProgressEvent,
  ProgressProps,
  Prop,
  QuoteProps,
  ReadonlyState,
  ReferrerPolicy,
  SVGElement,
  ScriptProps,
  SelectProps,
  SlotProps,
  SourceProps,
  State,
  StyleProps,
  SubmitEvent,
  SvgProps,
  TableProps,
  Target,
  TdProps,
  TextareaProps,
  ThProps,
  TimeProps,
  ToggleEvent,
  TouchEvent,
  TrackProps,
  TransitionEvent,
  UIEvent,
  VideoProps,
  VoidProps,
  WheelEvent,
  Window,
} from "@backtickjs/web-schema";

/**
 * Something the compiler had to say about what was written, and where in it.
 * The word the rest of this repository uses.
 */
export interface Diagnostic {
  readonly message: string;
  readonly start: number | null;
  readonly length: number | null;
}

/** The elements this schema declares, and what each accepts. */
export interface SiteElements {}

/** Every element in scope, this schema's own and its bases'. */
export interface Elements extends WebElements, SiteElements {}

/** What this schema declares, which is what its own client answers for. */
export interface SiteBuiltins {
  /**
   * Compiles Backtick source to a bundle. One of the two callbacks is called,
   * once. Callbacks rather than something to wait on, because waiting is not a
   * thing this language does.
   *
   * @param source What somebody wrote.
   * @param onBundle Called with the bundle, when there is one. Measuring it is
   * the caller's: a string knows its own length.
   * @param onDiagnostics Called instead, with what the compiler had to say.
   * Not an error: a half-written line answers this way, and the call did what
   * it was asked.
   */
  compile(
    source: string,
    onBundle: (bundle: string) => void,
    onDiagnostics: (diagnostics: Diagnostic[]) => void,
  ): void;
}

/** What a client must answer with, for every name in scope. */
export interface Builtins extends WebBuiltins, SiteBuiltins {}
