export type { SourceMapping } from "./buildMappings.js";
export type { CodeInformation } from "./CodeInformation.js";
export type { Diagnostic } from "./diagnostics.js";
export type { EmittedScript } from "./emitScript.js";
export type { CodeTransform } from "./applyTransform.js";
export { emitScripts, type EmittedScriptAt } from "./emitScripts.js";
export { flattenScripts } from "./flattenScripts.js";
export type { ClientScript, ParsedFile, Splice } from "./parseFile.js";
export { parseSourceFile, parseSourceText } from "./parseFile.js";
export { type ResolvedParam, resolveBindings } from "./resolveBindings.js";
export { transform } from "./transform.js";
export { transpile } from "./transpile.js";
export { mangle, unmangle } from "./unmangle.js";
export type { Virtualized } from "./virtualize.js";
export { virtualize } from "./virtualize.js";
