export type { SourceMapping } from "./buildMappings.js";
export type { CodeInformation } from "./CodeInformation.js";
export type { Diagnostic } from "./diagnostics.js";
export { flattenScripts } from "./flattenScripts.js";
export type { ClientScript, ParsedFile, Splice } from "./parseFile.js";
export { parseSourceFile, parseSourceText } from "./parseFile.js";
export { resolveBindings } from "./resolveBindings.js";
export { transform } from "./transform.js";
export { mangle, unmangle } from "./unmangle.js";
export type { Virtualized } from "./virtualize.js";
export { virtualize } from "./virtualize.js";
