// Generated by `pnpm generate`. Do not edit.

import { createBuiltin } from "./Builtin.js";
import type { Client } from "./Client.js";
import type { Http, State } from "./declarations.generated.js";

export const http: Client<Http> = createBuiltin("http");

export const state: Client<<T>(initial: T) => State<T>> =
  createBuiltin("state");
