// Generated by `pnpm generate`. Do not edit.

import { createBuiltin, type Client } from "@backtickjs/boundary";
import type { RequestInit, Response, State } from "./declarations.generated.js";

/**
 * The web's `fetch`, answering through handlers because a script has no
 * `await`.
 *
 * Exactly one handler is called, once. `init` is last so the optional argument
 * stays last.
 *
 * @param onFailure Called where nothing answered at all.
 */
export const fetch: Client<
  (
    input: string,
    onResponse: (response: Response) => void,
    onFailure: (reason: string) => void,
    init?: RequestInit,
  ) => void
> = createBuiltin("fetch");

export const state: Client<<T>(initial: T) => State<T>> =
  createBuiltin("state");
