// Generated by `pnpm generate`. Do not edit.

import type { ArrayLike, ClientValue } from "./declarations.generated.js";

export interface Boolean {
  /**
   * Returns the primitive value of the specified object.
   */
  valueOf(): boolean;
}

export interface Number {
  /**
   * Returns a string representation of an object.
   *
   * @param radix Specifies a radix for converting numeric values to strings.
   * This value is only used for numbers.
   */
  toString(radix?: number): string;
  /**
   * Returns a string representing a number in fixed-point notation.
   *
   * @param fractionDigits Number of digits after the decimal point. Must be in
   * the range 0 - 20, inclusive.
   */
  toFixed(fractionDigits?: number): string;
  /**
   * Returns a string containing a number represented in exponential notation.
   *
   * @param fractionDigits Number of digits after the decimal point. Must be in
   * the range 0 - 20, inclusive.
   */
  toExponential(fractionDigits?: number): string;
  /**
   * Returns a string containing a number represented either in exponential or
   * fixed-point notation with a specified number of digits.
   *
   * @param precision Number of significant digits. Must be in the range 1 -
   * 21, inclusive.
   */
  toPrecision(precision?: number): string;
  /**
   * Returns the primitive value of the specified object.
   */
  valueOf(): number;
}

export interface String {
  /**
   * Returns a string representation of a string.
   */
  toString(): string;
  /**
   * Returns the character at the specified index.
   *
   * @param pos The zero-based index of the desired character.
   */
  charAt(pos: number): string;
  /**
   * Returns the Unicode value of the character at the specified location.
   *
   * @param index The zero-based index of the desired character. If there is no
   * character at the specified index, NaN is returned.
   */
  charCodeAt(index: number): number;
  /**
   * Returns a string that contains the concatenation of two or more strings.
   *
   * @param strings The strings to append to the end of the string.
   */
  concat(...strings: string[]): string;
  /**
   * Returns the position of the first occurrence of a substring, or -1 if it
   * is not present.
   *
   * @param searchString The substring to search for in the string
   * @param position The index at which to begin searching the String object.
   * If omitted, search starts at the beginning of the string.
   */
  indexOf(searchString: string, position?: number): number;
  /**
   * Returns the last occurrence of a substring in the string, or -1 if it is
   * not present.
   *
   * @param searchString The substring to search for.
   * @param position The index at which to begin searching. If omitted, the
   * search begins at the end of the string.
   */
  lastIndexOf(searchString: string, position?: number): number;
  /**
   * Determines whether two strings are equivalent in the current locale.
   *
   * @param that String to compare to target string
   */
  localeCompare(that: string): number;
  /**
   * Replaces text in a string, using a search string.
   *
   * @param searchValue A string to search for.
   * @param replaceValue The text to replace it with, or a function answering
   * with that text. Only the first match of `searchValue` is replaced.
   */
  replace(
    searchValue: string,
    replaceValue:
      | string
      | ((substring: string, offset: number, string: string) => string),
  ): string;
  /**
   * Returns a section of a string.
   *
   * @param start The index to the beginning of the specified portion of
   * stringObj.
   * @param end The index to the end of the specified portion of stringObj. The
   * substring includes the characters up to, but not including, the character
   * indicated by end. If this value is not specified, the substring continues
   * to the end of stringObj.
   */
  slice(start?: number, end?: number): string;
  /**
   * Split a string into substrings using the specified separator and return
   * them as an array.
   *
   * @param separator A string that identifies character or characters to use
   * in separating the string. If omitted, a single-element array containing
   * the entire string is returned.
   * @param limit A value used to limit the number of elements returned in the
   * array.
   */
  split(separator: string, limit?: number): string[];
  /**
   * Returns the substring at the specified location within a String object.
   *
   * @param start The zero-based index number indicating the beginning of the
   * substring.
   * @param end Zero-based index number indicating the end of the substring.
   * The substring includes the characters up to, but not including, the
   * character indicated by end. If end is omitted, the characters from start
   * through the end of the original string are returned.
   */
  substring(start: number, end?: number): string;
  /**
   * Converts all the alphabetic characters in a string to lowercase.
   */
  toLowerCase(): string;
  /**
   * Converts all alphabetic characters to lowercase, taking into account the
   * host environment's current locale.
   */
  toLocaleLowerCase(locales?: string | string[]): string;
  /**
   * Converts all the alphabetic characters in a string to uppercase.
   */
  toUpperCase(): string;
  /**
   * Returns a string where all alphabetic characters have been converted to
   * uppercase, taking into account the host environment's current locale.
   */
  toLocaleUpperCase(locales?: string | string[]): string;
  /**
   * Removes the leading and trailing white space and line terminator
   * characters from a string.
   */
  trim(): string;
  /**
   * Returns the length of a String object.
   */
  readonly length: number;
  /**
   * Returns the primitive value of the specified object.
   */
  valueOf(): string;
  readonly [index: number]: string;
}

export interface Array<T> {
  /**
   * Gets the length of the array. This is a number one higher than the highest
   * index in the array.
   */
  readonly length: number;
  /**
   * Combines two or more arrays. This method returns a new array without
   * modifying any existing arrays.
   *
   * @param items Additional arrays and/or items to add to the end of the
   * array.
   */
  concat(...items: (T | readonly T[])[]): T[];
  /**
   * Adds all the elements of an array into a string, separated by the
   * specified separator string.
   *
   * @param separator A string used to separate one element of the array from
   * the next in the resulting string. If omitted, the array elements are
   * separated with a comma.
   */
  join(separator?: string): string;
  /**
   * Returns a copy of a section of an array.
   *
   * @param start The beginning index of the specified portion of the array. If
   * start is undefined, then the slice begins at index 0.
   * @param end The end index of the specified portion of the array. This is
   * exclusive of the element at the index 'end'. If end is undefined, then the
   * slice extends to the end of the array.
   */
  slice(start?: number, end?: number): T[];
  /**
   * Returns the index of the first occurrence of a value in an array, or -1 if
   * it is not present.
   *
   * @param searchElement The value to locate in the array.
   * @param fromIndex The array index at which to begin the search. If
   * fromIndex is omitted, the search starts at index 0.
   */
  indexOf(searchElement: T, fromIndex?: number): number;
  /**
   * Determines whether an array includes a certain element, returning true or
   * false as appropriate.
   *
   * @param searchElement The element to search for.
   * @param fromIndex The position in this array at which to begin searching
   * for searchElement.
   */
  includes(searchElement: T, fromIndex?: number): boolean;
  /**
   * Calls a defined callback function on each element of an array, and returns
   * an array that contains the results.
   *
   * @param callbackfn A function that accepts up to two arguments. The map
   * method calls the callbackfn function one time for each element in the
   * array.
   */
  map<U>(callbackfn: (value: T, index: number) => U): U[];
  /**
   * Calls the specified callback function for all the elements in an array.
   * The return value of the callback function is the accumulated result, and
   * is provided as an argument in the next call to the callback function.
   *
   * The initial value is required, where the standard library makes it
   * optional: without one the first call is handed an element rather than an
   * accumulator, and an empty array has nothing to hand it and throws. Both
   * are rules a host would have to reproduce exactly to agree, and naming the
   * starting value is the same work.
   *
   * @param callbackfn A function that accepts up to three arguments. The
   * reduce method calls the callbackfn function one time for each element in
   * the array.
   * @param initialValue It is used as the initial value to start the
   * accumulation. The first call to the callbackfn function provides this
   * value as an argument instead of an array value.
   */
  reduce<U>(
    callbackfn: (previousValue: U, currentValue: T, currentIndex: number) => U,
    initialValue: U,
  ): U;
  /**
   * Returns the elements of an array that meet the condition specified in a
   * callback function.
   *
   * @param predicate A function that accepts up to two arguments. The filter
   * method calls the predicate function one time for each element in the
   * array.
   */
  filter(predicate: (value: T, index: number) => boolean): T[];
  /**
   * Copies an array, then overwrites the value at the provided index with the
   * given value. If the index is negative, then it replaces from the end of
   * the array.
   *
   * @param index The index of the value to overwrite. If the index is
   * negative, then it replaces from the end of the array.
   * @param value The value to write into the copied array.
   */
  with(index: number, value: T): T[];
  /**
   * Returns a copy of an array with its elements sorted.
   *
   * The comparator is required, where the standard library makes it optional:
   * sorting without one compares the elements as strings, which is a rule of
   * JavaScript's rather than of this language, and every other host would have
   * to reproduce it to agree. Saying how to order two elements is the same
   * work and it ports.
   *
   * @param compareFn Function used to determine the order of the elements. It
   * is expected to return a negative value if the first argument is less than
   * the second argument, zero if they're equal, and a positive value
   * otherwise.
   */
  toSorted(compareFn: (a: T, b: T) => number): T[];
  /**
   * Returns a copy of an array with its elements in reverse order.
   */
  toReversed(): T[];
  /**
   * Copies an array and removes elements while, if necessary, inserting new
   * elements in their place, returning the remaining elements.
   *
   * @param start The zero-based location in the array from which to start
   * removing elements.
   * @param deleteCount The number of elements to remove.
   * @param items Elements to insert into the copied array in place of the
   * deleted elements.
   */
  toSpliced(start: number, deleteCount: number, ...items: T[]): T[];
  readonly [index: number]: T;
}

export interface JSON {
  /**
   * Converts a JSON string into the value it describes. Throws if the text is
   * not JSON.
   *
   * @param text A valid JSON string.
   */
  parse(text: string): any;
  /**
   * Converts a value to the JSON string that describes it.
   *
   * @param value A value to convert.
   */
  stringify(value: ClientValue): string;
}

export interface Math {
  /**
   * The mathematical constant e. This is Euler's number, the base of natural
   * logarithms.
   */
  readonly E: number;
  /**
   * The natural logarithm of 10.
   */
  readonly LN10: number;
  /**
   * The natural logarithm of 2.
   */
  readonly LN2: number;
  /**
   * The base-2 logarithm of e.
   */
  readonly LOG2E: number;
  /**
   * The base-10 logarithm of e.
   */
  readonly LOG10E: number;
  /**
   * Pi. This is the ratio of the circumference of a circle to its diameter.
   */
  readonly PI: number;
  /**
   * The square root of 0.5, or, equivalently, one divided by the square root
   * of 2.
   */
  readonly SQRT1_2: number;
  /**
   * The square root of 2.
   */
  readonly SQRT2: number;
  /**
   * Returns the absolute value of a number (the value without regard to
   * whether it is positive or negative). For example, the absolute value of -5
   * is the same as the absolute value of 5.
   *
   * @param x A numeric expression for which the absolute value is needed.
   */
  abs(x: number): number;
  /**
   * Returns the arc cosine (or inverse cosine) of a number.
   *
   * @param x A numeric expression.
   */
  acos(x: number): number;
  /**
   * Returns the arcsine of a number.
   *
   * @param x A numeric expression.
   */
  asin(x: number): number;
  /**
   * Returns the arctangent of a number.
   *
   * @param x A numeric expression for which the arctangent is needed.
   */
  atan(x: number): number;
  /**
   * Returns the angle (in radians) between the X axis and the line going
   * through both the origin and the given point.
   *
   * @param y A numeric expression representing the cartesian y-coordinate.
   * @param x A numeric expression representing the cartesian x-coordinate.
   */
  atan2(y: number, x: number): number;
  /**
   * Returns the smallest integer greater than or equal to its numeric
   * argument.
   *
   * @param x A numeric expression.
   */
  ceil(x: number): number;
  /**
   * Returns the cosine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  cos(x: number): number;
  /**
   * Returns e (the base of natural logarithms) raised to a power.
   *
   * @param x A numeric expression representing the power of e.
   */
  exp(x: number): number;
  /**
   * Returns the greatest integer less than or equal to its numeric argument.
   *
   * @param x A numeric expression.
   */
  floor(x: number): number;
  /**
   * Returns the natural logarithm (base e) of a number.
   *
   * @param x A numeric expression.
   */
  log(x: number): number;
  /**
   * Returns the larger of a set of supplied numeric expressions.
   *
   * Calling this with no arguments is a client error rather than an answer:
   * the standard library takes none and answers `-Infinity`, which is not a
   * value this language has.
   *
   * @param values Numeric expressions to be evaluated.
   */
  max(...values: number[]): number;
  /**
   * Returns the smaller of a set of supplied numeric expressions.
   *
   * Calling this with no arguments is a client error rather than an answer:
   * the standard library takes none and answers `Infinity`, which is not a
   * value this language has.
   *
   * @param values Numeric expressions to be evaluated.
   */
  min(...values: number[]): number;
  /**
   * Returns the value of a base expression taken to a specified power.
   *
   * @param x The base value of the expression.
   * @param y The exponent value of the expression.
   */
  pow(x: number, y: number): number;
  /**
   * Returns a pseudorandom number between 0 and 1.
   */
  random(): number;
  /**
   * Returns a supplied numeric expression rounded to the nearest integer.
   *
   * @param x The value to be rounded to the nearest integer.
   */
  round(x: number): number;
  /**
   * Returns the sine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  sin(x: number): number;
  /**
   * Returns the square root of a number.
   *
   * @param x A numeric expression.
   */
  sqrt(x: number): number;
  /**
   * Returns the tangent of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  tan(x: number): number;
  /**
   * Returns the number of leading zero bits in the 32-bit binary
   * representation of a number.
   *
   * @param x A numeric expression.
   */
  clz32(x: number): number;
  /**
   * Returns the result of 32-bit multiplication of two numbers.
   *
   * @param x First number
   * @param y Second number
   */
  imul(x: number, y: number): number;
  /**
   * Returns the sign of the x, indicating whether x is positive, negative or
   * zero.
   *
   * @param x The numeric expression to test
   */
  sign(x: number): number;
  /**
   * Returns the base 10 logarithm of a number.
   *
   * @param x A numeric expression.
   */
  log10(x: number): number;
  /**
   * Returns the base 2 logarithm of a number.
   *
   * @param x A numeric expression.
   */
  log2(x: number): number;
  /**
   * Returns the natural logarithm of 1 + x.
   *
   * @param x A numeric expression.
   */
  log1p(x: number): number;
  /**
   * Returns the result of (e^x - 1), which is an implementation-dependent
   * approximation to subtracting 1 from the exponential function of x (e
   * raised to the power of x, where e is the base of the natural logarithms).
   *
   * @param x A numeric expression.
   */
  expm1(x: number): number;
  /**
   * Returns the hyperbolic cosine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  cosh(x: number): number;
  /**
   * Returns the hyperbolic sine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  sinh(x: number): number;
  /**
   * Returns the hyperbolic tangent of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  tanh(x: number): number;
  /**
   * Returns the inverse hyperbolic cosine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  acosh(x: number): number;
  /**
   * Returns the inverse hyperbolic sine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  asinh(x: number): number;
  /**
   * Returns the inverse hyperbolic tangent of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  atanh(x: number): number;
  /**
   * Returns the square root of the sum of squares of its arguments.
   *
   * @param values Values to compute the square root for. If no arguments are
   * passed, the result is +0. If there is only one argument, the result is the
   * absolute value. If any argument is +Infinity or -Infinity, the result is
   * +Infinity. If any argument is NaN, the result is NaN. If all arguments are
   * either +0 or −0, the result is +0.
   */
  hypot(...values: number[]): number;
  /**
   * Returns the integral part of the numeric expression x, removing any
   * fractional digits. If x is already an integer, the result is x.
   *
   * @param x A numeric expression.
   */
  trunc(x: number): number;
  /**
   * Returns the nearest single precision float representation of a number.
   *
   * @param x A numeric expression.
   */
  fround(x: number): number;
  /**
   * Returns an implementation-dependent approximation to the cube root of
   * number.
   *
   * @param x A numeric expression.
   */
  cbrt(x: number): number;
}

export interface ArrayConstructor {
  /**
   * Creates an array from an array-like object.
   *
   * The mapper is required, where the standard library makes it optional:
   * without one, a source that names only a length answers with holes, and a
   * hole reads as `undefined` — which this language has no value for.
   *
   * @param arrayLike An array-like object to convert to an array.
   * @param mapfn A mapping function to call on every element of the array.
   */
  from<T extends ClientValue, U extends ClientValue>(
    arrayLike: ArrayLike<T>,
    mapfn: (v: T, k: number) => U,
  ): U[];
  /**
   * Returns a new array from a set of elements.
   *
   * @param items A set of elements to include in the new array object.
   */
  of<T extends ClientValue>(...items: T[]): T[];
}

export interface NumberConstructor {
  /**
   * The value of Number.EPSILON is the difference between 1 and the smallest
   * value greater than 1 that is representable as a Number value, which is
   * approximately: 2.2204460492503130808472633361816 x 10−16.
   */
  readonly EPSILON: number;
  /**
   * Returns true if passed value is finite. Unlike the global isFinite,
   * Number.isFinite doesn't forcibly convert the parameter to a number. Only
   * finite values of the type number, result in true.
   *
   * @param number A numeric value.
   */
  isFinite(number: ClientValue): boolean;
  /**
   * Returns true if the value passed is an integer, false otherwise.
   *
   * @param number A numeric value.
   */
  isInteger(number: ClientValue): boolean;
  /**
   * Converts a string to a floating-point number.
   *
   * @param string A string that contains a floating-point number.
   */
  parseFloat(string: string): number;
  /**
   * Converts A string to an integer.
   *
   * @param string A string to convert into a number.
   * @param radix A value between 2 and 36 that specifies the base of the
   * number in `string`. If this argument is not supplied, strings with a
   * prefix of '0x' are considered hexadecimal. All other strings are
   * considered decimal.
   */
  parseInt(string: string, radix?: number): number;
}

export interface ObjectConstructor {
  /**
   * Returns an array of an object's members, each as a key and its value, in
   * the order `JSON.stringify` writes them.
   *
   * @param o An object whose members to list.
   */
  entries<T extends ClientValue>(o: {
    readonly [key: string]: T;
  }): [key: string, value: T][];
  /**
   * Returns an object holding each key with its value. A key written twice
   * holds the later value.
   *
   * @param entries Keys and their values.
   */
  fromEntries<T extends ClientValue>(
    entries: readonly [key: string, value: T][],
  ): { [key: string]: T };
}

export interface StringConstructor {
  /**
   * Return the String value whose elements are, in order, the elements in the
   * List elements. If length is 0, the empty string is returned.
   */
  fromCodePoint(...codePoints: number[]): string;
}
