// Generated by `pnpm generate`. Do not edit.

import { createBuiltin } from "@backtickjs/ui-schema";
import type {
  Client,
  Console,
  Event,
  EventTarget,
  Performance,
} from "./declarations.generated.js";

/**
 * The clock, for measuring how long something took.
 */
export const performance: Client<Performance> = createBuiltin("performance");

/**
 * Somewhere to say something while writing a script.
 */
export const console: Client<Console> = createBuiltin("console");

/**
 * Listens for an event nothing drawn here is the target of — a key pressed
 * anywhere, a message arriving. What an element's own events are is a prop on
 * that element, and this is the rest.
 *
 * @param type Which event to listen for, named as the DOM names it.
 */
export const addEventListener: Client<
  (type: string, listener: (event: Event<EventTarget>) => void) => void
> = createBuiltin("addEventListener");

/**
 * Stops listening. The listener has to be the same one that was handed to
 * `addEventListener` — the DOM matches by identity, so a second closure that
 * does the same thing removes nothing.
 *
 * @param type Which event to listen for, named as the DOM names it.
 */
export const removeEventListener: Client<
  (type: string, listener: (event: Event<EventTarget>) => void) => void
> = createBuiltin("removeEventListener");
