// Generated by `pnpm generate`. Do not edit.

import type {
  Builtins as UiBuiltins,
  Children,
  ClientElement,
  Elements as UiElements,
  Prop,
} from "@backtickjs/ui-schema";

export type {
  ArrayLike,
  Children,
  Client,
  ClientElement,
  ClientFunction,
  ClientHandle,
  ClientUnknown,
  ClientValue,
  ForProps,
  Prop,
  ReadonlyState,
  State,
} from "@backtickjs/ui-schema";

export type HtmlNode = ClientElement | string | number | null;

export type Booleanish = boolean | "true" | "false";

export type Numeric = number | string;

export type AriaRole =
  | "alert"
  | "alertdialog"
  | "application"
  | "article"
  | "banner"
  | "button"
  | "cell"
  | "checkbox"
  | "columnheader"
  | "combobox"
  | "complementary"
  | "contentinfo"
  | "definition"
  | "dialog"
  | "directory"
  | "document"
  | "feed"
  | "figure"
  | "form"
  | "grid"
  | "gridcell"
  | "group"
  | "heading"
  | "img"
  | "link"
  | "list"
  | "listbox"
  | "listitem"
  | "log"
  | "main"
  | "marquee"
  | "math"
  | "menu"
  | "menubar"
  | "menuitem"
  | "menuitemcheckbox"
  | "menuitemradio"
  | "navigation"
  | "none"
  | "note"
  | "option"
  | "presentation"
  | "progressbar"
  | "radio"
  | "radiogroup"
  | "region"
  | "row"
  | "rowgroup"
  | "rowheader"
  | "scrollbar"
  | "search"
  | "searchbox"
  | "separator"
  | "slider"
  | "spinbutton"
  | "status"
  | "switch"
  | "tab"
  | "table"
  | "tablist"
  | "tabpanel"
  | "term"
  | "textbox"
  | "timer"
  | "toolbar"
  | "tooltip"
  | "tree"
  | "treegrid"
  | "treeitem";

export type ReferrerPolicy =
  | ""
  | "no-referrer"
  | "no-referrer-when-downgrade"
  | "origin"
  | "origin-when-cross-origin"
  | "same-origin"
  | "strict-origin"
  | "strict-origin-when-cross-origin"
  | "unsafe-url";

export type CrossOrigin = "anonymous" | "use-credentials" | "";

export type Target = "_self" | "_blank" | "_parent" | "_top";

export interface AriaAttributes {
  "aria-activedescendant"?: Prop<string>;
  "aria-atomic"?: Prop<Booleanish>;
  "aria-autocomplete"?: Prop<"none" | "inline" | "list" | "both">;
  "aria-braillelabel"?: Prop<string>;
  "aria-brailleroledescription"?: Prop<string>;
  "aria-busy"?: Prop<Booleanish>;
  "aria-checked"?: Prop<boolean | "false" | "mixed" | "true">;
  "aria-colcount"?: Prop<number>;
  "aria-colindex"?: Prop<number>;
  "aria-colindextext"?: Prop<string>;
  "aria-colspan"?: Prop<number>;
  "aria-controls"?: Prop<string>;
  "aria-current"?: Prop<
    boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time"
  >;
  "aria-describedby"?: Prop<string>;
  "aria-description"?: Prop<string>;
  "aria-details"?: Prop<string>;
  "aria-disabled"?: Prop<Booleanish>;
  "aria-errormessage"?: Prop<string>;
  "aria-expanded"?: Prop<Booleanish>;
  "aria-flowto"?: Prop<string>;
  "aria-haspopup"?: Prop<
    boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog"
  >;
  "aria-hidden"?: Prop<Booleanish>;
  "aria-invalid"?: Prop<boolean | "false" | "true" | "grammar" | "spelling">;
  "aria-keyshortcuts"?: Prop<string>;
  "aria-label"?: Prop<string>;
  "aria-labelledby"?: Prop<string>;
  "aria-level"?: Prop<number>;
  "aria-live"?: Prop<"off" | "assertive" | "polite">;
  "aria-modal"?: Prop<Booleanish>;
  "aria-multiline"?: Prop<Booleanish>;
  "aria-multiselectable"?: Prop<Booleanish>;
  "aria-orientation"?: Prop<"horizontal" | "vertical">;
  "aria-owns"?: Prop<string>;
  "aria-placeholder"?: Prop<string>;
  "aria-posinset"?: Prop<number>;
  "aria-pressed"?: Prop<boolean | "false" | "mixed" | "true">;
  "aria-readonly"?: Prop<Booleanish>;
  "aria-relevant"?: Prop<
    | "additions"
    | "additions removals"
    | "additions text"
    | "all"
    | "removals"
    | "removals additions"
    | "removals text"
    | "text"
    | "text additions"
    | "text removals"
  >;
  "aria-required"?: Prop<Booleanish>;
  "aria-roledescription"?: Prop<string>;
  "aria-rowcount"?: Prop<number>;
  "aria-rowindex"?: Prop<number>;
  "aria-rowindextext"?: Prop<string>;
  "aria-rowspan"?: Prop<number>;
  "aria-selected"?: Prop<Booleanish>;
  "aria-setsize"?: Prop<number>;
  "aria-sort"?: Prop<"none" | "ascending" | "descending" | "other">;
  "aria-valuemax"?: Prop<number>;
  "aria-valuemin"?: Prop<number>;
  "aria-valuenow"?: Prop<number>;
  "aria-valuetext"?: Prop<string>;
}

export interface Events {
  oncopy?: Prop<() => void>;
  oncut?: Prop<() => void>;
  onpaste?: Prop<() => void>;
  oncompositionend?: Prop<() => void>;
  oncompositionstart?: Prop<() => void>;
  oncompositionupdate?: Prop<() => void>;
  onblur?: Prop<() => void>;
  onfocus?: Prop<() => void>;
  onfocusin?: Prop<() => void>;
  onfocusout?: Prop<() => void>;
  onbeforeinput?: Prop<() => void>;
  onchange?: Prop<() => void>;
  oninput?: Prop<() => void>;
  oninvalid?: Prop<() => void>;
  onreset?: Prop<() => void>;
  onselect?: Prop<() => void>;
  onsubmit?: Prop<() => void>;
  onerror?: Prop<() => void>;
  onload?: Prop<() => void>;
  onkeydown?: Prop<() => void>;
  onkeypress?: Prop<() => void>;
  onkeyup?: Prop<() => void>;
  onabort?: Prop<() => void>;
  oncanplay?: Prop<() => void>;
  oncanplaythrough?: Prop<() => void>;
  ondurationchange?: Prop<() => void>;
  onemptied?: Prop<() => void>;
  onended?: Prop<() => void>;
  onloadeddata?: Prop<() => void>;
  onloadedmetadata?: Prop<() => void>;
  onloadstart?: Prop<() => void>;
  onpause?: Prop<() => void>;
  onplay?: Prop<() => void>;
  onplaying?: Prop<() => void>;
  onprogress?: Prop<() => void>;
  onratechange?: Prop<() => void>;
  onseeked?: Prop<() => void>;
  onseeking?: Prop<() => void>;
  onstalled?: Prop<() => void>;
  onsuspend?: Prop<() => void>;
  ontimeupdate?: Prop<() => void>;
  onvolumechange?: Prop<() => void>;
  onwaiting?: Prop<() => void>;
  onauxclick?: Prop<() => void>;
  onclick?: Prop<() => void>;
  oncontextmenu?: Prop<() => void>;
  ondblclick?: Prop<() => void>;
  onmousedown?: Prop<() => void>;
  onmouseenter?: Prop<() => void>;
  onmouseleave?: Prop<() => void>;
  onmousemove?: Prop<() => void>;
  onmouseout?: Prop<() => void>;
  onmouseover?: Prop<() => void>;
  onmouseup?: Prop<() => void>;
  ondrag?: Prop<() => void>;
  ondragend?: Prop<() => void>;
  ondragenter?: Prop<() => void>;
  ondragleave?: Prop<() => void>;
  ondragover?: Prop<() => void>;
  ondragstart?: Prop<() => void>;
  ondrop?: Prop<() => void>;
  ontouchcancel?: Prop<() => void>;
  ontouchend?: Prop<() => void>;
  ontouchmove?: Prop<() => void>;
  ontouchstart?: Prop<() => void>;
  ongotpointercapture?: Prop<() => void>;
  onlostpointercapture?: Prop<() => void>;
  onpointercancel?: Prop<() => void>;
  onpointerdown?: Prop<() => void>;
  onpointerenter?: Prop<() => void>;
  onpointerleave?: Prop<() => void>;
  onpointermove?: Prop<() => void>;
  onpointerout?: Prop<() => void>;
  onpointerover?: Prop<() => void>;
  onpointerup?: Prop<() => void>;
  onscroll?: Prop<() => void>;
  onscrollend?: Prop<() => void>;
  onwheel?: Prop<() => void>;
  onanimationend?: Prop<() => void>;
  onanimationiteration?: Prop<() => void>;
  onanimationstart?: Prop<() => void>;
  ontransitioncancel?: Prop<() => void>;
  ontransitionend?: Prop<() => void>;
  ontransitionrun?: Prop<() => void>;
  ontransitionstart?: Prop<() => void>;
  onbeforetoggle?: Prop<() => void>;
  ontoggle?: Prop<() => void>;
}

export interface GlobalAttributes extends AriaAttributes, Events {
  accesskey?: Prop<string>;
  autocapitalize?: Prop<
    "off" | "none" | "on" | "sentences" | "words" | "characters"
  >;
  autocorrect?: Prop<"on" | "off">;
  autofocus?: Prop<boolean>;
  class?: Prop<string>;
  contenteditable?: Prop<Booleanish | "inherit" | "plaintext-only">;
  dir?: Prop<"ltr" | "rtl" | "auto">;
  draggable?: Prop<Booleanish>;
  enterkeyhint?: Prop<
    "enter" | "done" | "go" | "next" | "previous" | "search" | "send"
  >;
  exportparts?: Prop<string>;
  hidden?: Prop<boolean | "until-found">;
  id?: Prop<string>;
  inert?: Prop<boolean>;
  inputmode?: Prop<
    "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search"
  >;
  is?: Prop<string>;
  itemid?: Prop<string>;
  itemprop?: Prop<string>;
  itemref?: Prop<string>;
  itemscope?: Prop<boolean>;
  itemtype?: Prop<string>;
  lang?: Prop<string>;
  nonce?: Prop<string>;
  part?: Prop<string>;
  popover?: Prop<"" | "auto" | "manual" | "hint">;
  role?: Prop<AriaRole>;
  xmlns?: Prop<string>;
  slot?: Prop<string>;
  spellcheck?: Prop<Booleanish>;
  style?: Prop<string>;
  tabindex?: Prop<number>;
  title?: Prop<string>;
  translate?: Prop<"yes" | "no">;
}

export interface VoidProps extends GlobalAttributes {}

export interface HtmlProps extends GlobalAttributes {
  children?: Children<HtmlNode>;
}

export interface AnchorProps extends HtmlProps {
  download?: Prop<string | boolean>;
  href?: Prop<string>;
  hreflang?: Prop<string>;
  media?: Prop<string>;
  ping?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  rel?: Prop<string>;
  target?: Prop<Target>;
  type?: Prop<string>;
}

export interface AreaProps extends VoidProps {
  alt?: Prop<string>;
  coords?: Prop<string>;
  download?: Prop<string | boolean>;
  href?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  rel?: Prop<string>;
  shape?: Prop<"rect" | "circle" | "poly" | "default">;
  target?: Prop<Target>;
}

export interface BaseProps extends VoidProps {
  href?: Prop<string>;
  target?: Prop<Target>;
}

export interface BlockquoteProps extends HtmlProps {
  cite?: Prop<string>;
}

export interface ButtonProps extends HtmlProps {
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  formaction?: Prop<string>;
  formenctype?: Prop<string>;
  formmethod?: Prop<"get" | "post" | "dialog">;
  formnovalidate?: Prop<boolean>;
  formtarget?: Prop<Target>;
  name?: Prop<string>;
  popovertarget?: Prop<string>;
  popovertargetaction?: Prop<"toggle" | "show" | "hide">;
  type?: Prop<"submit" | "reset" | "button">;
  value?: Prop<string | number>;
}

export interface CanvasProps extends HtmlProps {
  height?: Prop<Numeric>;
  width?: Prop<Numeric>;
}

export interface ColProps extends VoidProps {
  span?: Prop<number>;
  width?: Prop<Numeric>;
}

export interface ColgroupProps extends HtmlProps {
  span?: Prop<number>;
}

export interface DataProps extends HtmlProps {
  value?: Prop<string | number>;
}

export interface DelProps extends HtmlProps {
  cite?: Prop<string>;
  datetime?: Prop<string>;
}

export interface DetailsProps extends HtmlProps {
  name?: Prop<string>;
  open?: Prop<boolean>;
}

export interface DialogProps extends HtmlProps {
  closedby?: Prop<"any" | "closerequest" | "none">;
  open?: Prop<boolean>;
}

export interface EmbedProps extends VoidProps {
  height?: Prop<Numeric>;
  src?: Prop<string>;
  type?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface FieldsetProps extends HtmlProps {
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  name?: Prop<string>;
}

export interface FormProps extends HtmlProps {
  "accept-charset"?: Prop<string>;
  action?: Prop<string>;
  autocomplete?: Prop<"on" | "off">;
  enctype?: Prop<string>;
  method?: Prop<"get" | "post" | "dialog">;
  name?: Prop<string>;
  novalidate?: Prop<boolean>;
  rel?: Prop<string>;
  target?: Prop<Target>;
}

export interface HtmlElementProps extends HtmlProps {
  manifest?: Prop<string>;
}

export interface IframeProps extends HtmlProps {
  allow?: Prop<string>;
  allowfullscreen?: Prop<boolean>;
  height?: Prop<Numeric>;
  loading?: Prop<"eager" | "lazy">;
  name?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  sandbox?: Prop<string>;
  src?: Prop<string>;
  srcdoc?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface ImgProps extends VoidProps {
  alt?: Prop<string>;
  crossorigin?: Prop<CrossOrigin>;
  decoding?: Prop<"async" | "auto" | "sync">;
  fetchpriority?: Prop<"high" | "low" | "auto">;
  height?: Prop<Numeric>;
  loading?: Prop<"eager" | "lazy">;
  referrerpolicy?: Prop<ReferrerPolicy>;
  sizes?: Prop<string>;
  src?: Prop<string>;
  srcset?: Prop<string>;
  usemap?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface InputProps extends VoidProps {
  accept?: Prop<string>;
  alt?: Prop<string>;
  autocomplete?: Prop<string>;
  capture?: Prop<boolean | "user" | "environment">;
  checked?: Prop<boolean>;
  dirname?: Prop<string>;
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  formaction?: Prop<string>;
  formenctype?: Prop<string>;
  formmethod?: Prop<"get" | "post" | "dialog">;
  formnovalidate?: Prop<boolean>;
  formtarget?: Prop<Target>;
  height?: Prop<Numeric>;
  list?: Prop<string>;
  max?: Prop<Numeric>;
  maxlength?: Prop<number>;
  min?: Prop<Numeric>;
  minlength?: Prop<number>;
  multiple?: Prop<boolean>;
  name?: Prop<string>;
  pattern?: Prop<string>;
  placeholder?: Prop<string>;
  readonly?: Prop<boolean>;
  required?: Prop<boolean>;
  size?: Prop<number>;
  src?: Prop<string>;
  step?: Prop<Numeric>;
  type?: Prop<
    | "button"
    | "checkbox"
    | "color"
    | "date"
    | "datetime-local"
    | "email"
    | "file"
    | "hidden"
    | "image"
    | "month"
    | "number"
    | "password"
    | "radio"
    | "range"
    | "reset"
    | "search"
    | "submit"
    | "tel"
    | "text"
    | "time"
    | "url"
    | "week"
  >;
  value?: Prop<string | number>;
  width?: Prop<Numeric>;
}

export interface InsProps extends HtmlProps {
  cite?: Prop<string>;
  datetime?: Prop<string>;
}

export interface LabelProps extends HtmlProps {
  for?: Prop<string>;
  form?: Prop<string>;
}

export interface LiProps extends HtmlProps {
  value?: Prop<number>;
}

export interface LinkProps extends VoidProps {
  as?: Prop<string>;
  crossorigin?: Prop<CrossOrigin>;
  fetchpriority?: Prop<"high" | "low" | "auto">;
  href?: Prop<string>;
  hreflang?: Prop<string>;
  imagesizes?: Prop<string>;
  imagesrcset?: Prop<string>;
  integrity?: Prop<string>;
  media?: Prop<string>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  rel?: Prop<string>;
  sizes?: Prop<string>;
  type?: Prop<string>;
}

export interface MapProps extends HtmlProps {
  name?: Prop<string>;
}

export interface MediaProps extends HtmlProps {
  autoplay?: Prop<boolean>;
  controls?: Prop<boolean>;
  controlslist?: Prop<string>;
  crossorigin?: Prop<CrossOrigin>;
  loop?: Prop<boolean>;
  muted?: Prop<boolean>;
  preload?: Prop<"none" | "metadata" | "auto" | "">;
  src?: Prop<string>;
}

export interface MetaProps extends VoidProps {
  charset?: Prop<string>;
  content?: Prop<string>;
  "http-equiv"?: Prop<string>;
  media?: Prop<string>;
  name?: Prop<string>;
}

export interface MeterProps extends HtmlProps {
  form?: Prop<string>;
  high?: Prop<number>;
  low?: Prop<number>;
  max?: Prop<Numeric>;
  min?: Prop<Numeric>;
  optimum?: Prop<number>;
  value?: Prop<string | number>;
}

export interface ObjectProps extends HtmlProps {
  data?: Prop<string>;
  form?: Prop<string>;
  height?: Prop<Numeric>;
  name?: Prop<string>;
  type?: Prop<string>;
  usemap?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface OlProps extends HtmlProps {
  reversed?: Prop<boolean>;
  start?: Prop<number>;
  type?: Prop<"1" | "a" | "A" | "i" | "I">;
}

export interface OptgroupProps extends HtmlProps {
  disabled?: Prop<boolean>;
  label?: Prop<string>;
}

export interface OptionProps extends HtmlProps {
  disabled?: Prop<boolean>;
  label?: Prop<string>;
  selected?: Prop<boolean>;
  value?: Prop<string | number>;
}

export interface OutputProps extends HtmlProps {
  for?: Prop<string>;
  form?: Prop<string>;
  name?: Prop<string>;
}

export interface ProgressProps extends HtmlProps {
  max?: Prop<Numeric>;
  value?: Prop<string | number>;
}

export interface QuoteProps extends HtmlProps {
  cite?: Prop<string>;
}

export interface ScriptProps extends HtmlProps {
  async?: Prop<boolean>;
  crossorigin?: Prop<CrossOrigin>;
  defer?: Prop<boolean>;
  fetchpriority?: Prop<"high" | "low" | "auto">;
  integrity?: Prop<string>;
  nomodule?: Prop<boolean>;
  referrerpolicy?: Prop<ReferrerPolicy>;
  src?: Prop<string>;
  type?: Prop<string>;
}

export interface SelectProps extends HtmlProps {
  autocomplete?: Prop<string>;
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  multiple?: Prop<boolean>;
  name?: Prop<string>;
  required?: Prop<boolean>;
  size?: Prop<number>;
  value?: Prop<string | number>;
}

export interface SlotProps extends HtmlProps {
  name?: Prop<string>;
}

export interface SourceProps extends VoidProps {
  height?: Prop<Numeric>;
  media?: Prop<string>;
  sizes?: Prop<string>;
  src?: Prop<string>;
  srcset?: Prop<string>;
  type?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface StyleProps extends HtmlProps {
  media?: Prop<string>;
  type?: Prop<string>;
}

export interface TableProps extends HtmlProps {
  summary?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface TdProps extends HtmlProps {
  colspan?: Prop<number>;
  headers?: Prop<string>;
  rowspan?: Prop<number>;
}

export interface ThProps extends HtmlProps {
  abbr?: Prop<string>;
  colspan?: Prop<number>;
  headers?: Prop<string>;
  rowspan?: Prop<number>;
  scope?: Prop<"row" | "col" | "rowgroup" | "colgroup">;
}

export interface TextareaProps extends HtmlProps {
  autocomplete?: Prop<string>;
  cols?: Prop<number>;
  dirname?: Prop<string>;
  disabled?: Prop<boolean>;
  form?: Prop<string>;
  maxlength?: Prop<number>;
  minlength?: Prop<number>;
  name?: Prop<string>;
  placeholder?: Prop<string>;
  readonly?: Prop<boolean>;
  required?: Prop<boolean>;
  rows?: Prop<number>;
  value?: Prop<string | number>;
  wrap?: Prop<"hard" | "soft" | "off">;
}

export interface TimeProps extends HtmlProps {
  datetime?: Prop<string>;
}

export interface TrackProps extends VoidProps {
  default?: Prop<boolean>;
  kind?: Prop<
    "subtitles" | "captions" | "descriptions" | "chapters" | "metadata"
  >;
  label?: Prop<string>;
  src?: Prop<string>;
  srclang?: Prop<string>;
}

export interface VideoProps extends MediaProps {
  disablepictureinpicture?: Prop<boolean>;
  disableremoteplayback?: Prop<boolean>;
  height?: Prop<Numeric>;
  playsinline?: Prop<boolean>;
  poster?: Prop<string>;
  width?: Prop<Numeric>;
}

export interface SvgProps extends AriaAttributes, Events {
  children?: Children<HtmlNode>;
  id?: Prop<string>;
  class?: Prop<string>;
  style?: Prop<string>;
  lang?: Prop<string>;
  tabindex?: Prop<number>;
  role?: Prop<AriaRole>;
  xmlns?: Prop<string>;
  accentHeight?: Prop<Numeric>;
  accumulate?: Prop<string>;
  additive?: Prop<string>;
  "alignment-baseline"?: Prop<string>;
  allowReorder?: Prop<string>;
  alphabetic?: Prop<Numeric>;
  amplitude?: Prop<Numeric>;
  arabicForm?: Prop<string>;
  ascent?: Prop<Numeric>;
  attributeName?: Prop<string>;
  attributeType?: Prop<string>;
  autoReverse?: Prop<Booleanish>;
  azimuth?: Prop<Numeric>;
  baseFrequency?: Prop<Numeric>;
  baseProfile?: Prop<Numeric>;
  "baseline-shift"?: Prop<Numeric>;
  bbox?: Prop<Numeric>;
  begin?: Prop<Numeric>;
  bias?: Prop<Numeric>;
  by?: Prop<Numeric>;
  calcMode?: Prop<Numeric>;
  capHeight?: Prop<Numeric>;
  clip?: Prop<Numeric>;
  "clip-path"?: Prop<string>;
  clipPathUnits?: Prop<Numeric>;
  "clip-rule"?: Prop<Numeric>;
  color?: Prop<string>;
  "color-interpolation"?: Prop<Numeric>;
  "color-interpolation-filters"?: Prop<string>;
  "color-profile"?: Prop<Numeric>;
  "color-rendering"?: Prop<Numeric>;
  contentScriptType?: Prop<Numeric>;
  contentStyleType?: Prop<Numeric>;
  crossOrigin?: Prop<string>;
  cursor?: Prop<Numeric>;
  cx?: Prop<Numeric>;
  cy?: Prop<Numeric>;
  d?: Prop<string>;
  decelerate?: Prop<Numeric>;
  descent?: Prop<Numeric>;
  diffuseConstant?: Prop<Numeric>;
  direction?: Prop<Numeric>;
  display?: Prop<Numeric>;
  divisor?: Prop<Numeric>;
  "dominant-baseline"?: Prop<Numeric>;
  dur?: Prop<Numeric>;
  dx?: Prop<Numeric>;
  dy?: Prop<Numeric>;
  edgeMode?: Prop<Numeric>;
  elevation?: Prop<Numeric>;
  "enable-background"?: Prop<Numeric>;
  end?: Prop<Numeric>;
  exponent?: Prop<Numeric>;
  externalResourcesRequired?: Prop<Booleanish>;
  fill?: Prop<string>;
  "fill-opacity"?: Prop<Numeric>;
  "fill-rule"?: Prop<string>;
  filter?: Prop<string>;
  filterRes?: Prop<Numeric>;
  filterUnits?: Prop<Numeric>;
  "flood-color"?: Prop<Numeric>;
  "flood-opacity"?: Prop<Numeric>;
  focusable?: Prop<string>;
  "font-family"?: Prop<string>;
  "font-size"?: Prop<Numeric>;
  "font-size-adjust"?: Prop<Numeric>;
  "font-stretch"?: Prop<Numeric>;
  "font-style"?: Prop<Numeric>;
  "font-variant"?: Prop<Numeric>;
  "font-weight"?: Prop<Numeric>;
  format?: Prop<Numeric>;
  fr?: Prop<Numeric>;
  from?: Prop<Numeric>;
  fx?: Prop<Numeric>;
  fy?: Prop<Numeric>;
  g1?: Prop<Numeric>;
  g2?: Prop<Numeric>;
  glyphName?: Prop<Numeric>;
  "glyph-orientation-horizontal"?: Prop<Numeric>;
  "glyph-orientation-vertical"?: Prop<Numeric>;
  glyphRef?: Prop<Numeric>;
  gradientTransform?: Prop<string>;
  gradientUnits?: Prop<string>;
  hanging?: Prop<Numeric>;
  height?: Prop<Numeric>;
  horizAdvX?: Prop<Numeric>;
  horizOriginX?: Prop<Numeric>;
  href?: Prop<string>;
  ideographic?: Prop<Numeric>;
  "image-rendering"?: Prop<Numeric>;
  in?: Prop<string>;
  in2?: Prop<Numeric>;
  intercept?: Prop<Numeric>;
  k?: Prop<Numeric>;
  k1?: Prop<Numeric>;
  k2?: Prop<Numeric>;
  k3?: Prop<Numeric>;
  k4?: Prop<Numeric>;
  kernelMatrix?: Prop<Numeric>;
  kernelUnitLength?: Prop<Numeric>;
  kerning?: Prop<Numeric>;
  keyPoints?: Prop<Numeric>;
  keySplines?: Prop<Numeric>;
  keyTimes?: Prop<Numeric>;
  lengthAdjust?: Prop<Numeric>;
  "letter-spacing"?: Prop<Numeric>;
  "lighting-color"?: Prop<Numeric>;
  limitingConeAngle?: Prop<Numeric>;
  local?: Prop<Numeric>;
  "marker-end"?: Prop<string>;
  markerHeight?: Prop<Numeric>;
  "marker-mid"?: Prop<string>;
  "marker-start"?: Prop<string>;
  markerUnits?: Prop<Numeric>;
  markerWidth?: Prop<Numeric>;
  mask?: Prop<string>;
  maskContentUnits?: Prop<Numeric>;
  maskUnits?: Prop<Numeric>;
  mathematical?: Prop<Numeric>;
  max?: Prop<Numeric>;
  media?: Prop<string>;
  method?: Prop<string>;
  min?: Prop<Numeric>;
  mode?: Prop<Numeric>;
  name?: Prop<string>;
  numOctaves?: Prop<Numeric>;
  offset?: Prop<Numeric>;
  opacity?: Prop<Numeric>;
  operator?: Prop<Numeric>;
  order?: Prop<Numeric>;
  orient?: Prop<Numeric>;
  orientation?: Prop<Numeric>;
  origin?: Prop<Numeric>;
  overflow?: Prop<Numeric>;
  "overline-position"?: Prop<Numeric>;
  "overline-thickness"?: Prop<Numeric>;
  "paint-order"?: Prop<Numeric>;
  panose1?: Prop<Numeric>;
  path?: Prop<string>;
  pathLength?: Prop<Numeric>;
  patternContentUnits?: Prop<string>;
  patternTransform?: Prop<Numeric>;
  patternUnits?: Prop<string>;
  "pointer-events"?: Prop<Numeric>;
  points?: Prop<string>;
  pointsAtX?: Prop<Numeric>;
  pointsAtY?: Prop<Numeric>;
  pointsAtZ?: Prop<Numeric>;
  preserveAlpha?: Prop<Booleanish>;
  preserveAspectRatio?: Prop<string>;
  primitiveUnits?: Prop<Numeric>;
  r?: Prop<Numeric>;
  radius?: Prop<Numeric>;
  refX?: Prop<Numeric>;
  refY?: Prop<Numeric>;
  "rendering-intent"?: Prop<Numeric>;
  repeatCount?: Prop<Numeric>;
  repeatDur?: Prop<Numeric>;
  requiredExtensions?: Prop<Numeric>;
  requiredFeatures?: Prop<Numeric>;
  restart?: Prop<Numeric>;
  result?: Prop<string>;
  rotate?: Prop<Numeric>;
  rx?: Prop<Numeric>;
  ry?: Prop<Numeric>;
  scale?: Prop<Numeric>;
  seed?: Prop<Numeric>;
  "shape-rendering"?: Prop<Numeric>;
  slope?: Prop<Numeric>;
  spacing?: Prop<Numeric>;
  specularConstant?: Prop<Numeric>;
  specularExponent?: Prop<Numeric>;
  speed?: Prop<Numeric>;
  spreadMethod?: Prop<string>;
  startOffset?: Prop<Numeric>;
  stdDeviation?: Prop<Numeric>;
  stemh?: Prop<Numeric>;
  stemv?: Prop<Numeric>;
  stitchTiles?: Prop<Numeric>;
  "stop-color"?: Prop<string>;
  "stop-opacity"?: Prop<Numeric>;
  "strikethrough-position"?: Prop<Numeric>;
  "strikethrough-thickness"?: Prop<Numeric>;
  string?: Prop<Numeric>;
  stroke?: Prop<string>;
  "stroke-dasharray"?: Prop<Numeric>;
  "stroke-dashoffset"?: Prop<Numeric>;
  "stroke-linecap"?: Prop<string>;
  "stroke-linejoin"?: Prop<string>;
  "stroke-miterlimit"?: Prop<Numeric>;
  "stroke-opacity"?: Prop<Numeric>;
  "stroke-width"?: Prop<Numeric>;
  surfaceScale?: Prop<Numeric>;
  systemLanguage?: Prop<Numeric>;
  tableValues?: Prop<Numeric>;
  target?: Prop<string>;
  targetX?: Prop<Numeric>;
  targetY?: Prop<Numeric>;
  "text-anchor"?: Prop<string>;
  "text-decoration"?: Prop<Numeric>;
  textLength?: Prop<Numeric>;
  "text-rendering"?: Prop<Numeric>;
  to?: Prop<Numeric>;
  transform?: Prop<string>;
  type?: Prop<string>;
  u1?: Prop<Numeric>;
  u2?: Prop<Numeric>;
  "underline-position"?: Prop<Numeric>;
  "underline-thickness"?: Prop<Numeric>;
  unicode?: Prop<Numeric>;
  "unicode-bidi"?: Prop<Numeric>;
  "unicode-range"?: Prop<Numeric>;
  "units-per-em"?: Prop<Numeric>;
  "v-alphabetic"?: Prop<Numeric>;
  "v-hanging"?: Prop<Numeric>;
  "v-ideographic"?: Prop<Numeric>;
  "v-mathematical"?: Prop<Numeric>;
  values?: Prop<string>;
  "vector-effect"?: Prop<Numeric>;
  version?: Prop<string>;
  "vert-adv-y"?: Prop<Numeric>;
  "vert-origin-x"?: Prop<Numeric>;
  "vert-origin-y"?: Prop<Numeric>;
  viewBox?: Prop<string>;
  viewTarget?: Prop<Numeric>;
  visibility?: Prop<Numeric>;
  width?: Prop<Numeric>;
  widths?: Prop<Numeric>;
  "word-spacing"?: Prop<Numeric>;
  "writing-mode"?: Prop<Numeric>;
  x?: Prop<Numeric>;
  x1?: Prop<Numeric>;
  x2?: Prop<Numeric>;
  xChannelSelector?: Prop<string>;
  xHeight?: Prop<Numeric>;
  xlinkActuate?: Prop<string>;
  xlinkArcrole?: Prop<string>;
  xlinkHref?: Prop<string>;
  xlinkRole?: Prop<string>;
  xlinkShow?: Prop<string>;
  xlinkTitle?: Prop<string>;
  xlinkType?: Prop<string>;
  xmlBase?: Prop<string>;
  xmlLang?: Prop<string>;
  xmlSpace?: Prop<string>;
  xmlnsXlink?: Prop<string>;
  y?: Prop<Numeric>;
  y1?: Prop<Numeric>;
  y2?: Prop<Numeric>;
  yChannelSelector?: Prop<string>;
  z?: Prop<Numeric>;
  zoomAndPan?: Prop<string>;
}

/** The elements this schema declares, and what each accepts. */
export interface Elements extends UiElements {
  a: AnchorProps;
  abbr: HtmlProps;
  address: HtmlProps;
  area: AreaProps;
  article: HtmlProps;
  aside: HtmlProps;
  audio: MediaProps;
  b: HtmlProps;
  base: BaseProps;
  bdi: HtmlProps;
  bdo: HtmlProps;
  blockquote: BlockquoteProps;
  body: HtmlProps;
  br: VoidProps;
  button: ButtonProps;
  canvas: CanvasProps;
  caption: HtmlProps;
  cite: HtmlProps;
  code: HtmlProps;
  col: ColProps;
  colgroup: ColgroupProps;
  data: DataProps;
  datalist: HtmlProps;
  dd: HtmlProps;
  del: DelProps;
  details: DetailsProps;
  dfn: HtmlProps;
  dialog: DialogProps;
  div: HtmlProps;
  dl: HtmlProps;
  dt: HtmlProps;
  em: HtmlProps;
  embed: EmbedProps;
  fieldset: FieldsetProps;
  figcaption: HtmlProps;
  figure: HtmlProps;
  footer: HtmlProps;
  form: FormProps;
  h1: HtmlProps;
  h2: HtmlProps;
  h3: HtmlProps;
  h4: HtmlProps;
  h5: HtmlProps;
  h6: HtmlProps;
  head: HtmlProps;
  header: HtmlProps;
  hgroup: HtmlProps;
  hr: VoidProps;
  html: HtmlElementProps;
  i: HtmlProps;
  iframe: IframeProps;
  img: ImgProps;
  input: InputProps;
  ins: InsProps;
  kbd: HtmlProps;
  label: LabelProps;
  legend: HtmlProps;
  li: LiProps;
  link: LinkProps;
  main: HtmlProps;
  map: MapProps;
  mark: HtmlProps;
  menu: HtmlProps;
  meta: MetaProps;
  meter: MeterProps;
  nav: HtmlProps;
  noscript: HtmlProps;
  object: ObjectProps;
  ol: OlProps;
  optgroup: OptgroupProps;
  option: OptionProps;
  output: OutputProps;
  p: HtmlProps;
  picture: HtmlProps;
  pre: HtmlProps;
  progress: ProgressProps;
  q: QuoteProps;
  rp: HtmlProps;
  rt: HtmlProps;
  ruby: HtmlProps;
  s: HtmlProps;
  samp: HtmlProps;
  script: ScriptProps;
  search: HtmlProps;
  section: HtmlProps;
  select: SelectProps;
  slot: SlotProps;
  small: HtmlProps;
  source: SourceProps;
  span: HtmlProps;
  strong: HtmlProps;
  style: StyleProps;
  sub: HtmlProps;
  summary: HtmlProps;
  sup: HtmlProps;
  table: TableProps;
  tbody: HtmlProps;
  td: TdProps;
  template: HtmlProps;
  textarea: TextareaProps;
  tfoot: HtmlProps;
  th: ThProps;
  thead: HtmlProps;
  time: TimeProps;
  title: HtmlProps;
  tr: HtmlProps;
  track: TrackProps;
  u: HtmlProps;
  ul: HtmlProps;
  var: HtmlProps;
  video: VideoProps;
  wbr: VoidProps;
  "svg:a": SvgProps;
  "svg:animate": SvgProps;
  "svg:animateMotion": SvgProps;
  "svg:animateTransform": SvgProps;
  "svg:circle": SvgProps;
  "svg:clipPath": SvgProps;
  "svg:defs": SvgProps;
  "svg:desc": SvgProps;
  "svg:ellipse": SvgProps;
  "svg:feBlend": SvgProps;
  "svg:feColorMatrix": SvgProps;
  "svg:feComponentTransfer": SvgProps;
  "svg:feComposite": SvgProps;
  "svg:feConvolveMatrix": SvgProps;
  "svg:feDiffuseLighting": SvgProps;
  "svg:feDisplacementMap": SvgProps;
  "svg:feDistantLight": SvgProps;
  "svg:feDropShadow": SvgProps;
  "svg:feFlood": SvgProps;
  "svg:feFuncA": SvgProps;
  "svg:feFuncB": SvgProps;
  "svg:feFuncG": SvgProps;
  "svg:feFuncR": SvgProps;
  "svg:feGaussianBlur": SvgProps;
  "svg:feImage": SvgProps;
  "svg:feMerge": SvgProps;
  "svg:feMergeNode": SvgProps;
  "svg:feMorphology": SvgProps;
  "svg:feOffset": SvgProps;
  "svg:fePointLight": SvgProps;
  "svg:feSpecularLighting": SvgProps;
  "svg:feSpotLight": SvgProps;
  "svg:feTile": SvgProps;
  "svg:feTurbulence": SvgProps;
  "svg:filter": SvgProps;
  "svg:foreignObject": SvgProps;
  "svg:g": SvgProps;
  "svg:image": SvgProps;
  "svg:line": SvgProps;
  "svg:linearGradient": SvgProps;
  "svg:marker": SvgProps;
  "svg:mask": SvgProps;
  "svg:metadata": SvgProps;
  "svg:mpath": SvgProps;
  "svg:path": SvgProps;
  "svg:pattern": SvgProps;
  "svg:polygon": SvgProps;
  "svg:polyline": SvgProps;
  "svg:radialGradient": SvgProps;
  "svg:rect": SvgProps;
  "svg:script": SvgProps;
  "svg:set": SvgProps;
  "svg:stop": SvgProps;
  "svg:style": SvgProps;
  "svg:svg": SvgProps;
  "svg:switch": SvgProps;
  "svg:symbol": SvgProps;
  "svg:text": SvgProps;
  "svg:textPath": SvgProps;
  "svg:title": SvgProps;
  "svg:tspan": SvgProps;
  "svg:use": SvgProps;
  "svg:view": SvgProps;
}

/** What a client must answer with, for every name in scope. */
export interface Builtins extends UiBuiltins {}
