// Generated by `pnpm generate`. Do not edit.

import { createBuiltin, type Client } from "@backtickjs/language";
import type { Window } from "./declarations.generated.js";

/**
 * The window a script is drawn in. Imported and spliced — `$window` — rather
 * than written as a bare name: a target's vocabulary is a value it hands over,
 * not a word the compiler knows.
 */
export const window: Client<Window> = createBuiltin("window");
