// Generated by `pnpm generate`. Do not edit.

declare const SignalBrand: unique symbol;
/**
 * Storage a script may read but not replace.
 *
 * What a position is in a list is one of these, and so is a cell handed to a
 * component that only displays it: the signature says which way the value
 * travels, and a `State` goes wherever one of these is wanted.
 */
export interface Signal<T> extends ClientHandle {
  readonly [SignalBrand]: never;
  get(): T;
}

declare const StateBrand: unique symbol;
/**
 * A cell as a script reads it.
 *
 * What makes one is not here: `state` is a client function a script imports
 * and splices, so a cell is what calling it answers with. This is the half
 * that reaches the client.
 *
 * `set` stores what it is given, a function included: it never calls it.
 */
export interface State<T> extends Signal<T> {
  readonly [StateBrand]: never;
  set(value: T): void;
}

/**
 * How a signal decides that a new value is a change.
 */
export interface SignalOptions<T> {
  /**
   * Whether `next` counts as the same value as `previous`. When it does,
   * whatever reads the signal isn't updated. Compared with `===` when left
   * out.
   */
  equals?(previous: T, next: T): boolean;
}

declare const ClientHandleBrand: unique symbol;
/**
 * Something the client owns, and that nothing here reads into.
 *
 * A script may hold one and hand it back and nothing else: what it is made of
 * is the client's, and two clients need not agree on that to agree on this.
 * Every opaque type is one — `State` is a handle, and so is anything a client
 * answers with that this format does not describe.
 */
export interface ClientHandle {
  readonly [ClientHandleBrand]: never;
}

/**
 * A function a client holds. What it takes is nothing this format describes —
 * a client hands one what it was given — and what it answers with is a client
 * value, or nothing.
 */
export type ClientFunction = (...args: never[]) => ClientUnknown;

/**
 * A client value, or nothing. What an action answers with, where every other
 * position takes a value.
 */
export type ClientUnknown = ClientValue | void;

/**
 * What may cross between a host and a client: data, a function, or a handle to
 * something the client owns.
 */
export type ClientValue =
  | null
  | undefined
  | number
  | boolean
  | string
  | { readonly [key: string]: ClientValue }
  | readonly ClientValue[]
  | ClientFunction
  | ClientHandle;

declare const BundleBrand: unique symbol;
/**
 * The bundler's wire format, as plain data — what ships is exactly the JSON of
 * one of these. This is the contract an interpreter implements: evaluate
 * `root` against the `functions` table. Computation ships as ASTs, so nothing
 * here needs a JavaScript parser.
 *
 * Opaque to a script, which is a different question from what it is made of: a
 * script may hold one and hand it back — to `evaluate`, which evaluates it —
 * and never read into it. What a client keeps behind one is the client's.
 *
 * What it comes to is carried and never read. A client has nothing to check it
 * against; it is what a host writes down so that what a bundle answers with is
 * known where the bundle is handed over.
 */
export interface Bundle<T extends ClientUnknown> extends ClientHandle {
  readonly [BundleBrand]: T;
  readonly functions: { [key: BundleFunctionLabel]: BundleArrowFunction };
  readonly root: BundleExpression;
}

export type BundleFunctionLabel = string;

export type BundleElement = [
  kind: "el",
  id: string,
  props: { [key: string]: BundleExpression },
  children: BundleExpression,
];

/**
 * A call of a component a script holds: the function called with one record of
 * its props, each member evaluated when it is read, and `children` among them
 * where the tag holds any. What a component's props are, for a function the
 * bundler never saw.
 */
export type BundleComponentCall = [
  kind: "comp",
  callee: BundleExpression,
  props: { [key: string]: BundleExpression },
  children: BundleExpression,
];

export type BundleArrayLiteral = [kind: "arr", members: BundleArrayElement[]];

export type BundleSpreadElement = [kind: "...", expression: BundleExpression];

export type BundleUndefined = [kind: "undef"];

export type BundleBuiltin = [kind: "bltn", name: string];

export type BundleArrayElement = BundleExpression | BundleSpreadElement;

export type BundleExpression =
  | null
  | boolean
  | number
  | string
  | { readonly [key: string]: BundleExpression }
  | BundleUndefined
  | BundleArrayLiteral
  | BundleIdentifier
  | BundleFunctionReference
  | BundleElement
  | BundleComponentCall
  | BundleCall
  | BundleOptionalCall
  | BundlePropertyAccess
  | BundleOptionalPropertyAccess
  | BundleElementAccess
  | BundleAssignment
  | BundleAdditionAssignment
  | BundleSubtractionAssignment
  | BundleMultiplicationAssignment
  | BundleDivisionAssignment
  | BundleRemainderAssignment
  | BundleLogicalAnd
  | BundleLogicalOr
  | BundleNullishCoalescing
  | BundleAddition
  | BundleSubtraction
  | BundleMultiplication
  | BundleDivision
  | BundleRemainder
  | BundleStrictEquality
  | BundleStrictInequality
  | BundleLessThan
  | BundleLessThanOrEqual
  | BundleGreaterThan
  | BundleGreaterThanOrEqual
  | BundleLogicalNot
  | BundleNegation
  | BundleTypeOf
  | BundlePrefixIncrement
  | BundlePrefixDecrement
  | BundlePostfixIncrement
  | BundlePostfixDecrement
  | BundleConditional
  | BundleArrowFunction
  | BundleBuiltin;

export type BundleStatement =
  | BundleExpression
  | BundleBlock
  | BundleConstDeclaration
  | BundleLetDeclaration
  | BundleIf
  | BundleWhile
  | BundleFor
  | BundleBreak
  | BundleContinue
  | BundleReturn
  | BundleThrow
  | BundleTry;

export type BundleBody = BundleExpression | BundleBlock;

export type BundleIdentifier = [kind: "id", text: string];

export type BundleFunctionReference = [kind: "fn", label: BundleFunctionLabel];

export type BundleCall = [
  kind: "()",
  expression: BundleExpression,
  args: BundleArrayElement[],
];

export type BundleOptionalCall = [
  kind: "?.()",
  expression: BundleExpression,
  args: BundleArrayElement[],
];

export type BundlePropertyAccess = [
  kind: ".",
  expression: BundleExpression,
  name: string,
];

export type BundleOptionalPropertyAccess = [
  kind: "?.",
  expression: BundleExpression,
  name: string,
];

export type BundleElementAccess = [
  kind: "[]",
  expression: BundleExpression,
  argumentExpression: BundleExpression,
];

export type BundleAssignment = [
  kind: "=",
  target: BundleIdentifier,
  value: BundleExpression,
];

export type BundleAdditionAssignment = [
  kind: "+=",
  target: BundleIdentifier,
  value: BundleExpression,
];

export type BundleSubtractionAssignment = [
  kind: "-=",
  target: BundleIdentifier,
  value: BundleExpression,
];

export type BundleMultiplicationAssignment = [
  kind: "*=",
  target: BundleIdentifier,
  value: BundleExpression,
];

export type BundleDivisionAssignment = [
  kind: "/=",
  target: BundleIdentifier,
  value: BundleExpression,
];

export type BundleRemainderAssignment = [
  kind: "%=",
  target: BundleIdentifier,
  value: BundleExpression,
];

export type BundleLogicalAnd = [
  kind: "&&",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleLogicalOr = [
  kind: "||",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleNullishCoalescing = [
  kind: "??",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleAddition = [
  kind: "+",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleSubtraction = [
  kind: "-",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleMultiplication = [
  kind: "*",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleDivision = [
  kind: "/",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleRemainder = [
  kind: "%",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleStrictEquality = [
  kind: "===",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleStrictInequality = [
  kind: "!==",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleLessThan = [
  kind: "<",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleLessThanOrEqual = [
  kind: "<=",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleGreaterThan = [
  kind: ">",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleGreaterThanOrEqual = [
  kind: ">=",
  left: BundleExpression,
  right: BundleExpression,
];

export type BundleLogicalNot = [kind: "!", operand: BundleExpression];

export type BundleNegation = [kind: "-x", operand: BundleExpression];

export type BundleTypeOf = [kind: "typeof", operand: BundleExpression];

export type BundlePrefixIncrement = [kind: "++x", target: BundleIdentifier];

export type BundlePrefixDecrement = [kind: "--x", target: BundleIdentifier];

export type BundlePostfixIncrement = [kind: "x++", target: BundleIdentifier];

export type BundlePostfixDecrement = [kind: "x--", target: BundleIdentifier];

export type BundleConditional = [
  kind: "?:",
  condition: BundleExpression,
  whenTrue: BundleExpression,
  whenFalse: BundleExpression,
];

export type BundleArrowFunction = [
  kind: "=>",
  parameters: BundleParameter[],
  body: BundleBody,
];

export type BundleBlock = [kind: "{}", statements: BundleStatement[]];

export type BundleConstDeclaration = [
  kind: "const",
  name: string,
  initializer: BundleExpression,
];

export type BundleLetDeclaration = [
  kind: "let",
  name: string,
  initializer: BundleExpression,
];

export type BundleIf = [
  kind: "if",
  expression: BundleExpression,
  thenStatement: BundleStatement,
  elseStatement: BundleStatement | null,
];

export type BundleWhile = [
  kind: "while",
  expression: BundleExpression,
  statement: BundleStatement,
];

export type BundleFor = [
  kind: "for",
  initializer:
    | BundleConstDeclaration
    | BundleLetDeclaration
    | BundleExpression
    | null,
  condition: BundleExpression | null,
  incrementor: BundleExpression | null,
  statement: BundleStatement,
];

export type BundleBreak = [kind: "break"];

export type BundleContinue = [kind: "continue"];

export type BundleReturn = [kind: "return", expression: BundleExpression];

export type BundleThrow = [kind: "throw", expression: BundleExpression];

export type BundleTry = [
  kind: "try",
  tryBlock: BundleBlock,
  catchClause: BundleCatchClause,
];

export type BundleCatchClause = [
  kind: "catch",
  variableDeclaration: string | null,
  block: BundleBlock,
];

export type BundleParameter = [kind: "param", name: string];

export interface ArrayLike<T extends ClientValue> {
  readonly length: number;
  readonly [n: number]: T;
}

/** The elements this schema declares, and what each accepts. */
export interface PlatformElements {}

/** Every element in scope, this schema's own and its bases'. */
export interface Elements extends PlatformElements {}

/** What this schema declares, which is what its own client answers for. */
export interface PlatformBuiltins {
  /**
   * Creates a `State`, a `Signal` a script can both `get` and `set`, and the
   * foundation of Backtick's reactivity. Whatever reads it with `get` follows
   * it — a prop, a child, a `computed` — and a `set` runs those readers again
   * and nothing else. Reading is cheap and setting does the work, so a state
   * suits values read often and set less often.
   *
   * Created while a script draws, it lasts as long as that drawing.
   *
   * @param initial The value it holds until the first `set`.
   */
  state<T>(initial: T, options?: SignalOptions<T>): State<T>;
  /**
   * Creates a read-only `Signal` that derives its value from other signals.
   * The calculated value is memoized: `fn` runs when the computed is created
   * and again only when a signal it read changes, and every `get` reuses the
   * result. If the new result equals the previous one (`===`, or
   * `options.equals`), the computed doesn't update whatever reads it.
   *
   * Created while a script draws, it lasts as long as that drawing.
   *
   * @param fn Calculates the value from the signals it reads.
   */
  computed<T>(fn: () => T, options?: SignalOptions<T>): Signal<T>;
  /**
   * What a bundle holds: its `root` evaluated against its `functions`, here. A
   * bundle is data — a program a client runs — and running one reads no
   * JavaScript.
   *
   * Each call evaluates it again, so two calls are two drawings with cells of
   * their own. Evaluated untracked, as a component is run: what the bundle
   * reads while its root is evaluated is read once, so a write to it evaluates
   * nothing again. A caller that reads a cell to choose the bundle still
   * follows that cell.
   *
   * @param bundle A script that fetched the text writes `JSON.parse(text) as
   * Bundle<BacktickElement>`, which is what an assertion is for.
   */
  evaluate<T extends ClientUnknown>(bundle: Bundle<T>): T;
}

/** What a client must answer with, for every name in scope. */
export interface Builtins extends PlatformBuiltins {}
