// Generated by `pnpm generate`. Do not edit.

import { createBuiltin, type Client } from "@backtickjs/boundary";
import type { State } from "./declarations.generated.js";

export const state: Client<<T>(initial: T) => State<T>> =
  createBuiltin("state");
