// Generated by `pnpm generate`. Do not edit.

export type ClientFunction = (...args: never[]) => ClientUnknown;

/**
 * What a value is on the client: data, a function, or a handle to an object
 * owned and managed by the client.
 */
export type ClientValue =
  | null
  | number
  | boolean
  | string
  | { readonly [key: string]: ClientValue }
  | readonly ClientValue[]
  | ClientFunction
  | ClientHandle;

export type ClientUnknown = ClientValue | void;

declare const ClientHandleBrand: unique symbol;
/**
 * Represents a handle to an object owned and managed by the client. The handle
 * can be referenced and passed in client script.
 */
export interface ClientHandle {
  readonly [ClientHandleBrand]: never;
}

declare const ReadonlyStateBrand: unique symbol;
/**
 * Storage a script may read but not replace.
 *
 * What a position is in a list is one of these, and so is a cell handed to a
 * component that only displays it: the signature says which way the value
 * travels, and a `State` goes wherever one of these is wanted.
 */
export interface ReadonlyState<T> extends ClientHandle {
  readonly [ReadonlyStateBrand]: never;
  read(): T;
}

declare const StateBrand: unique symbol;
/**
 * A cell as a script reads it.
 *
 * Declaring one is not here: `state()` is a name the compiler recognises, and
 * declaring happens while a component is being expanded and has to know which
 * instance is running. This is the half that reaches the client.
 */
export interface State<T> extends ReadonlyState<T> {
  readonly [StateBrand]: never;
  write(value: T): void;
  update(updater: (value: T) => T): void;
}

export interface Boolean {
  /**
   * Returns the primitive value of the specified object.
   */
  valueOf(): boolean;
}

export interface Number {
  /**
   * Returns a string representation of an object.
   *
   * @param radix Specifies a radix for converting numeric values to strings.
   * This value is only used for numbers.
   */
  toString(radix?: number): string;
  /**
   * Returns a string representing a number in fixed-point notation.
   *
   * @param fractionDigits Number of digits after the decimal point. Must be in
   * the range 0 - 20, inclusive.
   */
  toFixed(fractionDigits?: number): string;
  /**
   * Returns a string containing a number represented in exponential notation.
   *
   * @param fractionDigits Number of digits after the decimal point. Must be in
   * the range 0 - 20, inclusive.
   */
  toExponential(fractionDigits?: number): string;
  /**
   * Returns a string containing a number represented either in exponential or
   * fixed-point notation with a specified number of digits.
   *
   * @param precision Number of significant digits. Must be in the range 1 -
   * 21, inclusive.
   */
  toPrecision(precision?: number): string;
  /**
   * Returns the primitive value of the specified object.
   */
  valueOf(): number;
}

export interface String {
  /**
   * Returns a string representation of a string.
   */
  toString(): string;
  /**
   * Returns the character at the specified index.
   *
   * @param pos The zero-based index of the desired character.
   */
  charAt(pos: number): string;
  /**
   * Returns the Unicode value of the character at the specified location.
   *
   * @param index The zero-based index of the desired character. If there is no
   * character at the specified index, NaN is returned.
   */
  charCodeAt(index: number): number;
  /**
   * Returns a string that contains the concatenation of two or more strings.
   *
   * @param strings The strings to append to the end of the string.
   */
  concat(...strings: string[]): string;
  /**
   * Returns the position of the first occurrence of a substring, or -1 if it
   * is not present.
   *
   * @param searchString The substring to search for in the string
   * @param position The index at which to begin searching the String object.
   * If omitted, search starts at the beginning of the string.
   */
  indexOf(searchString: string, position?: number): number;
  /**
   * Returns the last occurrence of a substring in the string, or -1 if it is
   * not present.
   *
   * @param searchString The substring to search for.
   * @param position The index at which to begin searching. If omitted, the
   * search begins at the end of the string.
   */
  lastIndexOf(searchString: string, position?: number): number;
  /**
   * Determines whether two strings are equivalent in the current locale.
   *
   * @param that String to compare to target string
   */
  localeCompare(that: string): number;
  /**
   * Replaces text in a string, using a search string.
   *
   * @param searchValue A string to search for.
   * @param replaceValue The text to replace it with, or a function answering
   * with that text. Only the first match of `searchValue` is replaced.
   */
  replace(
    searchValue: string,
    replaceValue:
      | string
      | ((substring: string, offset: number, string: string) => string),
  ): string;
  /**
   * Returns a section of a string.
   *
   * @param start The index to the beginning of the specified portion of
   * stringObj.
   * @param end The index to the end of the specified portion of stringObj. The
   * substring includes the characters up to, but not including, the character
   * indicated by end. If this value is not specified, the substring continues
   * to the end of stringObj.
   */
  slice(start?: number, end?: number): string;
  /**
   * Split a string into substrings using the specified separator and return
   * them as an array.
   *
   * @param separator A string that identifies character or characters to use
   * in separating the string. If omitted, a single-element array containing
   * the entire string is returned.
   * @param limit A value used to limit the number of elements returned in the
   * array.
   */
  split(separator: string, limit?: number): string[];
  /**
   * Returns the substring at the specified location within a String object.
   *
   * @param start The zero-based index number indicating the beginning of the
   * substring.
   * @param end Zero-based index number indicating the end of the substring.
   * The substring includes the characters up to, but not including, the
   * character indicated by end. If end is omitted, the characters from start
   * through the end of the original string are returned.
   */
  substring(start: number, end?: number): string;
  /**
   * Converts all the alphabetic characters in a string to lowercase.
   */
  toLowerCase(): string;
  /**
   * Converts all alphabetic characters to lowercase, taking into account the
   * host environment's current locale.
   */
  toLocaleLowerCase(locales?: string | string[]): string;
  /**
   * Converts all the alphabetic characters in a string to uppercase.
   */
  toUpperCase(): string;
  /**
   * Returns a string where all alphabetic characters have been converted to
   * uppercase, taking into account the host environment's current locale.
   */
  toLocaleUpperCase(locales?: string | string[]): string;
  /**
   * Removes the leading and trailing white space and line terminator
   * characters from a string.
   */
  trim(): string;
  /**
   * Returns the length of a String object.
   */
  readonly length: number;
  /**
   * Returns the primitive value of the specified object.
   */
  valueOf(): string;
  readonly [index: number]: string;
}

export interface Array<T> {
  /**
   * Gets the length of the array. This is a number one higher than the highest
   * index in the array.
   */
  readonly length: number;
  /**
   * Combines two or more arrays. This method returns a new array without
   * modifying any existing arrays.
   *
   * @param items Additional arrays and/or items to add to the end of the
   * array.
   */
  concat(...items: (T | readonly T[])[]): T[];
  /**
   * Adds all the elements of an array into a string, separated by the
   * specified separator string.
   *
   * @param separator A string used to separate one element of the array from
   * the next in the resulting string. If omitted, the array elements are
   * separated with a comma.
   */
  join(separator?: string): string;
  /**
   * Returns a copy of a section of an array.
   *
   * @param start The beginning index of the specified portion of the array. If
   * start is undefined, then the slice begins at index 0.
   * @param end The end index of the specified portion of the array. This is
   * exclusive of the element at the index 'end'. If end is undefined, then the
   * slice extends to the end of the array.
   */
  slice(start?: number, end?: number): T[];
  /**
   * Returns the index of the first occurrence of a value in an array, or -1 if
   * it is not present.
   *
   * @param searchElement The value to locate in the array.
   * @param fromIndex The array index at which to begin the search. If
   * fromIndex is omitted, the search starts at index 0.
   */
  indexOf(searchElement: T, fromIndex?: number): number;
  /**
   * Determines whether an array includes a certain element, returning true or
   * false as appropriate.
   *
   * @param searchElement The element to search for.
   * @param fromIndex The position in this array at which to begin searching
   * for searchElement.
   */
  includes(searchElement: T, fromIndex?: number): boolean;
  /**
   * Calls a defined callback function on each element of an array, and returns
   * an array that contains the results.
   *
   * @param callbackfn A function that accepts up to two arguments. The map
   * method calls the callbackfn function one time for each element in the
   * array.
   */
  map<U>(callbackfn: (value: T, index: number) => U): U[];
  /**
   * Returns the elements of an array that meet the condition specified in a
   * callback function.
   *
   * @param predicate A function that accepts up to two arguments. The filter
   * method calls the predicate function one time for each element in the
   * array.
   */
  filter(predicate: (value: T, index: number) => boolean): T[];
  /**
   * Copies an array, then overwrites the value at the provided index with the
   * given value. If the index is negative, then it replaces from the end of
   * the array.
   *
   * @param index The index of the value to overwrite. If the index is
   * negative, then it replaces from the end of the array.
   * @param value The value to write into the copied array.
   */
  with(index: number, value: T): T[];
  /**
   * Returns a copy of an array with its elements sorted.
   *
   * The comparator is required, where the standard library makes it optional:
   * sorting without one compares the elements as strings, which is a rule of
   * JavaScript's rather than of this language, and every other host would have
   * to reproduce it to agree. Saying how to order two elements is the same
   * work and it ports.
   *
   * @param compareFn Function used to determine the order of the elements. It
   * is expected to return a negative value if the first argument is less than
   * the second argument, zero if they're equal, and a positive value
   * otherwise.
   */
  toSorted(compareFn: (a: T, b: T) => number): T[];
  /**
   * Returns a copy of an array with its elements in reverse order.
   */
  toReversed(): T[];
  /**
   * Copies an array and removes elements while, if necessary, inserting new
   * elements in their place, returning the remaining elements.
   *
   * @param start The zero-based location in the array from which to start
   * removing elements.
   * @param deleteCount The number of elements to remove.
   * @param items Elements to insert into the copied array in place of the
   * deleted elements.
   */
  toSpliced(start: number, deleteCount: number, ...items: T[]): T[];
  readonly [index: number]: T;
}

export interface ArrayLike<T> {
  readonly length: number;
  readonly [n: number]: T;
}

/** What a client must answer with, for every name in scope. */
export interface Builtins {
  /**
   * Returns the primitive value of the specified object.
   *
   * @param self The value the member is reached off.
   */
  "boolean.valueOf"(self: boolean): boolean;
  /**
   * Returns a string representation of an object.
   *
   * @param self The value the member is reached off.
   * @param radix Specifies a radix for converting numeric values to strings.
   * This value is only used for numbers.
   */
  "number.toString"(self: number, radix?: number): string;
  /**
   * Returns a string representing a number in fixed-point notation.
   *
   * @param self The value the member is reached off.
   * @param fractionDigits Number of digits after the decimal point. Must be in
   * the range 0 - 20, inclusive.
   */
  "number.toFixed"(self: number, fractionDigits?: number): string;
  /**
   * Returns a string containing a number represented in exponential notation.
   *
   * @param self The value the member is reached off.
   * @param fractionDigits Number of digits after the decimal point. Must be in
   * the range 0 - 20, inclusive.
   */
  "number.toExponential"(self: number, fractionDigits?: number): string;
  /**
   * Returns a string containing a number represented either in exponential or
   * fixed-point notation with a specified number of digits.
   *
   * @param self The value the member is reached off.
   * @param precision Number of significant digits. Must be in the range 1 -
   * 21, inclusive.
   */
  "number.toPrecision"(self: number, precision?: number): string;
  /**
   * Returns the primitive value of the specified object.
   *
   * @param self The value the member is reached off.
   */
  "number.valueOf"(self: number): number;
  /**
   * Returns a string representation of a string.
   *
   * @param self The value the member is reached off.
   */
  "string.toString"(self: string): string;
  /**
   * Returns the character at the specified index.
   *
   * @param self The value the member is reached off.
   * @param pos The zero-based index of the desired character.
   */
  "string.charAt"(self: string, pos: number): string;
  /**
   * Returns the Unicode value of the character at the specified location.
   *
   * @param self The value the member is reached off.
   * @param index The zero-based index of the desired character. If there is no
   * character at the specified index, NaN is returned.
   */
  "string.charCodeAt"(self: string, index: number): number;
  /**
   * Returns a string that contains the concatenation of two or more strings.
   *
   * @param self The value the member is reached off.
   * @param strings The strings to append to the end of the string.
   */
  "string.concat"(self: string, ...strings: string[]): string;
  /**
   * Returns the position of the first occurrence of a substring, or -1 if it
   * is not present.
   *
   * @param self The value the member is reached off.
   * @param searchString The substring to search for in the string
   * @param position The index at which to begin searching the String object.
   * If omitted, search starts at the beginning of the string.
   */
  "string.indexOf"(
    self: string,
    searchString: string,
    position?: number,
  ): number;
  /**
   * Returns the last occurrence of a substring in the string, or -1 if it is
   * not present.
   *
   * @param self The value the member is reached off.
   * @param searchString The substring to search for.
   * @param position The index at which to begin searching. If omitted, the
   * search begins at the end of the string.
   */
  "string.lastIndexOf"(
    self: string,
    searchString: string,
    position?: number,
  ): number;
  /**
   * Determines whether two strings are equivalent in the current locale.
   *
   * @param self The value the member is reached off.
   * @param that String to compare to target string
   */
  "string.localeCompare"(self: string, that: string): number;
  /**
   * Replaces text in a string, using a search string.
   *
   * @param self The value the member is reached off.
   * @param searchValue A string to search for.
   * @param replaceValue The text to replace it with, or a function answering
   * with that text. Only the first match of `searchValue` is replaced.
   */
  "string.replace"(
    self: string,
    searchValue: string,
    replaceValue:
      | string
      | ((substring: string, offset: number, string: string) => string),
  ): string;
  /**
   * Returns a section of a string.
   *
   * @param self The value the member is reached off.
   * @param start The index to the beginning of the specified portion of
   * stringObj.
   * @param end The index to the end of the specified portion of stringObj. The
   * substring includes the characters up to, but not including, the character
   * indicated by end. If this value is not specified, the substring continues
   * to the end of stringObj.
   */
  "string.slice"(self: string, start?: number, end?: number): string;
  /**
   * Split a string into substrings using the specified separator and return
   * them as an array.
   *
   * @param self The value the member is reached off.
   * @param separator A string that identifies character or characters to use
   * in separating the string. If omitted, a single-element array containing
   * the entire string is returned.
   * @param limit A value used to limit the number of elements returned in the
   * array.
   */
  "string.split"(self: string, separator: string, limit?: number): string[];
  /**
   * Returns the substring at the specified location within a String object.
   *
   * @param self The value the member is reached off.
   * @param start The zero-based index number indicating the beginning of the
   * substring.
   * @param end Zero-based index number indicating the end of the substring.
   * The substring includes the characters up to, but not including, the
   * character indicated by end. If end is omitted, the characters from start
   * through the end of the original string are returned.
   */
  "string.substring"(self: string, start: number, end?: number): string;
  /**
   * Converts all the alphabetic characters in a string to lowercase.
   *
   * @param self The value the member is reached off.
   */
  "string.toLowerCase"(self: string): string;
  /**
   * Converts all alphabetic characters to lowercase, taking into account the
   * host environment's current locale.
   *
   * @param self The value the member is reached off.
   */
  "string.toLocaleLowerCase"(self: string, locales?: string | string[]): string;
  /**
   * Converts all the alphabetic characters in a string to uppercase.
   *
   * @param self The value the member is reached off.
   */
  "string.toUpperCase"(self: string): string;
  /**
   * Returns a string where all alphabetic characters have been converted to
   * uppercase, taking into account the host environment's current locale.
   *
   * @param self The value the member is reached off.
   */
  "string.toLocaleUpperCase"(self: string, locales?: string | string[]): string;
  /**
   * Removes the leading and trailing white space and line terminator
   * characters from a string.
   *
   * @param self The value the member is reached off.
   */
  "string.trim"(self: string): string;
  /**
   * Returns the length of a String object.
   *
   * @param self The value the member is reached off.
   */
  "string.length"(self: string): number;
  /**
   * Returns the primitive value of the specified object.
   *
   * @param self The value the member is reached off.
   */
  "string.valueOf"(self: string): string;
  /**
   * Gets the length of the array. This is a number one higher than the highest
   * index in the array.
   *
   * @param self The value the member is reached off.
   */
  "array.length"<T>(self: T[]): number;
  /**
   * Combines two or more arrays. This method returns a new array without
   * modifying any existing arrays.
   *
   * @param self The value the member is reached off.
   * @param items Additional arrays and/or items to add to the end of the
   * array.
   */
  "array.concat"<T>(self: T[], ...items: (T | readonly T[])[]): T[];
  /**
   * Adds all the elements of an array into a string, separated by the
   * specified separator string.
   *
   * @param self The value the member is reached off.
   * @param separator A string used to separate one element of the array from
   * the next in the resulting string. If omitted, the array elements are
   * separated with a comma.
   */
  "array.join"<T>(self: T[], separator?: string): string;
  /**
   * Returns a copy of a section of an array.
   *
   * @param self The value the member is reached off.
   * @param start The beginning index of the specified portion of the array. If
   * start is undefined, then the slice begins at index 0.
   * @param end The end index of the specified portion of the array. This is
   * exclusive of the element at the index 'end'. If end is undefined, then the
   * slice extends to the end of the array.
   */
  "array.slice"<T>(self: T[], start?: number, end?: number): T[];
  /**
   * Returns the index of the first occurrence of a value in an array, or -1 if
   * it is not present.
   *
   * @param self The value the member is reached off.
   * @param searchElement The value to locate in the array.
   * @param fromIndex The array index at which to begin the search. If
   * fromIndex is omitted, the search starts at index 0.
   */
  "array.indexOf"<T>(self: T[], searchElement: T, fromIndex?: number): number;
  /**
   * Determines whether an array includes a certain element, returning true or
   * false as appropriate.
   *
   * @param self The value the member is reached off.
   * @param searchElement The element to search for.
   * @param fromIndex The position in this array at which to begin searching
   * for searchElement.
   */
  "array.includes"<T>(self: T[], searchElement: T, fromIndex?: number): boolean;
  /**
   * Calls a defined callback function on each element of an array, and returns
   * an array that contains the results.
   *
   * @param self The value the member is reached off.
   * @param callbackfn A function that accepts up to two arguments. The map
   * method calls the callbackfn function one time for each element in the
   * array.
   */
  "array.map"<T, U>(self: T[], callbackfn: (value: T, index: number) => U): U[];
  /**
   * Returns the elements of an array that meet the condition specified in a
   * callback function.
   *
   * @param self The value the member is reached off.
   * @param predicate A function that accepts up to two arguments. The filter
   * method calls the predicate function one time for each element in the
   * array.
   */
  "array.filter"<T>(
    self: T[],
    predicate: (value: T, index: number) => boolean,
  ): T[];
  /**
   * Copies an array, then overwrites the value at the provided index with the
   * given value. If the index is negative, then it replaces from the end of
   * the array.
   *
   * @param self The value the member is reached off.
   * @param index The index of the value to overwrite. If the index is
   * negative, then it replaces from the end of the array.
   * @param value The value to write into the copied array.
   */
  "array.with"<T>(self: T[], index: number, value: T): T[];
  /**
   * Returns a copy of an array with its elements sorted.
   *
   * The comparator is required, where the standard library makes it optional:
   * sorting without one compares the elements as strings, which is a rule of
   * JavaScript's rather than of this language, and every other host would have
   * to reproduce it to agree. Saying how to order two elements is the same
   * work and it ports.
   *
   * @param self The value the member is reached off.
   * @param compareFn Function used to determine the order of the elements. It
   * is expected to return a negative value if the first argument is less than
   * the second argument, zero if they're equal, and a positive value
   * otherwise.
   */
  "array.toSorted"<T>(self: T[], compareFn: (a: T, b: T) => number): T[];
  /**
   * Returns a copy of an array with its elements in reverse order.
   *
   * @param self The value the member is reached off.
   */
  "array.toReversed"<T>(self: T[]): T[];
  /**
   * Copies an array and removes elements while, if necessary, inserting new
   * elements in their place, returning the remaining elements.
   *
   * @param self The value the member is reached off.
   * @param start The zero-based location in the array from which to start
   * removing elements.
   * @param deleteCount The number of elements to remove.
   * @param items Elements to insert into the copied array in place of the
   * deleted elements.
   */
  "array.toSpliced"<T>(
    self: T[],
    start: number,
    deleteCount: number,
    ...items: T[]
  ): T[];
  /**
   * The mathematical constant e. This is Euler's number, the base of natural
   * logarithms.
   */
  readonly "Math.E": number;
  /**
   * The natural logarithm of 10.
   */
  readonly "Math.LN10": number;
  /**
   * The natural logarithm of 2.
   */
  readonly "Math.LN2": number;
  /**
   * The base-2 logarithm of e.
   */
  readonly "Math.LOG2E": number;
  /**
   * The base-10 logarithm of e.
   */
  readonly "Math.LOG10E": number;
  /**
   * Pi. This is the ratio of the circumference of a circle to its diameter.
   */
  readonly "Math.PI": number;
  /**
   * The square root of 0.5, or, equivalently, one divided by the square root
   * of 2.
   */
  readonly "Math.SQRT1_2": number;
  /**
   * The square root of 2.
   */
  readonly "Math.SQRT2": number;
  /**
   * Returns the absolute value of a number (the value without regard to
   * whether it is positive or negative). For example, the absolute value of -5
   * is the same as the absolute value of 5.
   *
   * @param x A numeric expression for which the absolute value is needed.
   */
  "Math.abs"(x: number): number;
  /**
   * Returns the arc cosine (or inverse cosine) of a number.
   *
   * @param x A numeric expression.
   */
  "Math.acos"(x: number): number;
  /**
   * Returns the arcsine of a number.
   *
   * @param x A numeric expression.
   */
  "Math.asin"(x: number): number;
  /**
   * Returns the arctangent of a number.
   *
   * @param x A numeric expression for which the arctangent is needed.
   */
  "Math.atan"(x: number): number;
  /**
   * Returns the angle (in radians) between the X axis and the line going
   * through both the origin and the given point.
   *
   * @param y A numeric expression representing the cartesian y-coordinate.
   * @param x A numeric expression representing the cartesian x-coordinate.
   */
  "Math.atan2"(y: number, x: number): number;
  /**
   * Returns the smallest integer greater than or equal to its numeric
   * argument.
   *
   * @param x A numeric expression.
   */
  "Math.ceil"(x: number): number;
  /**
   * Returns the cosine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  "Math.cos"(x: number): number;
  /**
   * Returns e (the base of natural logarithms) raised to a power.
   *
   * @param x A numeric expression representing the power of e.
   */
  "Math.exp"(x: number): number;
  /**
   * Returns the greatest integer less than or equal to its numeric argument.
   *
   * @param x A numeric expression.
   */
  "Math.floor"(x: number): number;
  /**
   * Returns the natural logarithm (base e) of a number.
   *
   * @param x A numeric expression.
   */
  "Math.log"(x: number): number;
  /**
   * Returns the larger of a set of supplied numeric expressions.
   *
   * Calling this with no arguments is a client error rather than an answer:
   * the standard library takes none and answers `-Infinity`, which is not a
   * value this language has.
   *
   * @param values Numeric expressions to be evaluated.
   */
  "Math.max"(...values: number[]): number;
  /**
   * Returns the smaller of a set of supplied numeric expressions.
   *
   * Calling this with no arguments is a client error rather than an answer:
   * the standard library takes none and answers `Infinity`, which is not a
   * value this language has.
   *
   * @param values Numeric expressions to be evaluated.
   */
  "Math.min"(...values: number[]): number;
  /**
   * Returns the value of a base expression taken to a specified power.
   *
   * @param x The base value of the expression.
   * @param y The exponent value of the expression.
   */
  "Math.pow"(x: number, y: number): number;
  /**
   * Returns a pseudorandom number between 0 and 1.
   */
  "Math.random"(): number;
  /**
   * Returns a supplied numeric expression rounded to the nearest integer.
   *
   * @param x The value to be rounded to the nearest integer.
   */
  "Math.round"(x: number): number;
  /**
   * Returns the sine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  "Math.sin"(x: number): number;
  /**
   * Returns the square root of a number.
   *
   * @param x A numeric expression.
   */
  "Math.sqrt"(x: number): number;
  /**
   * Returns the tangent of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  "Math.tan"(x: number): number;
  /**
   * Returns the number of leading zero bits in the 32-bit binary
   * representation of a number.
   *
   * @param x A numeric expression.
   */
  "Math.clz32"(x: number): number;
  /**
   * Returns the result of 32-bit multiplication of two numbers.
   *
   * @param x First number
   * @param y Second number
   */
  "Math.imul"(x: number, y: number): number;
  /**
   * Returns the sign of the x, indicating whether x is positive, negative or
   * zero.
   *
   * @param x The numeric expression to test
   */
  "Math.sign"(x: number): number;
  /**
   * Returns the base 10 logarithm of a number.
   *
   * @param x A numeric expression.
   */
  "Math.log10"(x: number): number;
  /**
   * Returns the base 2 logarithm of a number.
   *
   * @param x A numeric expression.
   */
  "Math.log2"(x: number): number;
  /**
   * Returns the natural logarithm of 1 + x.
   *
   * @param x A numeric expression.
   */
  "Math.log1p"(x: number): number;
  /**
   * Returns the result of (e^x - 1), which is an implementation-dependent
   * approximation to subtracting 1 from the exponential function of x (e
   * raised to the power of x, where e is the base of the natural logarithms).
   *
   * @param x A numeric expression.
   */
  "Math.expm1"(x: number): number;
  /**
   * Returns the hyperbolic cosine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  "Math.cosh"(x: number): number;
  /**
   * Returns the hyperbolic sine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  "Math.sinh"(x: number): number;
  /**
   * Returns the hyperbolic tangent of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  "Math.tanh"(x: number): number;
  /**
   * Returns the inverse hyperbolic cosine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  "Math.acosh"(x: number): number;
  /**
   * Returns the inverse hyperbolic sine of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  "Math.asinh"(x: number): number;
  /**
   * Returns the inverse hyperbolic tangent of a number.
   *
   * @param x A numeric expression that contains an angle measured in radians.
   */
  "Math.atanh"(x: number): number;
  /**
   * Returns the square root of the sum of squares of its arguments.
   *
   * @param values Values to compute the square root for. If no arguments are
   * passed, the result is +0. If there is only one argument, the result is the
   * absolute value. If any argument is +Infinity or -Infinity, the result is
   * +Infinity. If any argument is NaN, the result is NaN. If all arguments are
   * either +0 or −0, the result is +0.
   */
  "Math.hypot"(...values: number[]): number;
  /**
   * Returns the integral part of the numeric expression x, removing any
   * fractional digits. If x is already an integer, the result is x.
   *
   * @param x A numeric expression.
   */
  "Math.trunc"(x: number): number;
  /**
   * Returns the nearest single precision float representation of a number.
   *
   * @param x A numeric expression.
   */
  "Math.fround"(x: number): number;
  /**
   * Returns an implementation-dependent approximation to the cube root of
   * number.
   *
   * @param x A numeric expression.
   */
  "Math.cbrt"(x: number): number;
  /**
   * Creates an array from an array-like object.
   *
   * The mapper is required, where the standard library makes it optional:
   * without one, a source that names only a length answers with holes, and a
   * hole reads as `undefined` — which this language has no value for.
   *
   * @param arrayLike An array-like object to convert to an array.
   * @param mapfn A mapping function to call on every element of the array.
   */
  "Array.from"<T extends ClientValue, U extends ClientValue>(
    arrayLike: ArrayLike<T>,
    mapfn: (v: T, k: number) => U,
  ): U[];
  /**
   * Returns a new array from a set of elements.
   *
   * @param items A set of elements to include in the new array object.
   */
  "Array.of"<T extends ClientValue>(...items: T[]): T[];
  state<T extends ClientValue>(initial: T): State<T>;
}
