// What a node is, as position 0 carries it; never respelled.
export const NodeKind = {
  Element: "el",
  FunctionReference: "fn",
  Builtin: "bltn",
  Identifier: "id",
  CallExpression: "()",
  OptionalCallExpression: "?.()",
  PropertyAccessExpression: ".",
  OptionalPropertyAccessExpression: "?.",
  Assignment: "=",
  LogicalAnd: "&&",
  LogicalOr: "||",
  NullishCoalescing: "??",
  Addition: "+",
  Subtraction: "-",
  Multiplication: "*",
  Division: "/",
  Remainder: "%",
  StrictEquality: "===",
  StrictInequality: "!==",
  LessThan: "<",
  LessThanOrEqual: "<=",
  GreaterThan: ">",
  GreaterThanOrEqual: ">=",
  ConditionalExpression: "?:",
  ArrowFunction: "=>",
  Block: "{}",
  ConstDeclaration: "const",
  LetDeclaration: "let",
  IfStatement: "if",
  ReturnStatement: "return",
  ThrowStatement: "throw",
  TryStatement: "try",
  WhileStatement: "while",
  ForStatement: "for",
  BreakStatement: "break",
  ContinueStatement: "continue",
  ElementAccessExpression: "[]",
  CatchClause: "catch",
  Parameter: "param",
  LogicalNot: "!",
  Negation: "-x",
  SpreadElement: "...",
  ObjectLiteralExpression: "obj",
  PropertyAssignment: ":",
  ArrayLiteralExpression: "arr",
} as const;

export type NodeKind = (typeof NodeKind)[keyof typeof NodeKind];
