import { IsClass } from "../nodes/Class.js";
import { IsGeneric } from "../nodes/Generic.js";
import { IsRef } from "../nodes/Ref.js";
import { flatten } from "../flatten.js";
import { classLines } from "./typescript.js";
import type { ClientSchema } from "../ClientSchema.js";

// A schema to the surface the language itself offers.
//
// What `jsx` is for a target's tags, this is for the names a script reaches:
// the classes a client answers with, and the lists the compiler recognises.

/** The client surface a schema offers: its classes, and the names in scope. */
export function builtins(schema: ClientSchema): string {
  // Classes are this schema's own — a base's are that base's to write, and a
  // second declaration is a name two packages both export. Written inline
  // where the name a script reaches is also the type's name, and named in
  // `types` where it is not: `Array` is reached as `Array` and its type is
  // `ArrayConstructor`, because the first name is a type already.
  const classes = [
    ...Object.entries(schema.types),
    ...Object.entries(schema.globals),
  ].filter(([, node]) => IsClass(node));

  // Names are everything in scope, inherited included: what reads these is
  // asking what a script may reach, and a script reaches what its whole schema
  // declares.
  const all = flatten(schema);

  // Every name a class reaches has to be one the schema declares. A generated
  // file cannot import what a document does not name, and a schema that leans
  // on a type from the package it is generated into is not a document another
  // language can read.
  const walk = (node: unknown, bound: ReadonlySet<string>): void => {
    if (typeof node !== "object" || node === null) {
      return;
    }
    if (Array.isArray(node)) {
      node.forEach((one) => walk(one, bound));
      return;
    }
    const held = IsGeneric(node)
      ? new Set([...bound, ...node.parameters.map((one) => one.name)])
      : bound;
    if (IsRef(node) && !held.has(node.$ref) && !(node.$ref in all.types)) {
      throw new Error(
        `the schema names \`${node.$ref}\` and does not declare it`,
      );
    }
    Object.values(node).forEach((one) => walk(one, held));
  };
  classes.forEach(([, node]) => walk(node, new Set()));

  const lines: string[] = ["// Generated by `pnpm generate`. Do not edit.", ""];

  // What an unbounded type parameter reads as here, which is this generator's
  // to know rather than the schema's to name.
  if (JSON.stringify(classes).includes('"genericParameter"')) {
    lines.push('import type { ClientValue } from "./ClientValue.js";', "");
  }

  for (const [name, node] of classes) {
    lines.push(...classLines(name, node));
    lines.push("");
  }

  // Two lists, because the compiler asks two questions: which names a script
  // may write at all, and which of those stand for a value it may hold and read
  // members of. The schema answers the second by where the name was declared —
  // a global is the host's own, where `state` is a form and names nothing a
  // script can pass on.
  const globals = Object.keys(all.globals).sort();
  const names = [...globals, ...Object.keys(all.builtins)].sort();

  lines.push("/** Every name a script reaches without declaring it. */");
  lines.push(`export const BUILTIN_NAMES = [`);
  for (const name of names) {
    lines.push(`  ${JSON.stringify(name)},`);
  }
  lines.push(`] as const;`);
  lines.push("");
  lines.push(
    "/** The ones a script may reach as a value, and read members of. */",
  );
  lines.push(`export const BUILTIN_GLOBALS = [`);
  for (const name of globals) {
    lines.push(`  ${JSON.stringify(name)},`);
  }
  lines.push(`] as const;`);
  lines.push("");

  return lines.join("\n");
}
