import { IsGeneric } from "../nodes/Generic.js";
import { IsInterface } from "../nodes/Interface.js";
import { IsRef } from "../nodes/Ref.js";
import { flatten } from "../flatten.js";
import {
  documentation,
  interfaceLines,
  key,
  member,
  type,
} from "./typescript.js";
import type { Schema } from "../Schema.js";

// A schema to the names it declares, as the host language declares them.
//
// What `jsx` is for a target's tags, this is for everything a script reaches
// by name: the interfaces a client answers with, and the contract it owes. It
// declares and nothing else — a runtime is a different artifact, and so is a
// target's own, generated where it is.

/** What a schema declares: its types, and what a client must answer for. */
export function declarations(schema: Schema): string {
  // Names are everything in scope, inherited included: what reads these is
  // asking what a script may reach, and a script reaches what its whole schema
  // declares.
  const all = flatten(schema);

  // Every name a declaration reaches has to be one the schema declares. A
  // generated file cannot import what a document does not name, and a schema
  // that leans on a type from the package it is generated into is not a
  // document another language can read.
  const declares = (node: unknown, bound: ReadonlySet<string>): void => {
    if (typeof node !== "object" || node === null) {
      return;
    }
    if (Array.isArray(node)) {
      node.forEach((one) => declares(one, bound));
      return;
    }
    const held = IsGeneric(node)
      ? new Set([...bound, ...node.parameters.map((one) => one.name)])
      : bound;
    if (
      IsRef(node) &&
      !held.has(node.$ref) &&
      all.types[node.$ref] === undefined
    ) {
      throw new Error(
        `the schema names \`${node.$ref}\` and does not declare it`,
      );
    }
    Object.values(node).forEach((one) => declares(one, held));
  };
  Object.values(schema.types).forEach((node) => declares(node, new Set()));
  Object.values(schema.builtins).forEach((node) => declares(node, new Set()));

  const lines: string[] = ["// Generated by `pnpm generate`. Do not edit.", ""];

  // This schema's own and in the order it declares them — a base's names are
  // that base's to write, and a second declaration is a name two packages both
  // export. What a name stands for decides how it is written: an interface
  // where the node is one, and a named type everywhere else.
  for (const [name, node] of Object.entries(schema.types)) {
    lines.push(
      ...(IsInterface(node) || IsGeneric(node)
        ? interfaceLines(name, node)
        : [...documentation(node, ""), `export type ${name} = ${type(node)};`]),
    );
    lines.push("");
  }

  // What a client owes: one interface, because a client answers for these the
  // same way whether the host's lib declares the name or the framework does.
  // This schema's own names, not the flattened ones — a base's are answered by
  // the client that declared them, and a target's client composes.
  const owed = Object.entries(schema.builtins);
  if (owed.length > 0) {
    lines.push(
      "/** What a client must answer with, for every name in scope. */",
    );
    lines.push(`export interface Builtins {`);
    for (const [name, node] of owed) {
      // A name standing for a type it declares is a member holding one;
      // anything else is written as the signature it declares.
      lines.push(
        ...(IsRef(node)
          ? [`  ${key(name)}: ${node.$ref};`]
          : member(name, node)),
      );
    }
    lines.push(`}`);
    lines.push("");
  }

  return lines.join("\n");
}
