import { IsClass } from "../nodes/Class.js";
import { IsGeneric } from "../nodes/Generic.js";
import { IsInterface } from "../nodes/Interface.js";
import { IsRef } from "../nodes/Ref.js";
import { flatten } from "../flatten.js";
import {
  classLines,
  documentation,
  interfaceLines,
  key,
  member,
  type,
} from "./typescript.js";
import type { ClientSchema } from "../ClientSchema.js";
import type { TNode } from "../TNode.js";

// A schema to the host language's own names.
//
// What `jsx` is for a target's tags, this is for the globals a script reaches:
// the classes a client answers with, and the list the compiler recognises. A
// target's own names are a different artifact, generated where they are.

/** The globals a schema declares: their classes, the contract, the names. */
export function globals(schema: ClientSchema): string {
  // Classes are this schema's own — a base's are that base's to write, and a
  // second declaration is a name two packages both export. Written inline
  // where the name a script reaches is also the type's name, and named in
  // `types` where it is not: `Array` is reached as `Array` and its type is
  // `ArrayConstructor`, because the first name is a type already.
  const classes = [
    ...Object.entries(schema.types),
    ...Object.entries(schema.builtins),
    // A generic class is a class: `ClientArray<T>` is one declaration with a
    // parameter, and `classLines` writes either.
  ].filter(
    ([, node]) =>
      IsClass(node) || (IsGeneric(node) && IsClass(node.expression)),
  );

  // Names are everything in scope, inherited included: what reads these is
  // asking what a script may reach, and a script reaches what its whole schema
  // declares.
  const all = flatten(schema);

  // Every name a class reaches has to be one the schema declares. A generated
  // file cannot import what a document does not name, and a schema that leans
  // on a type from the package it is generated into is not a document another
  // language can read.
  const reached = new Map<string, TNode>();
  const walk = (node: unknown, bound: ReadonlySet<string>): void => {
    if (typeof node !== "object" || node === null) {
      return;
    }
    if (Array.isArray(node)) {
      node.forEach((one) => walk(one, bound));
      return;
    }
    const held = IsGeneric(node)
      ? new Set([...bound, ...node.parameters.map((one) => one.name)])
      : bound;
    if (IsRef(node) && !held.has(node.$ref)) {
      const named = all.types[node.$ref];
      if (named === undefined) {
        throw new Error(
          `the schema names \`${node.$ref}\` and does not declare it`,
        );
      }
      // A type a class reaches is declared beside it: a generated file cannot
      // import what the document does not name. Classes are emitted already,
      // so what is collected here is everything else.
      if (!IsClass(named) && !reached.has(node.$ref)) {
        reached.set(node.$ref, named);
        walk(named, held);
      }
    }
    Object.values(node).forEach((one) => walk(one, held));
  };
  classes.forEach(([, node]) => walk(node, new Set()));
  // A builtin's signature names types too — `state` answers with a `State<T>` —
  // and those are this file's to declare for the same reason a class's are.
  Object.values(schema.builtins).forEach((node) => walk(node, new Set()));

  // Every name a script may write, and what may be read off it. An entry with
  // no members is a name that is whole on its own; `Math` is not one, because
  // there is nothing to do with `Math` but read a member of it.
  const reach = (node: TNode): readonly string[] => {
    const held = IsRef(node) ? all.types[node.$ref] : node;
    if (held === undefined) {
      return [];
    }
    const inner = IsGeneric(held) ? held.expression : held;
    return IsClass(inner) ? Object.keys(inner.members).sort() : [];
  };
  const table = (of: Readonly<Record<string, TNode>>): string[] =>
    Object.keys(of)
      .sort()
      .map((name) => {
        const members = reach(of[name] as TNode);
        return members.length === 0
          ? `  ${key(name)}: {},`
          : `  ${key(name)}: { ${members
              .map((one) => `${key(one)}: true`)
              .join(", ")} },`;
      });

  const lines: string[] = ["// Generated by `pnpm generate`. Do not edit.", ""];
  lines.push("/** A name a script may write, and what may be read off it. */");
  lines.push(
    "type Members = { readonly [name: string]: { readonly [member: string]: true } };",
  );
  lines.push("");

  // What an unbounded type parameter reads as here, which is this generator's
  // to know rather than the schema's to name.
  if (JSON.stringify(classes).includes('"genericParameter"')) {
    lines.push('import type { ClientValue } from "./ClientValue.js";', "");
  }

  for (const [name, node] of reached) {
    lines.push(
      ...(IsInterface(node) || IsGeneric(node)
        ? interfaceLines(name, node)
        : [...documentation(node, ""), `export type ${name} = ${type(node)};`]),
    );
    lines.push("");
  }

  for (const [name, node] of classes) {
    lines.push(...classLines(name, node));
    lines.push("");
  }

  // What a client owes: one interface, because a client answers for these the
  // same way whether the host's lib declares the name or the framework does.
  // This schema's own names, not the flattened ones — a base's are answered by
  // the client that declared them, and a target's client composes.
  const owed = Object.entries(schema.builtins);
  if (owed.length > 0) {
    lines.push(
      "/** What a client must answer with, for every name in scope. */",
    );
    lines.push(`export interface Builtins {`);
    for (const [name, node] of owed) {
      // A name standing for a class is a member holding one; anything else is
      // written as the signature it declares.
      lines.push(
        ...(IsRef(node) && IsClass(all.types[node.$ref] as TNode)
          ? [`  ${key(name)}: ${node.$ref};`]
          : member(name, node)),
      );
    }
    lines.push(`}`);
    lines.push("");
  }

  // What a member access on a primitive reaches, by the value that autoboxes to
  // it. A client answers these the way it answers a global: from a list the
  // schema chose, so a member left out stays left out rather than falling
  // through to whatever the host's own prototypes happen to hold.
  const boxed = classes
    .map(([name, node]) => {
      const held = IsGeneric(node) ? node.expression : node;
      const boxes = IsClass(held) ? held.boxes : undefined;
      return boxes === undefined
        ? undefined
        : ([boxes, IsGeneric(node) ? `${name}<Value>` : name] as const);
    })
    .filter((one) => one !== undefined)
    .sort(([a], [b]) => a.localeCompare(b));

  if (boxed.length > 0) {
    lines.push(
      "/** What a client must answer with, for a member of an autoboxed value. */",
    );
    lines.push(`export interface Boxes {`);
    for (const [boxes, held] of boxed) {
      lines.push(`  ${boxes}: ${held};`);
    }
    lines.push(`}`);
    lines.push("");
  }

  // Two tables of one shape, because a name is reached the same way whichever
  // it is in: what differs is only how the typechecker is shown it, and the
  // compiler is what needs telling them apart.
  const lib = Object.fromEntries(
    Object.entries(all.builtins).filter(([, node]) => node.global === true),
  );
  const own = Object.fromEntries(
    Object.entries(all.builtins).filter(([, node]) => node.global !== true),
  );

  lines.push(
    "/** Every name the host's own lib declares, and what may be read",
  );
  lines.push(
    " * off it. A script names one of these plainly, where the rest are",
  );
  lines.push(" * read through `cs`. */");
  lines.push(`export const GLOBAL_BUILTINS: Members = {`);
  lines.push(...table(lib));
  lines.push(`};`);
  lines.push("");
  lines.push("/** Every name the framework provides, and what may be read off");
  lines.push(" * it. A member absent from both tables is a name this language");
  lines.push(" * does not have, however the host spells it. */");
  lines.push(`export const BUILTIN_MEMBERS: Members = {`);
  lines.push(...table(own));
  lines.push(`};`);
  lines.push("");

  return lines.join("\n");
}
