import { IsClass } from "../nodes/Class.js";
import { IsGeneric } from "../nodes/Generic.js";
import { IsRef } from "../nodes/Ref.js";
import { flatten } from "../flatten.js";
import { classLines } from "./typescript.js";
import type { ClientSchema } from "../ClientSchema.js";

// A schema to the host language's own names.
//
// What `jsx` is for a target's tags, this is for the globals a script reaches:
// the classes a client answers with, and the list the compiler recognises. A
// target's own names are a different artifact, generated where they are.

/** The globals a schema declares: their classes, the contract, the names. */
export function globals(schema: ClientSchema): string {
  // Classes are this schema's own — a base's are that base's to write, and a
  // second declaration is a name two packages both export. Written inline
  // where the name a script reaches is also the type's name, and named in
  // `types` where it is not: `Array` is reached as `Array` and its type is
  // `ArrayConstructor`, because the first name is a type already.
  const classes = [
    ...Object.entries(schema.types),
    ...Object.entries(schema.globals),
  ].filter(([, node]) => IsClass(node));

  // Names are everything in scope, inherited included: what reads these is
  // asking what a script may reach, and a script reaches what its whole schema
  // declares.
  const all = flatten(schema);

  // Every name a class reaches has to be one the schema declares. A generated
  // file cannot import what a document does not name, and a schema that leans
  // on a type from the package it is generated into is not a document another
  // language can read.
  const walk = (node: unknown, bound: ReadonlySet<string>): void => {
    if (typeof node !== "object" || node === null) {
      return;
    }
    if (Array.isArray(node)) {
      node.forEach((one) => walk(one, bound));
      return;
    }
    const held = IsGeneric(node)
      ? new Set([...bound, ...node.parameters.map((one) => one.name)])
      : bound;
    if (IsRef(node) && !held.has(node.$ref) && !(node.$ref in all.types)) {
      throw new Error(
        `the schema names \`${node.$ref}\` and does not declare it`,
      );
    }
    Object.values(node).forEach((one) => walk(one, held));
  };
  classes.forEach(([, node]) => walk(node, new Set()));

  const lines: string[] = ["// Generated by `pnpm generate`. Do not edit.", ""];

  // What an unbounded type parameter reads as here, which is this generator's
  // to know rather than the schema's to name.
  if (JSON.stringify(classes).includes('"genericParameter"')) {
    lines.push('import type { ClientValue } from "./ClientValue.js";', "");
  }

  for (const [name, node] of classes) {
    lines.push(...classLines(name, node));
    lines.push("");
  }

  // What a client owes, one interface per record so each says what its name
  // says. A target's `builtins` join as a second one where they are generated;
  // both are looked up through the same table, because the format has one node
  // for a name it carries.
  //
  // This schema's own names, not the flattened ones: a base's are answered by
  // the client that declared them, and a target's client composes.
  const owed = Object.entries(schema.globals).map(
    ([name, node]) => [name, IsRef(node) ? node.$ref : name] as const,
  );

  if (owed.length > 0) {
    lines.push("/** What a client must answer with, for every global. */");
    lines.push(`export interface Globals {`);
    for (const [name, held] of owed) {
      lines.push(`  ${name}: ${held};`);
    }
    lines.push(`}`);
    lines.push("");
  }

  // One list: the names the compiler recognises without a binding. A builtin
  // is not among them — `state` is matched by its call shape, and a target's is
  // reached by splicing what this generates.
  const globalNames = Object.keys(all.globals).sort();

  lines.push("/** Every global a script reaches without declaring it. */");
  lines.push(`export const GLOBAL_NAMES = [`);
  for (const name of globalNames) {
    lines.push(`  ${JSON.stringify(name)},`);
  }
  lines.push(`] as const;`);
  lines.push("");

  return lines.join("\n");
}
