import { IsClass } from "../nodes/Class.js";
import { IsGeneric } from "../nodes/Generic.js";
import { IsInterface } from "../nodes/Interface.js";
import { IsRef } from "../nodes/Ref.js";
import { flatten } from "../flatten.js";
import {
  classLines,
  documentation,
  interfaceLines,
  key,
  member,
  type,
  typeParameter,
} from "./typescript.js";
import type { Schema } from "../Schema.js";
import type { TGenericParameter } from "../nodes/GenericParameter.js";
import type { TNode } from "../TNode.js";

// A schema to the host language's own names.
//
// What `jsx` is for a target's tags, this is for the globals a script reaches:
// the classes a client answers with, and the list the compiler recognises. A
// target's own names are a different artifact, generated where they are.

/** The globals a schema declares: their classes, the contract, the names. */
export function globals(schema: Schema): string {
  // Classes are this schema's own — a base's are that base's to write, and a
  // second declaration is a name two packages both export. Written inline
  // where the name a script reaches is also the type's name, and named in
  // `types` where it is not: `Array` is reached as `Array` and its type is
  // `ArrayConstructor`, because the first name is a type already.
  const classes = [
    ...Object.entries(schema.types),
    ...Object.entries(schema.builtins),
    // A generic class is a class: `ClientArray<T>` is one declaration with a
    // parameter, and `classLines` writes either.
  ].filter(
    ([, node]) =>
      IsClass(node) || (IsGeneric(node) && IsClass(node.expression)),
  );

  // Names are everything in scope, inherited included: what reads these is
  // asking what a script may reach, and a script reaches what its whole schema
  // declares.
  const all = flatten(schema);

  // Every name a class reaches has to be one the schema declares. A generated
  // file cannot import what a document does not name, and a schema that leans
  // on a type from the package it is generated into is not a document another
  // language can read.
  const reached = new Map<string, TNode>();
  const walk = (node: unknown, bound: ReadonlySet<string>): void => {
    if (typeof node !== "object" || node === null) {
      return;
    }
    if (Array.isArray(node)) {
      node.forEach((one) => walk(one, bound));
      return;
    }
    const held = IsGeneric(node)
      ? new Set([...bound, ...node.parameters.map((one) => one.name)])
      : bound;
    if (IsRef(node) && !held.has(node.$ref)) {
      const named = all.types[node.$ref];
      if (named === undefined) {
        throw new Error(
          `the schema names \`${node.$ref}\` and does not declare it`,
        );
      }
      // A type a class reaches is declared beside it: a generated file cannot
      // import what the document does not name. Classes are emitted already,
      // so what is collected here is everything else.
      if (!IsClass(named) && !reached.has(node.$ref)) {
        reached.set(node.$ref, named);
        walk(named, held);
      }
    }
    Object.values(node).forEach((one) => walk(one, held));
  };
  classes.forEach(([, node]) => walk(node, new Set()));
  // A builtin's signature names types too — `state` answers with a `State<T>` —
  // and those are this file's to declare for the same reason a class's are.
  Object.values(schema.builtins).forEach((node) => walk(node, new Set()));

  const lines: string[] = ["// Generated by `pnpm generate`. Do not edit.", ""];

  for (const [name, node] of reached) {
    lines.push(
      ...(IsInterface(node) || IsGeneric(node)
        ? interfaceLines(name, node)
        : [...documentation(node, ""), `export type ${name} = ${type(node)};`]),
    );
    lines.push("");
  }

  for (const [name, node] of classes) {
    lines.push(...classLines(name, node));
    lines.push("");
  }

  // What a client owes: one interface, because a client answers for these the
  // same way whether the host's lib declares the name or the framework does.
  // This schema's own names, not the flattened ones — a base's are answered by
  // the client that declared them, and a target's client composes.
  const owed = Object.entries(schema.builtins);
  if (owed.length > 0) {
    lines.push(
      "/** What a client must answer with, for every name in scope. */",
    );
    lines.push(`export interface Builtins {`);
    for (const [name, node] of owed) {
      // A name standing for a class is a member holding one; anything else is
      // written as the signature it declares.
      lines.push(
        ...(IsRef(node) && IsClass(all.types[node.$ref] as TNode)
          ? [`  ${key(name)}: ${node.$ref};`]
          : member(name, node)),
      );
    }
    lines.push(`}`);
    lines.push("");
  }

  // What a member access on a primitive reaches, by the value that autoboxes to
  // it. A client answers these the way it answers a global: from a list the
  // schema chose, so a member left out stays left out rather than falling
  // through to whatever the host's own prototypes happen to hold.
  const boxed = classes
    .map(([name, node]) => {
      const held = IsGeneric(node) ? node.expression : node;
      const boxes = IsClass(held) ? held.boxes : undefined;
      return boxes === undefined
        ? undefined
        : ({
            boxes,
            name,
            // What a boxed container holds is the client's own domain, so the
            // class's own parameters are carried out to this interface and the
            // client fills them in. Nothing here names them.
            parameters: IsGeneric(node) ? node.parameters : [],
          } as const);
    })
    .filter((one) => one !== undefined)
    .sort((a, b) => a.boxes.localeCompare(b.boxes));

  // Every parameter a boxed container declares, in the order they are boxed.
  // Two containers naming one parameter would be two things asking to be
  // filled in by one, which is a schema to fix rather than a name to invent.
  const holds: TGenericParameter[] = [];
  for (const { boxes, parameters } of boxed) {
    for (const parameter of parameters) {
      if (holds.some((held) => held.name === parameter.name)) {
        throw new Error(
          `a boxed \`${boxes}\` names \`${parameter.name}\`, and so does another`,
        );
      }
      holds.push(parameter);
    }
  }

  if (boxed.length > 0) {
    const declared =
      holds.length === 0
        ? ""
        : `<${holds.map((one) => typeParameter(one)).join(", ")}>`;
    lines.push(
      "/** What a client must answer with, for a member of an autoboxed value. */",
    );
    lines.push(`export interface Boxes${declared} {`);
    for (const { boxes, name, parameters } of boxed) {
      const applied =
        parameters.length === 0
          ? ""
          : `<${parameters.map((one) => one.name).join(", ")}>`;
      lines.push(`  ${boxes}: ${name}${applied};`);
    }
    lines.push(`}`);
    lines.push("");
  }

  return lines.join("\n");
}
