// The `jsx-dev-runtime` a project ships beside its `jsx-runtime`.
//
// What the JSX transform imports when it is compiled for development, which is
// a decision the toolchain makes and not the app. It answers with the same
// functions under the names that transform expects, so a project that
// generates one runtime has to generate this too — a schema says nothing about
// it, and a project should not have to know it exists.

/** The development runtime, which is the runtime beside it under other names. */
export function jsxDev(): string {
  return [
    "// Generated by `pnpm generate`. Do not edit.",
    "",
    'export { jsx as jsxDEV, jsxs, Fragment } from "../jsx-runtime/index.js";',
    'export type { JSX } from "../jsx-runtime/index.js";',
  ].join("\n");
}
